export const canvasShortcuts = {
  'canvas-host': [
    '[.puppet-editor_&]:w-full [.puppet-editor_&]:h-full',
    '[.puppet-editor_&_canvas]:w-full [.puppet-editor_&_canvas]:h-full',
    '[.puppet-editor_&_canvas]:block',
  ],
  'deformer-edit-message': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[right:1.125rem] [.puppet-editor_&]:[bottom:1.125rem]',
    '[.puppet-editor_&]:[left:1.125rem] [.puppet-editor_&]:[margin:0_auto]',
    '[.puppet-editor_&]:[padding:0.5625rem_0.75rem] [.puppet-editor_&]:[border:0.0625rem_solid_#725e31]',
    '[.puppet-editor_&]:[border-radius:0.5rem] [.puppet-editor_&]:[color:#ffe0a3]',
    '[.puppet-editor_&]:[background:rgb(34_29_18_/_92%)] [.puppet-editor_&]:[font-size:0.6875rem]',
    '[.puppet-editor_&]:[line-height:1.5] [.puppet-editor_&]:text-center',
  ],
  'deformer-editor': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[inset:0] [.puppet-editor_&]:pointer-events-none',
    '[.puppet-editor_&_svg]:absolute [.puppet-editor_&_svg]:[inset:0] [.puppet-editor_&_svg]:w-full',
    '[.puppet-editor_&_svg]:h-full [.puppet-editor_&_svg]:[overflow:visible]',
    '[.puppet-editor_&_svg]:pointer-events-auto [.puppet-editor_&_svg]:touch-none',
    '[.puppet-editor_&_line]:fill-none [.puppet-editor_&_line]:[stroke:#ffbd59]',
    '[.puppet-editor_&_line]:[stroke-width:0.09375rem]',
    '[.puppet-editor_&_line]:[vector-effect:non-scaling-stroke]',
    '[.puppet-editor_&_path]:fill-none [.puppet-editor_&_path]:[stroke:#ffbd59]',
    '[.puppet-editor_&_path]:[stroke-width:0.09375rem]',
    '[.puppet-editor_&_path]:[vector-effect:non-scaling-stroke]',
    '[.puppet-editor_&_.translation-handle]:[fill:transparent]',
    '[.puppet-editor_&_.translation-handle]:[stroke:none]',
    '[.puppet-editor_&_.translation-handle]:[pointer-events:fill]',
    '[.puppet-editor_&_.translation-handle]:cursor-grab',
    '[.puppet-editor_&_.translation-handle:active]:cursor-grabbing',
    '[.puppet-editor_&_line]:pointer-events-none',
    '[.puppet-editor_&_.grid-deformer-controls_>_path:not(.translation-handle)]:pointer-events-none',
    '[.puppet-editor_&_circle]:[fill:#111715] [.puppet-editor_&_circle]:[stroke:#ffbd59]',
    '[.puppet-editor_&_circle]:[stroke-width:0.125rem]',
    '[.puppet-editor_&_circle]:[vector-effect:non-scaling-stroke] [.puppet-editor_&_circle]:cursor-grab',
    '[.puppet-editor_&_circle:active]:cursor-grabbing',
    '[.puppet-editor_&_.rotation-origin-hit]:[fill:transparent]',
    '[.puppet-editor_&_.rotation-origin-hit]:[stroke:transparent]',
    '[.puppet-editor_&_.rotation-origin-hit]:[cursor:move]',
    '[.puppet-editor_&_.rotation-origin-hit]:[pointer-events:all]',
    '[.puppet-editor_&_.rotation-origin-hit:active]:[fill:transparent]',
    '[.puppet-editor_&_.rotation-origin-hit:active]:[stroke:transparent]',
    '[.puppet-editor_&_.rotation-origin-hit:active]:[cursor:move]',
    '[.puppet-editor_&_.rotation-origin-hit:active]:[pointer-events:all]',
    '[.puppet-editor_&_.rotation-origin]:fill-none [.puppet-editor_&_.rotation-origin]:cursor-default',
    '[.puppet-editor_&_.rotation-origin]:pointer-events-none',
    '[.puppet-editor_&_circle.selected]:[fill:#ffbd59] [.puppet-editor_&_circle.selected]:[stroke:#fff1d6]',
    '[.puppet-editor_&_circle.selected]:[stroke-width:0.1875rem]',
    '[.puppet-editor_&_.curve-handle-line]:[stroke:#ff7087]',
    '[.puppet-editor_&_.curve-handle-line]:[stroke-dasharray:4_3]',
    '[.puppet-editor_&_.curve-handle]:[fill:#ff7087] [.puppet-editor_&_.curve-handle]:[stroke:#fff1f4]',
    '[.puppet-editor_&_.blocked_line]:[stroke:#66716d]',
    '[.puppet-editor_&_.blocked_path]:[stroke:#66716d]',
    '[.puppet-editor_&_.blocked_circle]:[stroke:#66716d]',
    '[.puppet-editor_&_.blocked_circle]:[fill:#202825] [.puppet-editor_&_.blocked_circle]:cursor-not-allowed',
    '[.puppet-editor_&_.blocked_.translation-handle]:cursor-not-allowed',
    '[.puppet-editor_&_.blocked_.rotation-origin]:fill-none',
    '[.puppet-editor_&_.blocked_.rotation-origin-hit]:fill-none',
    '[.puppet-editor_&_.blocked_.rotation-origin-hit]:cursor-not-allowed',
    '[.puppet-editor_&_.blocked_.rotation-origin-hit]:[fill:transparent]',
    '[.puppet-editor_&_.blocked_.rotation-origin-hit]:[stroke:transparent]',
  ],
  'deformer-properties': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[gap:0.5rem] [.puppet-editor_&]:[margin:0.875rem_0_0]',
    '[.puppet-editor_&]:[padding:0.625rem] [.puppet-editor_&]:[border:0.0625rem_solid_#313b37]',
    '[.puppet-editor_&]:[border-radius:0.5rem]',
    '[.puppet-editor_&_legend]:[padding:0_0.3125rem] [.puppet-editor_&_legend]:[color:#bfeee1]',
    '[.puppet-editor_&_legend]:[font-size:0.625rem]',
    '[.puppet-editor_&_label]:grid [.puppet-editor_&_label]:[grid-template-columns:3.375rem_minmax(0,_1fr)]',
    '[.puppet-editor_&_label]:[gap:0.4375rem] [.puppet-editor_&_label]:items-center',
    '[.puppet-editor_&_label]:[color:#84918c] [.puppet-editor_&_label]:[font-size:0.5625rem]',
    "[.puppet-editor_&_input:not([type='checkbox'],_[type='color'],_[type='number'])]:w-full",
    "[.puppet-editor_&_input:not([type='checkbox'],_[type='color'],_[type='number'])]:min-w-0",
    "[.puppet-editor_&_input:not([type='checkbox'],_[type='color'],_[type='number'])]:[padding:0.3125rem_0.375rem]",
    "[.puppet-editor_&_input:not([type='checkbox'],_[type='color'],_[type='number'])]:[border:0.0625rem_solid_#35413d]",
    "[.puppet-editor_&_input:not([type='checkbox'],_[type='color'],_[type='number'])]:[border-radius:0.3125rem]",
    "[.puppet-editor_&_input:not([type='checkbox'],_[type='color'],_[type='number'])]:[color:#dfe8e4]",
    "[.puppet-editor_&_input:not([type='checkbox'],_[type='color'],_[type='number'])]:[background:#121816]",
    "[.puppet-editor_&_input:not([type='checkbox'],_[type='color'],_[type='number'])]:[font:inherit]",
    '[.puppet-editor_&_select]:w-full [.puppet-editor_&_select]:min-w-0',
    '[.puppet-editor_&_select]:[padding:0.3125rem_0.375rem]',
    '[.puppet-editor_&_select]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_select]:[border-radius:0.3125rem] [.puppet-editor_&_select]:[color:#dfe8e4]',
    '[.puppet-editor_&_select]:[background:#121816] [.puppet-editor_&_select]:[font:inherit]',
    "[.puppet-editor_&_input[type='color']]:w-full [.puppet-editor_&_input[type='color']]:min-w-0",
    "[.puppet-editor_&_input[type='color']]:[height:1.75rem]",
    "[.puppet-editor_&_input[type='color']]:[padding:0.125rem]",
    "[.puppet-editor_&_input[type='color']]:[border:0.0625rem_solid_#35413d]",
    "[.puppet-editor_&_input[type='color']]:[border-radius:0.3125rem]",
    "[.puppet-editor_&_input[type='color']]:[background:#121816]",
  ],
  'display-controls': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:[gap:0.625rem]',
    '[.puppet-editor_&]:[padding:0.5rem_0.625rem] [.puppet-editor_&]:[border:1px_solid_#35413d]',
    '[.puppet-editor_&]:[border-radius:0.5625rem] [.puppet-editor_&]:[background:rgb(11_15_14_/_88%)]',
    '[.puppet-editor_&]:pointer-events-auto',
    '[.puppet-editor_&:empty]:hidden',
  ],
  'error-message': ['[.puppet-editor_&]:[color:#ff9b96]'],
  'mask-boundary-toggle': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:[gap:0.3125rem]',
    '[.puppet-editor_&]:[padding:0_0.25rem] [.puppet-editor_&]:[color:#c7d0cc]',
    '[.puppet-editor_&]:[font-size:0.625rem] [.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&_input]:m-0 [.puppet-editor_&_input]:[accent-color:#64e5c4]',
  ],
  'mesh-editor': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[inset:0] [.puppet-editor_&]:pointer-events-none',
    '[.puppet-editor_&_svg]:absolute [.puppet-editor_&_svg]:[inset:0] [.puppet-editor_&_svg]:w-full',
    '[.puppet-editor_&_svg]:h-full [.puppet-editor_&_svg]:[overflow:visible]',
    '[.puppet-editor_&_svg]:pointer-events-auto [.puppet-editor_&_svg]:touch-none',
    '[.puppet-editor_&_polygon]:[fill:rgb(100_229_196_/_4%)]',
    '[.puppet-editor_&_polygon]:[stroke:rgb(100_229_196_/_58%)]',
    '[.puppet-editor_&_polygon]:[stroke-width:0.0625rem]',
    '[.puppet-editor_&_polygon]:[vector-effect:non-scaling-stroke]',
    '[.puppet-editor_&_.clipped-part-preview]:pointer-events-none',
    '[.puppet-editor_&_.clipped-part-preview_.clipped-part-boundary]:[clip-path:var(--active-mask-clip)]',
    '[.puppet-editor_&_.clipped-part-preview_.clipped-part-boundary]:fill-none',
    '[.puppet-editor_&_.clipped-part-preview_.clipped-part-boundary]:[stroke-width:2px]',
    '[.puppet-editor_&_.clipped-part-preview_.clipped-part-boundary]:[vector-effect:non-scaling-stroke]',
    '[.puppet-editor_&_.clipped-part-preview_.boundary-base]:[stroke:#000]',
    '[.puppet-editor_&_.clipped-part-preview_.boundary-dashes]:[stroke:#fff]',
    '[.puppet-editor_&_.clipped-part-preview_.boundary-dashes]:[stroke-dasharray:6_6]',
    '[.puppet-editor_&_.clipped-part-preview_.boundary-dashes]:animate-mask-march',
    '[@media(prefers-reduced-motion:reduce)]:[.puppet-editor_&_.clipped-part-preview_.boundary-dashes]:animate-none',
    '[.puppet-editor_&_circle]:[fill:#101513] [.puppet-editor_&_circle]:[stroke:#64e5c4]',
    '[.puppet-editor_&_circle]:[stroke-width:0.125rem]',
    '[.puppet-editor_&_circle]:[vector-effect:non-scaling-stroke] [.puppet-editor_&_circle]:cursor-grab',
    '[.puppet-editor_&_circle:active]:cursor-grabbing',
    '[.puppet-editor_&_circle.selected]:[fill:#ffbd59] [.puppet-editor_&_circle.selected]:[stroke:#fff1d6]',
    '[.puppet-editor_&_>_.display-controls]:absolute [.puppet-editor_&_>_.display-controls]:[top:0.75rem]',
    '[.puppet-editor_&_>_.display-controls]:[right:0.75rem]',
    '[.puppet-editor_&_svg:focus-visible]:[outline:1px_solid_#64e5c4]',
    '[.puppet-editor_&_svg:focus-visible]:[outline-offset:-1px]',
  ],
  'player-canvas': ['[.puppet-editor_&]:w-full [.puppet-editor_&]:h-full'],
  viewport: [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:min-h-0',
    '[.puppet-editor_&]:overflow-hidden [.puppet-editor_&]:[background-color:#111715]',
    '[.puppet-editor_&]:[background-image:radial-gradient(#34413d_0.046875rem,_transparent_0.046875rem)]',
    '[.puppet-editor_&]:[background-size:1.125rem_1.125rem]',
  ],
  'viewport-display': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0.75rem] [.puppet-editor_&]:[right:0.75rem]',
  ],
  'viewport-message': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[inset:50%_auto_auto_50%] [.puppet-editor_&]:m-0',
    '[.puppet-editor_&]:[color:#7f8d88] [.puppet-editor_&]:[font-size:0.75rem]',
    '[.puppet-editor_&]:[transform:translate(-50%,_-50%)]',
  ],
  'viewport-panel': [
    '[.puppet-editor_&]:[grid-area:viewport] [.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&]:min-h-0 [.puppet-editor_&]:[grid-template-rows:minmax(0,_1fr)]',
    '[.puppet-editor_&]:[background:#0d1210]',
  ],
}
