export const dialogsShortcuts = {
  'auto-mesh-dialog-content': [
    '[&[data-closed]]:hidden',
    'fixed [top:50%] [left:50%] [width:min(32.5rem,_calc(100vw_-_2rem))] [max-height:calc(100vh_-_2rem)]',
    'overflow-y-auto [border:0.0625rem_solid_#3c4b46] [border-radius:0.75rem] [outline:none] [color:#e8f0ed]',
    '[background:#111714] [box-shadow:0_1.5rem_4.375rem_rgb(0_0_0_/_48%)]',
    "[font-family:Inter,_ui-sans-serif,_system-ui,_-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_sans-serif]",
    '[transform:translate(-50%,_-50%)]',
    '[&_form]:grid [&_form]:[gap:1.25rem] [&_form]:[padding:1.375rem]',
    '[&_header]:flex [&_header]:[gap:1rem] [&_header]:items-center [&_header]:justify-between',
    '[&_footer]:flex [&_footer]:[gap:1rem] [&_footer]:items-center [&_footer]:justify-between',
    '[&_header_>_div]:grid [&_header_>_div]:[gap:0.3125rem]',
    '[&_h2]:m-0 [&_h2]:[font-size:1.0625rem]',
    '[&_header_p]:m-0 [&_header_p]:[color:#91a09a] [&_header_p]:[font-size:0.6875rem]',
    '[&_header_p]:[line-height:1.5]',
    '[&_header_button]:[width:1.875rem] [&_header_button]:[height:1.875rem] [&_header_button]:[flex:none]',
    '[&_header_button]:p-0 [&_header_button]:[border:0] [&_header_button]:[border-radius:0.375rem]',
    '[&_header_button]:[color:#96a39e] [&_header_button]:[background:transparent]',
    '[&_header_button]:[font-size:1.375rem] [&_header_button]:cursor-pointer',
    '[&_header_button:hover]:[color:#f0f7f4] [&_header_button:hover]:[background:#25302c]',
    '[&_button:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[&_button:focus-visible]:[outline-offset:0.125rem]',
    "[&_input[type='number']:focus-visible]:[outline:0.125rem_solid_#64e5c4]",
    "[&_input[type='number']:focus-visible]:[outline-offset:0.125rem]",
    '[&_.editor-number-field]:relative [&_.editor-number-field]:flex [&_.editor-number-field]:box-border',
    '[&_.editor-number-field]:w-full [&_.editor-number-field]:min-w-0 [&_.editor-number-field]:items-center',
    '[&_.editor-number-field]:overflow-hidden [&_.editor-number-field]:[border:0.0625rem_solid_#35413d]',
    '[&_.editor-number-field]:[border-radius:0.3125rem] [&_.editor-number-field]:[color:#dfe8e4]',
    '[&_.editor-number-field]:[background:#121816]',
    '[&_.editor-number-field[data-bounded]::before]:absolute',
    '[&_.editor-number-field[data-bounded]::before]:[inset:0_auto_0_0]',
    '[&_.editor-number-field[data-bounded]::before]:[width:var(--number-field-progress)]',
    '[&_.editor-number-field[data-bounded]::before]:[background:#24443b]',
    "[&_.editor-number-field[data-bounded]::before]:[content:'']",
    '[&_.editor-number-field[data-bounded]::before]:pointer-events-none',
    '[&_.editor-number-field:focus-within]:[border-color:#64e5c4]',
    '[&_.editor-number-field:focus-within]:[outline:0.0625rem_solid_#64e5c4]',
    '[&_.editor-number-field:focus-within]:[outline-offset:0.0625rem]',
    '[&_.editor-number-field:has(input:disabled)]:[border-color:#303936]',
    '[&_.editor-number-field:has(input:disabled)]:[color:#77837e]',
    '[&_.editor-number-field:has(input:disabled)]:[background:#111613]',
    "[&_.editor-number-field_>_input[type='number']]:relative",
    "[&_.editor-number-field_>_input[type='number']]:w-full",
    "[&_.editor-number-field_>_input[type='number']]:min-w-0",
    "[&_.editor-number-field_>_input[type='number']]:[flex:1]",
    "[&_.editor-number-field_>_input[type='number']]:[padding:0.3125rem_0.4375rem]",
    "[&_.editor-number-field_>_input[type='number']]:[border:0]",
    "[&_.editor-number-field_>_input[type='number']]:[border-radius:0]",
    "[&_.editor-number-field_>_input[type='number']]:[outline:0]",
    "[&_.editor-number-field_>_input[type='number']]:[color:inherit]",
    "[&_.editor-number-field_>_input[type='number']]:[background:transparent]",
    "[&_.editor-number-field_>_input[type='number']]:[font:inherit]",
    "[&_.editor-number-field_>_input[type='number']]:[cursor:ew-resize]",
    "[&_.editor-number-field_>_input[type='number']]:[appearance:textfield]",
    "[&_.editor-number-field_>_input[type='number']]:touch-none",
    "[&_.editor-number-field_>_input[type='number']:focus:not(:active)]:[cursor:text]",
    "[&_.editor-number-field.scrubbing_>_input[type='number']]:[cursor:ew-resize]",
    "[&_.editor-number-field.scrubbing_>_input[type='number']]:select-none",
    "[&_.editor-number-field_>_input[type='number']::-webkit-inner-spin-button]:m-0",
    "[&_.editor-number-field_>_input[type='number']::-webkit-inner-spin-button]:[appearance:none]",
    "[&_.editor-number-field_>_input[type='number']::-webkit-outer-spin-button]:m-0",
    "[&_.editor-number-field_>_input[type='number']::-webkit-outer-spin-button]:[appearance:none]",
    '[&_.editor-number-field_>_span]:relative [&_.editor-number-field_>_span]:[padding-right:0.4375rem]',
    '[&_.editor-number-field_>_span]:[color:#81908a]',
    "[&_.editor-number-field_>_span]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[&_.editor-number-field_>_span]:[font-size:0.5625rem] [&_.editor-number-field_>_span]:pointer-events-none',
    '[&_.editor-number-step]:relative [&_.editor-number-step]:grid [&_.editor-number-step]:[width:1.25rem]',
    '[&_.editor-number-step]:[align-self:stretch] [&_.editor-number-step]:[flex:0_0_1.25rem]',
    '[&_.editor-number-step]:place-items-center [&_.editor-number-step]:p-0 [&_.editor-number-step]:[border:0]',
    '[&_.editor-number-step]:[border-radius:0] [&_.editor-number-step]:[color:#91a19a]',
    '[&_.editor-number-step]:[background:#18201d] [&_.editor-number-step]:[font:inherit]',
    '[&_.editor-number-step]:cursor-pointer',
    '[&_.editor-number-step.decrement]:[border-right:0.0625rem_solid_#35413d]',
    '[&_.editor-number-step.increment]:[border-left:0.0625rem_solid_#35413d]',
    '[&_.editor-number-step:hover:not(:disabled)]:[color:#dffff6]',
    '[&_.editor-number-step:hover:not(:disabled)]:[background:#29443b]',
    '[&_.editor-number-step:focus-visible]:[outline:0.0625rem_solid_#64e5c4]',
    '[&_.editor-number-step:focus-visible]:[outline-offset:-0.125rem]',
    '[&_.editor-number-step:disabled]:[color:#4b5752] [&_.editor-number-step:disabled]:cursor-default',
    '[&_.editor-number-step_>_span]:box-border [&_.editor-number-step_>_span]:[width:0.5rem]',
    '[&_.editor-number-step_>_span]:[height:0.5rem]',
    '[&_.editor-number-step_>_span]:[border-right:0.125rem_solid_currentColor]',
    '[&_.editor-number-step_>_span]:[border-bottom:0.125rem_solid_currentColor]',
    '[&_.editor-number-step_>_span]:[font-size:0] [&_.editor-number-step_>_span]:pointer-events-none',
    '[&_.editor-number-step.decrement_>_span]:[transform:rotate(135deg)]',
    '[&_.editor-number-step.increment_>_span]:[transform:rotate(-45deg)]',
    '[&_footer]:[justify-content:flex-end]',
    '[&_footer_button]:[min-width:5.75rem] [&_footer_button]:[padding:0.5rem_0.75rem]',
    '[&_footer_button]:[border:0.0625rem_solid_#64e5c4] [&_footer_button]:[border-radius:0.4375rem]',
    '[&_footer_button]:[color:#07110f] [&_footer_button]:[background:#64e5c4]',
    '[&_footer_button]:[font-size:0.6875rem] [&_footer_button]:font-bold [&_footer_button]:cursor-pointer',
    '[&_footer_button.secondary]:[border-color:#3b4743] [&_footer_button.secondary]:[color:#b8c4bf]',
    '[&_footer_button.secondary]:[background:#171e1b]',
    '[&_footer_button:disabled]:[opacity:0.5] [&_footer_button:disabled]:cursor-not-allowed',
  ],
  'auto-mesh-dialog-overlay': [
    'fixed [inset:0] [background:rgb(3_7_6_/_72%)] [backdrop-filter:blur(0.1875rem)]',
    '[&[data-closed]]:hidden',
  ],
  'auto-mesh-error': [
    'm-0 [padding:0.625rem_0.75rem] [border:0.0625rem_solid_#8f4747] [border-radius:0.4375rem] [color:#ffd1d1]',
    '[background:#2a1616] [font-size:0.625rem] [line-height:1.6]',
  ],
  'auto-mesh-number-field': [
    "flex [gap:0.5rem] items-center [color:#7f8d88] [font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[font-size:0.625rem]',
    '[&_input]:w-full [&_input]:min-w-0 [&_input]:[padding:0.5rem_0.5625rem]',
    '[&_input]:[border:0.0625rem_solid_#3b4743] [&_input]:[border-radius:0.375rem] [&_input]:[color:#eef5f2]',
    '[&_input]:[background:#0d1210]',
  ],
  'auto-mesh-presets': [
    'grid [grid-template-columns:repeat(3,_minmax(0,_1fr))] [gap:0.5rem] m-0 p-0 [border:0]',
    '[&_legend]:[margin-bottom:0.5rem] [&_legend]:[color:#bec9c5] [&_legend]:[font-size:0.6875rem]',
    '[&_legend]:font-bold',
    '[&_label]:relative [&_label]:grid [&_label]:min-w-0 [&_label]:cursor-pointer',
    '[&_input]:fixed [&_input]:[inline-size:0.0625rem] [&_input]:[block-size:0.0625rem] [&_input]:[opacity:0]',
    '[&_label_>_span]:grid [&_label_>_span]:[min-height:5.5rem] [&_label_>_span]:[gap:0.3125rem]',
    '[&_label_>_span]:[align-content:start] [&_label_>_span]:[padding:0.6875rem]',
    '[&_label_>_span]:[border:0.0625rem_solid_#35413d] [&_label_>_span]:[border-radius:0.5rem]',
    '[&_label_>_span]:[background:#171e1b]',
    '[&_input:checked_+_span]:[border-color:#64e5c4] [&_input:checked_+_span]:[background:#192722]',
    '[&_input:checked_+_span]:[box-shadow:inset_0_0_0_0.0625rem_#64e5c4]',
    '[&_input:focus-visible_+_span]:[outline:0.125rem_solid_#64e5c4]',
    '[&_input:focus-visible_+_span]:[outline-offset:0.125rem]',
    '[&_strong]:[color:#e6efeb] [&_strong]:[font-size:0.6875rem]',
    '[&_small]:[color:#7f8d88] [&_small]:[font-size:0.5625rem] [&_small]:[line-height:1.5]',
    '[@media(max-width:35rem)]:[grid-template-columns:1fr]',
    '[@media(max-width:35rem)]:[&_label_>_span]:min-h-0',
  ],
  'auto-mesh-settings': [
    'grid [grid-template-columns:repeat(2,_minmax(0,_1fr))] [gap:1rem]',
    '[&_>_label]:grid [&_>_label]:[gap:0.4375rem] [&_>_label]:[color:#bdc8c4] [&_>_label]:[font-size:0.6875rem]',
    '[&_>_label]:font-bold',
    '[&_label_>_small]:[color:#75827d] [&_label_>_small]:[font-size:0.5625rem]',
    '[&_label_>_small]:[font-weight:400] [&_label_>_small]:[line-height:1.5]',
    '[@media(max-width:35rem)]:[grid-template-columns:1fr]',
  ],
  'auto-mesh-warning': [
    'm-0 [padding:0.625rem_0.75rem] [border-left:0.1875rem_solid_#e5b55a] [color:#c7b889] [background:#211d13]',
    '[font-size:0.625rem] [line-height:1.6]',
  ],
  'editor-context-menu-content': [
    '[min-width:11.25rem] [padding:0.3125rem] [border:0.0625rem_solid_#35413d] [border-radius:0.4375rem]',
    '[outline:none] [color:#dbe5e1] [background:#121816] [box-shadow:0_0.625rem_1.75rem_rgb(0_0_0_/_36%)]',
    '[&[data-closed]]:hidden',
  ],
  'editor-context-menu-item': [
    'flex [min-height:1.875rem] [gap:1.125rem] items-center [padding:0.3125rem_0.5rem]',
    '[border-radius:0.3125rem] [outline:none] [font-size:0.625rem] cursor-default select-none',
    '[&[data-highlighted]]:[color:#effffb] [&[data-highlighted]]:[background:#28594c]',
    '[&.danger]:[color:#f3aaa5]',
    '[&.danger[data-highlighted]]:[color:#fff1ef] [&.danger[data-highlighted]]:[background:#873b37]',
    '[&[data-disabled]]:[opacity:0.42] [&[data-disabled]]:pointer-events-none',
    '[&[data-highlighted]_.editor-context-menu-shortcut]:[color:currentcolor]',
  ],
  'editor-context-menu-separator': [
    '[height:0.0625rem] [margin:0.25rem_0.375rem] [border:0] [background:#2d3834]',
  ],
  'editor-context-menu-shortcut': [
    "[margin-left:auto] [color:#788681] [font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[font-size:0.5625rem]',
  ],
  'editor-help': [
    'box-border [width:min(45.125rem,_calc(100vw_-_2rem))] [max-height:calc(100dvh_-_2rem)] [padding:1.5rem]',
    '[border:1px_solid_#35413d] [border-radius:0.75rem] [background:#111614] [color:#e9f3ef]',
    '[font-size:0.875rem] [line-height:1.7] overflow-y-auto',
    '[&::backdrop]:[background:#0009]',
    '[&_header]:flex [&_header]:items-center [&_header]:justify-between',
    '[&_h1]:[font-size:1.25rem] [&_h1]:m-0',
    '[&_h2]:[font-size:1rem] [&_h2]:[margin-top:1.5rem]',
    '[&_dt]:font-bold [&_dt]:[margin-top:0.75rem]',
    '[&_dd]:m-0 [&_dd]:[color:#b9c5c0]',
    '[&_header_button]:[padding:0.5rem_0.75rem] [&_header_button]:[border:1px_solid_#35413d]',
    '[&_header_button]:[border-radius:0.375rem] [&_header_button]:[color:#e9f3ef]',
    '[&_header_button]:[background:#26332f] [&_header_button]:cursor-pointer',
    '[&_button:focus-visible]:[outline:2px_solid_#64e5c4] [&_button:focus-visible]:[outline-offset:2px]',
  ],
}
