export const iconShortcuts = {
  'puppet-icon': 'inline-block align-middle shrink-0 [width:1em] [height:1em]',
  'puppet-icon-arrow-down': 'i-tabler-arrow-down',
  'puppet-icon-arrow-left': 'i-tabler-arrow-left',
  'puppet-icon-arrow-up': 'i-tabler-arrow-up',
  'puppet-icon-check': 'i-tabler-check',
  'puppet-icon-pin': 'i-tabler-pin',
  'puppet-icon-bone': 'i-tabler-bone',
  'puppet-icon-chevron-down': 'i-tabler-chevron-down',
  'puppet-icon-caret-right-filled': 'i-tabler-caret-right-filled',
  'puppet-icon-chevron-left': 'i-tabler-chevron-left',
  'puppet-icon-chevron-right': 'i-tabler-chevron-right',
  'puppet-icon-curve': 'i-tabler-vector-bezier',
  'puppet-icon-eye': 'i-tabler-eye',
  'puppet-icon-eye-off': 'i-tabler-eye-off',
  'puppet-icon-indent-decrease': 'i-tabler-indent-decrease',
  'puppet-icon-layers-intersect': 'i-tabler-layers-intersect',
  'puppet-icon-layout-bottombar': 'i-tabler-layout-bottombar',
  'puppet-icon-layout-sidebar': 'i-tabler-layout-sidebar',
  'puppet-icon-layout-sidebar-right': 'i-tabler-layout-sidebar-right',
  'puppet-icon-lock': 'i-tabler-lock',
  'puppet-icon-lock-open': 'i-tabler-lock-open',
  'puppet-icon-menu-2': 'i-tabler-menu-2',
  'puppet-icon-mesh': 'i-tabler-mesh',
  'puppet-icon-minus': 'i-tabler-minus',
  'puppet-icon-plus': 'i-tabler-plus',
  'puppet-icon-squares': 'i-tabler-squares',
  'puppet-icon-trash': 'i-tabler-trash',
  'puppet-icon-x': 'i-tabler-x',
}
