export const layersShortcuts = {
  'layer-label': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[gap:0.125rem]',
    '[.puppet-editor_&_strong]:overflow-hidden [.puppet-editor_&_strong]:[text-overflow:ellipsis]',
    '[.puppet-editor_&_strong]:whitespace-nowrap',
    '[.puppet-editor_&_small]:overflow-hidden [.puppet-editor_&_small]:[text-overflow:ellipsis]',
    '[.puppet-editor_&_small]:whitespace-nowrap',
    '[.puppet-editor_&_strong]:[font-size:0.6875rem]',
    '[.puppet-editor_&_small]:[color:#8f9d98] [.puppet-editor_&_small]:[font-size:0.5625rem]',
  ],
  'layer-row': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:grid',
    '[.puppet-editor_&]:[grid-template-columns:2.25rem_minmax(0,_1fr)_auto] [.puppet-editor_&]:[gap:0.25rem]',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:[padding-left:calc(var(--layer-depth)_*_0.875rem)]',
    '[.puppet-editor_&]:[border:0.0625rem_solid_transparent] [.puppet-editor_&]:[border-radius:0.4375rem]',
    '[.puppet-editor_&.drop-before::before]:absolute [.puppet-editor_&.drop-before::before]:[right:0.25rem]',
    '[.puppet-editor_&.drop-before::before]:[left:calc(var(--layer-depth)_*_0.875rem_+_0.25rem)]',
    '[.puppet-editor_&.drop-before::before]:[height:0.125rem]',
    '[.puppet-editor_&.drop-before::before]:[border-radius:62.4375rem]',
    '[.puppet-editor_&.drop-before::before]:[background:#e5b55a]',
    "[.puppet-editor_&.drop-before::before]:[content:'']",
    '[.puppet-editor_&.drop-after::after]:absolute [.puppet-editor_&.drop-after::after]:[right:0.25rem]',
    '[.puppet-editor_&.drop-after::after]:[left:calc(var(--layer-depth)_*_0.875rem_+_0.25rem)]',
    '[.puppet-editor_&.drop-after::after]:[height:0.125rem]',
    '[.puppet-editor_&.drop-after::after]:[border-radius:62.4375rem]',
    '[.puppet-editor_&.drop-after::after]:[background:#e5b55a]',
    "[.puppet-editor_&.drop-after::after]:[content:'']",
    '[.puppet-editor_&.drop-before::before]:[top:-0.1875rem]',
    '[.puppet-editor_&.drop-after::after]:[bottom:-0.1875rem]',
    '[.puppet-editor_&.drop-inside]:[border-color:#e5b55a] [.puppet-editor_&.drop-inside]:[background:#2b2618]',
  ],
  'layer-select': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[gap:0.5rem]',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:[padding:0.375rem_0.1875rem]',
    '[.puppet-editor_&]:[border:0] [.puppet-editor_&]:[color:#a7b3af]',
    '[.puppet-editor_&]:[background:transparent] [.puppet-editor_&]:cursor-pointer [.puppet-editor_&]:text-left',
    "[.puppet-editor_&[aria-pressed='true']]:[color:#f3f7f5]",
    '[.puppet-editor_&.mask-pick-candidate]:[border-radius:0.375rem]',
    '[.puppet-editor_&.mask-pick-candidate]:[color:#d7fff4]',
    '[.puppet-editor_&.mask-pick-candidate]:[background:#17352d]',
    '[.puppet-editor_&.mask-pick-candidate]:[box-shadow:inset_0_0_0_0.0625rem_#4fcaa9]',
    '[.puppet-editor_&:disabled]:[opacity:0.35] [.puppet-editor_&:disabled]:cursor-not-allowed',
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#61e3c1]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:0.0625rem]',
  ],
  'layer-thumbnail': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[width:2.375rem] [.puppet-editor_&]:[height:2.375rem]',
    '[.puppet-editor_&]:[flex:none] [.puppet-editor_&]:[border:0.0625rem_solid_#4c615a]',
    '[.puppet-editor_&]:[border-radius:0.375rem]',
    '[.puppet-editor_&]:editor-checkerboard',
    '[.puppet-editor_&]:[background-position:0_0,_0_0.5rem,_0.5rem_-0.5rem,_-0.5rem_0]',
    '[.puppet-editor_&]:[background-size:1rem_1rem] [.puppet-editor_&]:overflow-hidden',
    '[.puppet-editor_&]:place-items-center',
    '[.puppet-editor_&_img]:block [.puppet-editor_&_img]:w-full [.puppet-editor_&_img]:h-full',
    '[.puppet-editor_&_img]:[object-fit:contain]',
  ],
  'layer-toolbar': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:flex-wrap [.puppet-editor_&]:[gap:0.3125rem]',
    '[.puppet-editor_&]:[margin-bottom:0.625rem]',
    '[.puppet-editor_&_button]:[min-height:1.625rem] [.puppet-editor_&_button]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_button]:[border-radius:0.3125rem] [.puppet-editor_&_button]:[color:#a7b3af]',
    '[.puppet-editor_&_button]:[background:#171e1b] [.puppet-editor_&_button]:[font-size:0.625rem]',
    '[.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button]:[padding:0.25rem_0.4375rem]',
    '[.puppet-editor_&_button:disabled]:[opacity:0.38] [.puppet-editor_&_button:disabled]:cursor-not-allowed',
    '[.puppet-editor_&_button:focus-visible]:[outline:0.125rem_solid_#61e3c1]',
    '[.puppet-editor_&_button:focus-visible]:[outline-offset:0.0625rem]',
  ],
  'layer-tree': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[gap:0.25rem] [.puppet-editor_&]:m-0 [.puppet-editor_&]:p-0',
    '[.puppet-editor_&]:[list-style:none]',
    '[.puppet-editor_&_ul]:grid [.puppet-editor_&_ul]:[gap:0.25rem] [.puppet-editor_&_ul]:m-0',
    '[.puppet-editor_&_ul]:p-0 [.puppet-editor_&_ul]:[list-style:none]',
    '[.puppet-editor_&.root-drop-active]:[box-shadow:inset_0_-0.125rem_0_#e5b55a]',
  ],
  'layers-panel': [
    '[.puppet-editor_&]:[grid-area:layers] [.puppet-editor_&]:[border-right:0.0625rem_solid_#27302d]',
  ],
  'puppet-layer-container-icon': [
    '[.puppet-editor_&]:[width:2.375rem] [.puppet-editor_&]:[height:1.875rem] [.puppet-editor_&]:[flex:none]',
    '[.puppet-editor_&]:fill-none [.puppet-editor_&]:stroke-cap-round',
    '[.puppet-editor_&]:[stroke-linejoin:round] [.puppet-editor_&]:[stroke-width:0.10625rem]',
    '[.puppet-editor_&.group]:[color:#e5b55a] [.puppet-editor_&.group]:[stroke:currentcolor]',
    '[.puppet-editor_&.group_rect:last-child]:[fill:#2b2618]',
    '[.puppet-editor_&.deformer]:[color:#76d8c0] [.puppet-editor_&.deformer]:[stroke:currentcolor]',
    '[.puppet-editor_&.deformer_circle]:[fill:#171e1b]',
  ],
  'puppet-layer-name-editor': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&]:[grid-template-columns:2.375rem_minmax(0,_1fr)] [.puppet-editor_&]:[gap:0.5rem]',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:[padding:0.375rem_0.1875rem]',
    '[.puppet-editor_&_input]:min-w-0 [.puppet-editor_&_input]:[padding:0.3125rem_0.4375rem]',
    '[.puppet-editor_&_input]:[border:0.0625rem_solid_#64e5c4]',
    '[.puppet-editor_&_input]:[border-radius:0.3125rem] [.puppet-editor_&_input]:[color:#e5eeea]',
    '[.puppet-editor_&_input]:[background:#171e1b] [.puppet-editor_&_input]:[font-size:0.6875rem]',
    '[.puppet-editor_&_input:focus-visible]:[outline:0.125rem_solid_#61e3c1]',
    '[.puppet-editor_&_input:focus-visible]:[outline-offset:0.0625rem]',
  ],
  'puppet-layer-state-actions': [
    '[.puppet-editor_&_button]:[min-height:1.625rem] [.puppet-editor_&_button]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_button]:[border-radius:0.3125rem] [.puppet-editor_&_button]:[color:#a7b3af]',
    '[.puppet-editor_&_button]:[background:#171e1b] [.puppet-editor_&_button]:[font-size:0.625rem]',
    '[.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button:disabled]:[opacity:0.38] [.puppet-editor_&_button:disabled]:cursor-not-allowed',
    '[.puppet-editor_&]:flex [.puppet-editor_&]:[gap:0.125rem] [.puppet-editor_&]:[padding-right:0.25rem]',
    '[.puppet-editor_&_button]:[width:1.5rem] [.puppet-editor_&_button]:p-0',
    '[.puppet-editor_&_button]:[border-color:transparent] [.puppet-editor_&_button]:[background:transparent]',
    '[.puppet-editor_&_button:focus-visible]:[outline:0.125rem_solid_#61e3c1]',
    '[.puppet-editor_&_button:focus-visible]:[outline-offset:0.0625rem]',
  ],
  'puppet-layer-toolbar-icon': [
    '[.puppet-editor_&]:block [.puppet-editor_&]:[width:0.875rem] [.puppet-editor_&]:[height:0.875rem]',
    '[.puppet-editor_&]:fill-none [.puppet-editor_&]:[stroke:currentColor] [.puppet-editor_&]:stroke-cap-round',
    '[.puppet-editor_&]:[stroke-linejoin:round] [.puppet-editor_&]:[stroke-width:0.09375rem]',
  ],
  'puppet-layer-tree-item': [
    "[.puppet-editor_&[aria-selected='true']_>_.layer-tree-node_>_.layer-row]:[border-color:#64e5c4]",
    "[.puppet-editor_&[aria-selected='true']_>_.layer-tree-node_>_.layer-row]:[background:#1a2925]",
    "[.puppet-editor_&[aria-selected='true']_>_.layer-tree-node_>_.layer-row]:[box-shadow:inset_0.1875rem_0_0_#64e5c4]",
    '[.puppet-editor_&.dragging_>_.layer-tree-node_>_.layer-row]:[opacity:0.5]',
  ],
  'puppet-layer-tree-spacer': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[width:2.25rem] [.puppet-editor_&]:[height:2.25rem]',
    '[.puppet-editor_&]:p-0 [.puppet-editor_&]:place-items-center',
  ],
  'puppet-layer-tree-toggle': [
    '[.puppet-editor_&]:[min-height:1.625rem] [.puppet-editor_&]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&]:[border-radius:0.3125rem] [.puppet-editor_&]:[color:#a7b3af]',
    '[.puppet-editor_&]:[background:#171e1b] [.puppet-editor_&]:[font-size:0.625rem]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[width:2.25rem] [.puppet-editor_&]:[height:2.25rem]',
    '[.puppet-editor_&]:p-0 [.puppet-editor_&]:place-items-center',
    '[.puppet-editor_&]:[border-color:transparent] [.puppet-editor_&]:[background:transparent]',
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#61e3c1]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:0.0625rem]',
  ],
  'puppet-layer-tree-toggle-icon': [
    '[.puppet-editor_&]:[width:1.25rem] [.puppet-editor_&]:[height:1.25rem]',
    '[.puppet-editor_&]:[fill:currentcolor] [.puppet-editor_&]:[transform-origin:center]',
    '[.puppet-editor_&.expanded]:[transform:rotate(90deg)]',
  ],
}
