export const layoutShortcuts = {
  'grid-curve-button': [
    '[.puppet-editor_&]:[min-height:1.625rem] [.puppet-editor_&]:p-editor-related',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#53655f] [.puppet-editor_&]:[border-radius:0.3125rem]',
    '[.puppet-editor_&]:[color:#bfeee1] [.puppet-editor_&]:[background:#17211e]',
    '[.puppet-editor_&]:text-editor-metadata [.puppet-editor_&]:whitespace-nowrap',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&:disabled]:[opacity:0.42] [.puppet-editor_&:disabled]:cursor-not-allowed',
  ],
  'grid-point-row': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[grid-template-columns:3.375rem_minmax(0,_1fr)]',
    '[.puppet-editor_&]:gap-editor-field [.puppet-editor_&]:items-center [.puppet-editor_&]:[color:#84918c]',
    '[.puppet-editor_&]:text-editor-metadata',
    '[.puppet-editor_&]:[grid-template-columns:minmax(0,_1fr)_minmax(0,_1fr)_auto]',
  ],
  'grid-resolution': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[grid-template-columns:minmax(0,_1fr)]',
    '[.puppet-editor_&]:gap-editor-field',
    '[.puppet-editor_&_label]:[grid-template-columns:3.375rem_minmax(5.625rem,_1fr)]',
  ],
  'modeling-panel': [
    '[.puppet-editor_&]:[grid-area:timeline] [.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&]:min-h-0 [.puppet-editor_&]:[border-top:0.0625rem_solid_#27302d]',
    '[.puppet-editor_&]:[background:#111614]',
  ],
  notice: [
    '[.puppet-editor_&]:[color:#788681] [.puppet-editor_&]:text-editor-caption',
    '[.puppet-editor_&]:my-editor-section [.puppet-editor_&]:mx-editor-field [.puppet-editor_&]:[line-height:1.6]',
  ],
  panel: [
    '[.puppet-editor_&]:min-h-0 [.puppet-editor_&]:p-editor-group',
    '[.puppet-editor_&]:[background:#101513]',
  ],
  'panel-add-button': [
    '[.puppet-editor_&]:inline-flex [.puppet-editor_&]:w-auto [.puppet-editor_&]:shrink-0',
    '[.puppet-editor_&]:py-0 [.puppet-editor_&]:px-editor-field [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:justify-center',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#3d5f56] [.puppet-editor_&]:[border-radius:0.375rem]',
    '[.puppet-editor_&]:[color:#bfeee1] [.puppet-editor_&]:[background:#17211e]',
    '[.puppet-editor_&]:cursor-pointer',
  ],
  'panel-heading': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:justify-between',
    '[.puppet-editor_&]:[min-height:2.125rem] [.puppet-editor_&]:mb-editor-group',
    '[.puppet-editor_&_h2]:m-0 [.puppet-editor_&_h2]:[color:#a7b3af]',
    '[.puppet-editor_&_h2]:editor-type-section [.puppet-editor_&_h2]:[letter-spacing:0.12rem]',
    '[.puppet-editor_&_h2]:[text-transform:uppercase]',
    '[.puppet-editor_&_>_span]:grid [.puppet-editor_&_>_span]:[min-width:1.375rem]',
    '[.puppet-editor_&_>_span]:[height:1.375rem] [.puppet-editor_&_>_span]:place-items-center',
    '[.puppet-editor_&_>_span]:[border:0.0625rem_solid_#313b37]',
    '[.puppet-editor_&_>_span]:[border-radius:0.375rem] [.puppet-editor_&_>_span]:[color:#84918c]',
    '[.puppet-editor_&_>_span]:text-editor-caption',
  ],
  'panel-note': [
    '[.puppet-editor_&]:[color:#788681] [.puppet-editor_&]:text-editor-caption',
    '[.puppet-editor_&]:my-editor-section [.puppet-editor_&]:mx-editor-field [.puppet-editor_&]:[line-height:1.6]',
  ],
  'panel-resizer': [
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:min-h-0 [.puppet-editor_&]:[background:#27302d]',
    '[.puppet-editor_&]:touch-none',
    '[.puppet-editor_&:hover]:[outline:none] [.puppet-editor_&:hover]:[background:#64e5c4]',
    '[.puppet-editor_&.dragging]:[outline:none] [.puppet-editor_&.dragging]:[background:#64e5c4]',
    '[.puppet-editor_&:focus-visible]:[outline:none] [.puppet-editor_&:focus-visible]:[background:#64e5c4]',
    '[.puppet-editor_&.left]:[grid-area:left-resizer] [.puppet-editor_&.left]:[cursor:col-resize]',
    '[.puppet-editor_&.right]:[grid-area:right-resizer] [.puppet-editor_&.right]:[cursor:col-resize]',
    '[.puppet-editor_&.bottom]:[grid-area:bottom-resizer] [.puppet-editor_&.bottom]:[cursor:row-resize]',
  ],
  'panel-visibility-controls': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:gap-editor-related [.puppet-editor_&]:pl-editor-field',
    '[.puppet-editor_&]:[border-left:0.0625rem_solid_#313b37]',
    '[.puppet-editor_&_button]:grid [.puppet-editor_&_button]:[width:1.75rem]',
    '[.puppet-editor_&_button]:[height:1.75rem] [.puppet-editor_&_button]:p-0',
    '[.puppet-editor_&_button]:place-items-center [.puppet-editor_&_button]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_button]:[border-radius:0.375rem] [.puppet-editor_&_button]:[color:#788681]',
    '[.puppet-editor_&_button]:[background:#121816] [.puppet-editor_&_button]:cursor-pointer',
    "[.puppet-editor_&_button[aria-pressed='true']]:[border-color:#4b756a]",
    "[.puppet-editor_&_button[aria-pressed='true']]:[color:#bfeee1]",
    "[.puppet-editor_&_button[aria-pressed='true']]:[background:#1a2925]",
    '[.puppet-editor_&_button:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&_button:focus-visible]:[outline-offset:0.125rem]',
    '[.puppet-editor_&_.puppet-icon]:[width:1rem] [.puppet-editor_&_.puppet-icon]:[height:1rem]',
  ],
  'puppet-editor': [
    'editor-type-root',
    '[container-type:inline-size]',
    '[--editor-control-height:1.40625rem]',
    '[--bottom-grid-size:var(--bottom-panel-size,_16.25rem)] [--bottom-resizer-size:0.375rem]',
    '[--left-grid-size:var(--left-panel-size,_18.75rem)] [--left-resizer-size:0.375rem]',
    '[--right-grid-size:var(--right-panel-size,_16.25rem)] [--right-resizer-size:0.375rem] grid',
    'editor-workspace-grid',
    'w-full min-w-0 h-full [min-height:40rem] overflow-hidden [color:#edf4f0] [background:#0b0f0e]',
    '[&.left-panel-closed]:[--left-grid-size:0rem] [&.left-panel-closed]:[--left-resizer-size:0rem]',
    '[&.right-panel-closed]:[--right-grid-size:0rem] [&.right-panel-closed]:[--right-resizer-size:0rem]',
    '[&.bottom-panel-closed]:[--bottom-grid-size:0rem] [&.bottom-panel-closed]:[--bottom-resizer-size:0rem]',
    '[&.left-panel-closed_.layers-panel]:hidden',
    '[&.right-panel-closed_.inspector-panel]:hidden',
    '[&.bottom-panel-closed_.modeling-panel]:hidden',
    '[&.bottom-panel-closed_.timeline]:hidden',
    '[&.bottom-panel-closed_.keyform-panel]:hidden',
    '[&.left-panel-closed_.panel-resizer.left]:hidden',
    '[&.right-panel-closed_.panel-resizer.right]:hidden',
    '[&.bottom-panel-closed_.panel-resizer.bottom]:hidden',
    'box-border',
    '[&_*]:box-border',
    '[&_button]:[color:inherit]',
  ],
  'puppet-selection-actions': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:flex-wrap [.puppet-editor_&]:gap-editor-control',
    '[.puppet-editor_&_button]:[min-height:1.625rem] [.puppet-editor_&_button]:py-editor-related',
    '[.puppet-editor_&_button]:px-editor-field',
    '[.puppet-editor_&_button]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_button]:[border-radius:0.4375rem] [.puppet-editor_&_button]:[color:#b5c5bf]',
    '[.puppet-editor_&_button]:[background:#17211e] [.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button]:text-left [.puppet-editor_&_button]:editor-type-control',
    '[.puppet-editor_&_button]:[line-height:1rem] [.puppet-editor_&_button]:max-w-full',
    '[.puppet-editor_&_button:hover:not(:disabled)]:[border-color:#64e5c4]',
    '[.puppet-editor_&_button:hover:not(:disabled)]:[outline:none]',
    '[.puppet-editor_&_button:focus-visible]:[border-color:#64e5c4]',
    '[.puppet-editor_&_button:focus-visible]:[outline:none]',
    '[.puppet-editor_&_button:disabled]:[opacity:0.45] [.puppet-editor_&_button:disabled]:cursor-not-allowed',
  ],
  'renderer-status': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:gap-editor-field [.puppet-editor_&]:ml-editor-related',
    '[.puppet-editor_&]:[color:#a7b3af] [.puppet-editor_&]:text-editor-reading',
    "[.puppet-editor_&[data-status='ready']_.status-dot]:[background:#64e5c4]",
    "[.puppet-editor_&[data-status='ready']_.status-dot]:[box-shadow:0_0_0_0.25rem_rgb(100_229_196_/_10%)]",
    "[.puppet-editor_&[data-status='error']_.status-dot]:[background:#ff7a76]",
    "[.puppet-editor_&[data-status='error']_.status-dot]:[box-shadow:0_0_0_0.25rem_rgb(255_122_118_/_10%)]",
    '[@media(max-width:67.5rem)]:[.puppet-editor_&]:hidden',
  ],
  'status-dot': [
    '[.puppet-editor_&]:[width:0.4375rem] [.puppet-editor_&]:[height:0.4375rem]',
    '[.puppet-editor_&]:[border-radius:62.4375rem] [.puppet-editor_&]:[background:#e5b55a]',
    '[.puppet-editor_&]:[box-shadow:0_0_0_0.25rem_rgb(229_181_90_/_10%)]',
  ],
  toolbar: [
    '[.puppet-editor_&]:[grid-area:toolbar] [.puppet-editor_&]:flex [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:justify-between [.puppet-editor_&]:py-0 [.puppet-editor_&]:px-editor-group',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d] [.puppet-editor_&]:[background:#111614]',
  ],
  'toolbar-actions': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:gap-editor-field',
    '[.puppet-editor_&]:shrink-0 [.puppet-editor_&]:ml-editor-group',
    '[@media(max-width:67.5rem)]:[.puppet-editor_&]:gap-editor-control',
  ],
  'toolbar-brush-settings-mount': [
    'editor-scrollbar-compact',
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:flex-1',
    '[.puppet-editor_&]:ml-editor-group [.puppet-editor_&]:overflow-x-auto',
    '[.puppet-editor_&]:py-editor-field',
  ],
  'toolbar-button': [
    '[.puppet-editor_&]:p-editor-field [.puppet-editor_&]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&]:[border-radius:0.4375rem] [.puppet-editor_&]:[color:#b9c5c0]',
    '[.puppet-editor_&]:[background:#171e1b] [.puppet-editor_&]:text-editor-body',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&.primary]:[border-color:#64e5c4] [.puppet-editor_&.primary]:[color:#07110f]',
    '[.puppet-editor_&.primary]:[background:#64e5c4] [.puppet-editor_&.primary]:font-bold',
    '[.puppet-editor_&:disabled]:[opacity:0.42] [.puppet-editor_&:disabled]:cursor-not-allowed',
    '[.puppet-editor_&_input]:fixed [.puppet-editor_&_input]:[inline-size:0.0625rem]',
    '[.puppet-editor_&_input]:[block-size:0.0625rem] [.puppet-editor_&_input]:[opacity:0]',
    '[.puppet-editor_&_input]:pointer-events-none',
  ],
  'toolbar-menu': ['[.puppet-editor_&]:[anchor-scope:\\-\\-toolbar-menu]'],
  'toolbar-menu-content': [
    'editor-type-root',
    '[&_button.file-menu-action]:[display:flex] [&_button.file-menu-action]:[flex-direction:column]',
    '[&_button.file-menu-action]:[align-items:flex-start] [&_button.file-menu-action]:gap-editor-related',
    '[&_button.file-menu-action_small]:text-editor-body [&_button.file-menu-action_small]:[color:#b9c9c3]',
    'grid m-0 min-w-44 p-editor-control rounded-lg border border-solid border-[#35413d] bg-[#171e1b] text-[#e9f3ef]',
    'shadow-[0_8px_24px_#0006] [&[data-closed]]:hidden',
    '[&_button]:py-editor-field [&_button]:px-editor-group [&_button]:[border:0]',
    '[&_button]:[border-radius:0.3125rem] [&_button]:[background:transparent]',
    '[&_button]:[color:inherit] [&_button]:text-left',
    '[&_button]:text-editor-reading [&_button]:cursor-pointer',
    '[&_button:hover]:[background:#26332f]',
    '[&_button:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[&_button:focus-visible]:[outline-offset:0.125rem]',
    '[&_hr]:w-full [&_hr]:my-editor-related [&_hr]:mx-0 [&_hr]:[border:0]',
    '[&_hr]:[border-top:0.0625rem_solid_#35413d]',
    '[&_button:disabled]:[opacity:0.42] [&_button:disabled]:cursor-not-allowed',
    '[&_button:disabled]:[background:transparent]',
  ],
  'toolbar-menu-examples-trigger': [
    'cursor-pointer rounded px-editor-group py-editor-field text-editor-body',
    'hover:bg-[#26332f] focus-visible:outline-2 focus-visible:outline-[#64e5c4]',
  ],
  'toolbar-menu-trigger': [
    '[.puppet-editor_&]:[anchor-name:\\-\\-toolbar-menu] [.puppet-editor_&]:grid',
    '[.puppet-editor_&]:place-items-center [.puppet-editor_&]:[width:2rem] [.puppet-editor_&]:[height:2rem]',
    '[.puppet-editor_&]:p-editor-control [.puppet-editor_&]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&]:[border-radius:0.4375rem] [.puppet-editor_&]:[background:#171e1b]',
    '[.puppet-editor_&]:[color:#b9c5c0] [.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&_.puppet-icon]:w-full [.puppet-editor_&_.puppet-icon]:h-full ',
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:0.125rem]',
  ],
  'visually-hidden': [
    '[.puppet-editor_&]:fixed [.puppet-editor_&]:[inline-size:0.0625rem]',
    '[.puppet-editor_&]:[block-size:0.0625rem] [.puppet-editor_&]:overflow-hidden',
    '[.puppet-editor_&]:[clip-path:inset(50%)] [.puppet-editor_&]:whitespace-nowrap',
  ],
  'workspace-switcher': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:gap-editor-related [.puppet-editor_&]:p-editor-related',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#313b37] [.puppet-editor_&]:[border-radius:0.5rem]',
    '[.puppet-editor_&]:[background:#0d1210]',
    '[.puppet-editor_&_button]:py-editor-control [.puppet-editor_&_button]:px-editor-group',
    '[.puppet-editor_&_button]:[border:0]',
    '[.puppet-editor_&_button]:[border-radius:0.3125rem] [.puppet-editor_&_button]:[color:#7f8d88]',
    '[.puppet-editor_&_button]:[background:transparent] [.puppet-editor_&_button]:text-editor-body',
    '[.puppet-editor_&_button]:cursor-pointer',
    "[.puppet-editor_&_button[aria-pressed='true']]:[color:#e9f3ef]",
    "[.puppet-editor_&_button[aria-pressed='true']]:[background:#26332f]",
    '[.puppet-editor_&_button:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&_button:focus-visible]:[outline-offset:0.125rem]',
  ],
}
