export const layoutShortcuts = {
  'grid-curve-button': [
    '[.puppet-editor_&]:[min-height:1.625rem] [.puppet-editor_&]:[padding:0.1875rem_0.3125rem]',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#53655f] [.puppet-editor_&]:[border-radius:0.3125rem]',
    '[.puppet-editor_&]:[color:#bfeee1] [.puppet-editor_&]:[background:#17211e]',
    '[.puppet-editor_&]:[font-size:0.5625rem] [.puppet-editor_&]:whitespace-nowrap',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&:disabled]:[opacity:0.42] [.puppet-editor_&:disabled]:cursor-not-allowed',
  ],
  'grid-point-row': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[grid-template-columns:3.375rem_minmax(0,_1fr)]',
    '[.puppet-editor_&]:[gap:0.4375rem] [.puppet-editor_&]:items-center [.puppet-editor_&]:[color:#84918c]',
    '[.puppet-editor_&]:[font-size:0.5625rem]',
    '[.puppet-editor_&]:[grid-template-columns:minmax(0,_1fr)_minmax(0,_1fr)_auto]',
  ],
  'grid-resolution': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[grid-template-columns:minmax(0,_1fr)]',
    '[.puppet-editor_&]:[gap:0.5rem]',
    '[.puppet-editor_&_label]:[grid-template-columns:3.375rem_minmax(5.625rem,_1fr)]',
  ],
  'history-controls': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:[gap:0.1875rem]',
    '[.puppet-editor_&_button]:[padding:0.375rem_0.5rem]',
    '[.puppet-editor_&_button]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_button]:[border-radius:0.375rem] [.puppet-editor_&_button]:[color:#b9c5c0]',
    '[.puppet-editor_&_button]:[background:#121816] [.puppet-editor_&_button]:[font-size:0.625rem]',
    '[.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button:disabled]:[opacity:0.42] [.puppet-editor_&_button:disabled]:cursor-not-allowed',
    '[.puppet-editor_&_button:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&_button:focus-visible]:[outline-offset:0.125rem]',
  ],
  'modeling-panel': [
    '[.puppet-editor_&]:[grid-area:timeline] [.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&]:min-h-0 [.puppet-editor_&]:[border-top:0.0625rem_solid_#27302d]',
    '[.puppet-editor_&]:[background:#111614]',
  ],
  notice: [
    '[.puppet-editor_&]:[color:#788681] [.puppet-editor_&]:[font-size:0.625rem]',
    '[.puppet-editor_&]:[margin:1rem_0.5rem] [.puppet-editor_&]:[line-height:1.6]',
  ],
  panel: [
    '[.puppet-editor_&]:min-h-0 [.puppet-editor_&]:[padding:1rem_0.875rem]',
    '[.puppet-editor_&]:[background:#101513]',
  ],
  'panel-add-button': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[width:1.625rem] [.puppet-editor_&]:[height:1.625rem]',
    '[.puppet-editor_&]:p-0 [.puppet-editor_&]:place-items-center',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#3d5f56] [.puppet-editor_&]:[border-radius:0.375rem]',
    '[.puppet-editor_&]:[color:#bfeee1] [.puppet-editor_&]:[background:#17211e]',
    '[.puppet-editor_&]:cursor-pointer',
  ],
  'panel-heading': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:justify-between',
    '[.puppet-editor_&]:[min-height:2.125rem] [.puppet-editor_&]:[margin-bottom:0.75rem]',
    '[.puppet-editor_&_h2]:m-0 [.puppet-editor_&_h2]:[color:#a7b3af]',
    '[.puppet-editor_&_h2]:[font-size:0.6875rem] [.puppet-editor_&_h2]:[letter-spacing:0.12rem]',
    '[.puppet-editor_&_h2]:[text-transform:uppercase]',
    '[.puppet-editor_&_>_span]:grid [.puppet-editor_&_>_span]:[min-width:1.375rem]',
    '[.puppet-editor_&_>_span]:[height:1.375rem] [.puppet-editor_&_>_span]:place-items-center',
    '[.puppet-editor_&_>_span]:[border:0.0625rem_solid_#313b37]',
    '[.puppet-editor_&_>_span]:[border-radius:0.375rem] [.puppet-editor_&_>_span]:[color:#84918c]',
    '[.puppet-editor_&_>_span]:[font-size:0.625rem]',
  ],
  'panel-note': [
    '[.puppet-editor_&]:[color:#788681] [.puppet-editor_&]:[font-size:0.625rem]',
    '[.puppet-editor_&]:[margin:1rem_0.5rem] [.puppet-editor_&]:[line-height:1.6]',
  ],
  'panel-resizer': [
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:min-h-0 [.puppet-editor_&]:[background:#27302d]',
    '[.puppet-editor_&]:touch-none',
    '[.puppet-editor_&:hover]:[outline:none] [.puppet-editor_&:hover]:[background:#64e5c4]',
    '[.puppet-editor_&.dragging]:[outline:none] [.puppet-editor_&.dragging]:[background:#64e5c4]',
    '[.puppet-editor_&:focus-visible]:[outline:none] [.puppet-editor_&:focus-visible]:[background:#64e5c4]',
    '[.puppet-editor_&.left]:[grid-area:left-resizer] [.puppet-editor_&.left]:[cursor:col-resize]',
    '[.puppet-editor_&.right]:[grid-area:right-resizer] [.puppet-editor_&.right]:[cursor:col-resize]',
    '[.puppet-editor_&.bottom]:[grid-area:bottom-resizer] [.puppet-editor_&.bottom]:[cursor:row-resize]',
  ],
  'panel-visibility-controls': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:[gap:0.1875rem] [.puppet-editor_&]:[padding-left:0.5rem]',
    '[.puppet-editor_&]:[border-left:0.0625rem_solid_#313b37]',
    '[.puppet-editor_&_button]:grid [.puppet-editor_&_button]:[width:1.75rem]',
    '[.puppet-editor_&_button]:[height:1.75rem] [.puppet-editor_&_button]:p-0',
    '[.puppet-editor_&_button]:place-items-center [.puppet-editor_&_button]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_button]:[border-radius:0.375rem] [.puppet-editor_&_button]:[color:#788681]',
    '[.puppet-editor_&_button]:[background:#121816] [.puppet-editor_&_button]:cursor-pointer',
    "[.puppet-editor_&_button[aria-pressed='true']]:[border-color:#4b756a]",
    "[.puppet-editor_&_button[aria-pressed='true']]:[color:#bfeee1]",
    "[.puppet-editor_&_button[aria-pressed='true']]:[background:#1a2925]",
    '[.puppet-editor_&_button:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&_button:focus-visible]:[outline-offset:0.125rem]',
    '[.puppet-editor_&_svg]:[width:1rem] [.puppet-editor_&_svg]:[height:1rem] [.puppet-editor_&_svg]:fill-none',
    '[.puppet-editor_&_svg]:[stroke:currentcolor] [.puppet-editor_&_svg]:stroke-cap-round',
    '[.puppet-editor_&_svg]:[stroke-linejoin:round] [.puppet-editor_&_svg]:[stroke-width:0.078125rem]',
  ],
  'puppet-editor': [
    '[--bottom-grid-size:var(--bottom-panel-size,_16.25rem)] [--bottom-resizer-size:0.375rem]',
    '[--left-grid-size:var(--left-panel-size,_18.75rem)] [--left-resizer-size:0.375rem]',
    '[--right-grid-size:var(--right-panel-size,_16.25rem)] [--right-resizer-size:0.375rem] grid',
    'editor-workspace-grid',
    'w-full [min-width:51.25rem] h-full [min-height:40rem] overflow-hidden [color:#edf4f0] [background:#0b0f0e]',
    "[font-family:Inter,_ui-sans-serif,_system-ui,_-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_sans-serif]",
    '[font-synthesis:none] [text-rendering:optimizeLegibility]',
    '[&.left-panel-closed]:[--left-grid-size:0rem] [&.left-panel-closed]:[--left-resizer-size:0rem]',
    '[&.right-panel-closed]:[--right-grid-size:0rem] [&.right-panel-closed]:[--right-resizer-size:0rem]',
    '[&.bottom-panel-closed]:[--bottom-grid-size:0rem] [&.bottom-panel-closed]:[--bottom-resizer-size:0rem]',
    '[&.left-panel-closed_.layers-panel]:hidden',
    '[&.right-panel-closed_.inspector-panel]:hidden',
    '[&.bottom-panel-closed_.modeling-panel]:hidden',
    '[&.bottom-panel-closed_.timeline]:hidden',
    '[&.bottom-panel-closed_.keyform-panel]:hidden',
    '[&.left-panel-closed_.panel-resizer.left]:hidden',
    '[&.right-panel-closed_.panel-resizer.right]:hidden',
    '[&.bottom-panel-closed_.panel-resizer.bottom]:hidden',
    'box-border',
    '[&_*]:box-border',
    '[&_button]:[font:inherit]',
    '[&_input]:[font:inherit]',
    '[&_button]:[color:inherit]',
  ],
  'puppet-selection-actions': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[gap:0.5rem]',
    '[.puppet-editor_&_button]:[min-height:2.125rem] [.puppet-editor_&_button]:[padding:0.4375rem_0.625rem]',
    '[.puppet-editor_&_button]:[border:0.0625rem_solid_#3d5f56]',
    '[.puppet-editor_&_button]:[border-radius:0.4375rem] [.puppet-editor_&_button]:[color:#bfeee1]',
    '[.puppet-editor_&_button]:[background:#17211e] [.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button]:text-left',
    '[.puppet-editor_&_button:hover:not(:disabled)]:[border-color:#64e5c4]',
    '[.puppet-editor_&_button:hover:not(:disabled)]:[outline:none]',
    '[.puppet-editor_&_button:focus-visible]:[border-color:#64e5c4]',
    '[.puppet-editor_&_button:focus-visible]:[outline:none]',
    '[.puppet-editor_&_button:disabled]:[opacity:0.45] [.puppet-editor_&_button:disabled]:cursor-not-allowed',
  ],
  'renderer-status': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:[gap:0.5rem] [.puppet-editor_&]:[margin-left:0.25rem]',
    '[.puppet-editor_&]:[color:#a7b3af] [.puppet-editor_&]:[font-size:0.75rem]',
    "[.puppet-editor_&[data-status='ready']_.status-dot]:[background:#64e5c4]",
    "[.puppet-editor_&[data-status='ready']_.status-dot]:[box-shadow:0_0_0_0.25rem_rgb(100_229_196_/_10%)]",
    "[.puppet-editor_&[data-status='error']_.status-dot]:[background:#ff7a76]",
    "[.puppet-editor_&[data-status='error']_.status-dot]:[box-shadow:0_0_0_0.25rem_rgb(255_122_118_/_10%)]",
    '[@media(max-width:67.5rem)]:[.puppet-editor_&]:hidden',
  ],
  'status-dot': [
    '[.puppet-editor_&]:[width:0.4375rem] [.puppet-editor_&]:[height:0.4375rem]',
    '[.puppet-editor_&]:[border-radius:62.4375rem] [.puppet-editor_&]:[background:#e5b55a]',
    '[.puppet-editor_&]:[box-shadow:0_0_0_0.25rem_rgb(229_181_90_/_10%)]',
  ],
  toolbar: [
    '[.puppet-editor_&]:[grid-area:toolbar] [.puppet-editor_&]:flex [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:justify-between [.puppet-editor_&]:[padding:0_1.25rem]',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d] [.puppet-editor_&]:[background:#111614]',
    '[@media(max-width:67.5rem)]:[.puppet-editor_&]:[padding:0_0.75rem]',
  ],
  'toolbar-actions': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:[gap:0.625rem]',
    '[.puppet-editor_&]:shrink-0 [.puppet-editor_&]:[margin-left:0.75rem]',
    '[@media(max-width:67.5rem)]:[.puppet-editor_&]:[gap:0.375rem]',
  ],
  'toolbar-button': [
    '[.puppet-editor_&]:[padding:0.4375rem_0.625rem] [.puppet-editor_&]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&]:[border-radius:0.4375rem] [.puppet-editor_&]:[color:#b9c5c0]',
    '[.puppet-editor_&]:[background:#171e1b] [.puppet-editor_&]:[font-size:0.6875rem]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&.primary]:[border-color:#64e5c4] [.puppet-editor_&.primary]:[color:#07110f]',
    '[.puppet-editor_&.primary]:[background:#64e5c4] [.puppet-editor_&.primary]:font-bold',
    '[.puppet-editor_&:disabled]:[opacity:0.42] [.puppet-editor_&:disabled]:cursor-not-allowed',
    '[.puppet-editor_&_input]:fixed [.puppet-editor_&_input]:[inline-size:0.0625rem]',
    '[.puppet-editor_&_input]:[block-size:0.0625rem] [.puppet-editor_&_input]:[opacity:0]',
    '[.puppet-editor_&_input]:pointer-events-none',
  ],
  'toolbar-menu': ['[.puppet-editor_&]:[anchor-scope:\\-\\-toolbar-menu]'],
  'toolbar-menu-content': [
    '[.puppet-editor_&]:hidden [.puppet-editor_&]:fixed [.puppet-editor_&]:[position-anchor:\\-\\-toolbar-menu]',
    '[.puppet-editor_&]:[inset:auto] [.puppet-editor_&]:[top:anchor(bottom)]',
    '[.puppet-editor_&]:[left:anchor(left)] [.puppet-editor_&]:[position-try-fallbacks:flip-inline]',
    '[.puppet-editor_&]:[margin:0.5rem_0_0] [.puppet-editor_&]:[min-width:11rem]',
    '[.puppet-editor_&]:[padding:0.375rem] [.puppet-editor_&]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&]:[border-radius:0.625rem] [.puppet-editor_&]:[background:#171e1b]',
    '[.puppet-editor_&]:[color:#e9f3ef] [.puppet-editor_&]:[box-shadow:0_0.5rem_1.5rem_#0006]',
    '[.puppet-editor_&:popover-open]:grid',
    '[.puppet-editor_&_button]:[padding:0.625rem_0.75rem] [.puppet-editor_&_button]:[border:0]',
    '[.puppet-editor_&_button]:[border-radius:0.3125rem] [.puppet-editor_&_button]:[background:transparent]',
    '[.puppet-editor_&_button]:[color:inherit] [.puppet-editor_&_button]:text-left',
    '[.puppet-editor_&_button]:[font-size:0.75rem] [.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button:hover]:[background:#26332f]',
    '[.puppet-editor_&_button:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&_button:focus-visible]:[outline-offset:0.125rem]',
    '[.puppet-editor_&_hr]:w-full [.puppet-editor_&_hr]:[margin:0.25rem_0] [.puppet-editor_&_hr]:[border:0]',
    '[.puppet-editor_&_hr]:[border-top:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_button:disabled]:[opacity:0.42] [.puppet-editor_&_button:disabled]:cursor-not-allowed',
    '[.puppet-editor_&_button:disabled]:[background:transparent]',
  ],
  'toolbar-menu-trigger': [
    '[.puppet-editor_&]:[anchor-name:\\-\\-toolbar-menu] [.puppet-editor_&]:grid',
    '[.puppet-editor_&]:place-items-center [.puppet-editor_&]:[width:2rem] [.puppet-editor_&]:[height:2rem]',
    '[.puppet-editor_&]:[padding:0.375rem] [.puppet-editor_&]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&]:[border-radius:0.4375rem] [.puppet-editor_&]:[background:#171e1b]',
    '[.puppet-editor_&]:[color:#b9c5c0] [.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&_svg]:w-full [.puppet-editor_&_svg]:h-full [.puppet-editor_&_svg]:fill-none',
    '[.puppet-editor_&_svg]:[stroke:currentColor] [.puppet-editor_&_svg]:[stroke-width:1.75]',
    '[.puppet-editor_&_svg]:stroke-cap-round',
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:0.125rem]',
  ],
  'visually-hidden': [
    '[.puppet-editor_&]:fixed [.puppet-editor_&]:[inline-size:0.0625rem]',
    '[.puppet-editor_&]:[block-size:0.0625rem] [.puppet-editor_&]:overflow-hidden',
    '[.puppet-editor_&]:[clip-path:inset(50%)] [.puppet-editor_&]:whitespace-nowrap',
  ],
  'workspace-switcher': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:[gap:0.1875rem] [.puppet-editor_&]:[padding:0.1875rem]',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#313b37] [.puppet-editor_&]:[border-radius:0.5rem]',
    '[.puppet-editor_&]:[background:#0d1210]',
    '[.puppet-editor_&_button]:[padding:0.375rem_0.75rem] [.puppet-editor_&_button]:[border:0]',
    '[.puppet-editor_&_button]:[border-radius:0.3125rem] [.puppet-editor_&_button]:[color:#7f8d88]',
    '[.puppet-editor_&_button]:[background:transparent] [.puppet-editor_&_button]:[font-size:0.6875rem]',
    '[.puppet-editor_&_button]:cursor-pointer',
    "[.puppet-editor_&_button[aria-pressed='true']]:[color:#e9f3ef]",
    "[.puppet-editor_&_button[aria-pressed='true']]:[background:#26332f]",
    '[.puppet-editor_&_button:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&_button:focus-visible]:[outline-offset:0.125rem]',
  ],
}
