export const parametersShortcuts = {
  'keyform-actions': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:flex-nowrap [.puppet-editor_&]:min-w-max',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:gap-editor-field',
    '[.puppet-editor_&_>_button]:shrink-0',
    '[.puppet-editor_&_button]:py-editor-control [.puppet-editor_&_button]:px-editor-field',
    '[.puppet-editor_&_button]:[border:0.0625rem_solid_#3d5f56]',
    '[.puppet-editor_&_button]:[border-radius:0.375rem] [.puppet-editor_&_button]:[color:#bfeee1]',
    '[.puppet-editor_&_button]:[background:#17211e] [.puppet-editor_&_button]:text-editor-caption',
    '[.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button.danger]:[border-color:#66403e] [.puppet-editor_&_button.danger]:[color:#ffc5c0]',
    '[.puppet-editor_&_button.danger]:[background:#241817]',
    '[.puppet-editor_&_button:disabled]:[opacity:0.42] [.puppet-editor_&_button:disabled]:cursor-not-allowed',
  ],
  'keyform-binding-row':
    'grid min-w-0 [grid-template-columns:13.75rem_minmax(0,_1fr)] [border-top:0.0625rem_solid_#35413d]',
  'keyform-footer': [
    '[.puppet-editor_&]:flex-wrap [.puppet-editor_&]:gap-editor-field',
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:justify-between',
    '[.puppet-editor_&]:py-editor-control [.puppet-editor_&]:px-editor-group',
    '[.puppet-editor_&]:[border-top:0.0625rem_solid_#27302d]',
  ],

  'keyform-help': [
    '[.puppet-editor_&]:m-0 [.puppet-editor_&]:[color:#84918c] [.puppet-editor_&]:text-editor-caption',
    '[.puppet-editor_&]:[line-height:1.5]',
  ],
  'keyform-marker': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:50%] [.puppet-editor_&]:[width:0.875rem]',
    '[.puppet-editor_&]:[height:0.875rem] [.puppet-editor_&]:p-0',
    '[.puppet-editor_&]:[border:0.125rem_solid_#b8f5e5] [.puppet-editor_&]:[border-radius:0.125rem]',
    '[.puppet-editor_&]:[background:#64e5c4] [.puppet-editor_&]:[transform:translate(-50%,_-50%)_rotate(45deg)]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&.draggable]:[cursor:ew-resize] [.puppet-editor_&.draggable]:touch-none',
    '[.puppet-editor_&.dragging]:[border-color:#fff0cf] [.puppet-editor_&.dragging]:[background:#ffbd59]',
    '[.puppet-editor_&_>_span]:absolute [.puppet-editor_&_>_span]:[top:1rem]',
    '[.puppet-editor_&_>_span]:[left:0.875rem] [.puppet-editor_&_>_span]:[color:#82908b]',
    '[.puppet-editor_&_>_span]:font-editor-mono',
    '[.puppet-editor_&_>_span]:text-editor-micro',
    '[.puppet-editor_&_>_span]:[transform:rotate(-45deg)_translateX(-50%)]',
    "[.puppet-editor_&[aria-pressed='true']]:[border-color:#fff0cf]",
    "[.puppet-editor_&[aria-pressed='true']]:[background:#ffbd59]",
    "[.puppet-editor_&[aria-pressed='true']]:[box-shadow:0_0_0_0.1875rem_rgb(255_189_89_/_18%)]",
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#fff0cf]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:0.25rem]',
  ],
  'keyform-panel': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:min-h-0',
    '[.puppet-editor_&]:[grid-template-rows:auto_minmax(4.75rem,_1fr)_auto]',
    '[.puppet-editor_&]:[background:#111614]',
  ],
  'keyform-parameter-heading': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:gap-editor-field [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:[color:#c5d0cc] [.puppet-editor_&]:text-editor-caption [.puppet-editor_&]:font-bold',
    '[.puppet-editor_&]:[letter-spacing:0.08rem] [.puppet-editor_&]:[text-transform:uppercase]',
  ],
  'keyform-row-value': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&]:[grid-template-columns:minmax(0,_1fr)_4.5rem] [.puppet-editor_&]:gap-editor-field',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:font-editor-mono',
    '[.puppet-editor_&]:text-editor-metadata [.puppet-editor_&]:whitespace-nowrap',
    '[.puppet-editor_&_input]:box-border [.puppet-editor_&_input]:w-full [.puppet-editor_&_input]:min-w-0',
    '[.puppet-editor_&_input]:py-editor-related [.puppet-editor_&_input]:px-editor-control',
    '[.puppet-editor_&_input]:[border:0.0625rem_solid_#3b4743]',
    '[.puppet-editor_&_input]:[border-radius:0.3125rem] [.puppet-editor_&_input]:[color:#e5eeea]',
    '[.puppet-editor_&_input]:[background:#171e1b] [.puppet-editor_&_input]:[font:inherit]',
  ],
  'keyform-row-values': ['[.puppet-editor_&]:grid [.puppet-editor_&]:gap-editor-related'],
  'keyform-toolbar': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:overflow-x-auto',
    '[.puppet-editor_&]:[min-height:2.8125rem]',
    '[.puppet-editor_&]:[grid-template-columns:minmax(max-content,_13.125rem)_minmax(max-content,_1fr)]',
    '[.puppet-editor_&]:gap-editor-group',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:py-editor-field [.puppet-editor_&]:px-editor-group',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d]',
  ],
  'keyform-track': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:[min-width:10rem] [.puppet-editor_&]:[min-height:4.75rem]',
    '[.puppet-editor_&]:[margin:0_1.75rem]',
    '[.puppet-editor_&]:[background-image:linear-gradient(to_right,_#27322e_0.0625rem,_transparent_0.0625rem)]',
    '[.puppet-editor_&]:[background-size:12.5%_100%] [.puppet-editor_&]:[cursor:crosshair]',
    '[.puppet-editor_&]:touch-none',
    '[.puppet-editor_&::before]:absolute [.puppet-editor_&::before]:[top:50%]',
    '[.puppet-editor_&::before]:[right:0] [.puppet-editor_&::before]:[left:0]',
    '[.puppet-editor_&::before]:[height:0.0625rem] [.puppet-editor_&::before]:[background:#3a4642]',
    "[.puppet-editor_&::before]:[content:'']",
  ],
  'keyform-track-label': [
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[min-height:4.75rem]',
    '[.puppet-editor_&_.parameter-item-surface]:[border-right:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_.parameter-item-surface]:[border-bottom:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_.parameter-item-surface]:[border-radius:0]',
    '[.puppet-editor_&_.parameter-item-surface]:overflow-hidden',
    '[.puppet-editor_&.parameter-grid-label]:[min-height:7.75rem]',
    '[.puppet-editor_&_.parameter-swipe-row]:[min-height:4.75rem]',
    '[.puppet-editor_&_.parameter-swipe-row]:[border-radius:0]',
    '[.puppet-editor_&_.parameter-item]:[min-height:4.75rem]',
    '[.puppet-editor_&_.parameter-item]:[border-radius:0]',
    '[.puppet-editor_&_.parameter-item]:[padding-bottom:2.375rem]',
    '[.puppet-editor_&_.parameter-item]:[border-width:0]',
    '[.puppet-editor_&.parameter-grid-label_.parameter-swipe-row]:[min-height:7.75rem]',
    '[.puppet-editor_&.parameter-grid-label_.parameter-item]:[min-height:7.75rem]',
    '[.puppet-editor_&.parameter-grid-label_.parameter-item]:[padding-bottom:4.125rem]',
  ],
  'keyform-track-labels': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[align-content:start] [grid-column:1] [grid-row:1_/_3]',
  ],
  'keyform-track-scroll': [
    '[.puppet-editor_&]:box-border [.puppet-editor_&]:[border-bottom:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:overflow-x-auto',
    '[.puppet-editor_&]:[grid-column:2] [.puppet-editor_&]:[grid-row:1_/_3]',
  ],
  'keyform-track-wrap': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:min-h-0',

    '[.puppet-editor_&]:[align-content:start] [.puppet-editor_&]:[overflow-x:hidden]',
    '[.puppet-editor_&]:overflow-y-auto',
  ],
  'keyform-tracks': [
    '[.puppet-editor_&]:h-full [.puppet-editor_&]:[grid-template-rows:1fr]',
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[align-content:start]',
    '[.puppet-editor_&]:[min-width:13.5rem]',
  ],
  'keyform-value-indicator': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0] [.puppet-editor_&]:[bottom:0]',
    '[.puppet-editor_&]:[width:0.6875rem] [.puppet-editor_&]:p-0 [.puppet-editor_&]:[border:0]',
    '[.puppet-editor_&]:editor-parameter-marker',
    '[.puppet-editor_&]:[transform:translateX(-50%)] [.puppet-editor_&]:[cursor:ew-resize]',
    '[.puppet-editor_&]:touch-none',
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#fff0cf]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:-0.125rem]',
  ],
  'parameter-binding-name': [
    '[.puppet-editor_&]:m-0 [.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&]:break-words [.puppet-editor_&]:text-editor-body',
    '[.puppet-editor_&]:font-medium [.puppet-editor_&]:text-[#dfe8e4]',
  ],
  'parameter-editor': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:gap-editor-field [.puppet-editor_&]:mt-editor-section',
    '[.puppet-editor_&]:pt-editor-section [.puppet-editor_&]:[border-top:0.0625rem_solid_#27302d]',
    '[.puppet-editor_&_label]:grid [.puppet-editor_&_label]:[grid-template-columns:4.625rem_minmax(0,_1fr)]',
    '[.puppet-editor_&_label]:gap-editor-field [.puppet-editor_&_label]:items-center',
    '[.puppet-editor_&_label]:[color:#84918c] [.puppet-editor_&_label]:text-editor-caption',
    "[.puppet-editor_&_input[type='number']]:min-w-0",
    "[.puppet-editor_&_input[type='number']]:py-editor-control [.puppet-editor_&_input[type='number']]:px-editor-field",
    "[.puppet-editor_&_input[type='number']]:[border:0.0625rem_solid_#3b4743]",
    "[.puppet-editor_&_input[type='number']]:[border-radius:0.375rem]",
    "[.puppet-editor_&_input[type='number']]:[color:#e5eeea]",
    "[.puppet-editor_&_input[type='number']]:[background:#171e1b]",
    '[.puppet-editor_&_input:not([type])]:min-w-0',
    '[.puppet-editor_&_input:not([type])]:py-editor-control [.puppet-editor_&_input:not([type])]:px-editor-field',
    '[.puppet-editor_&_input:not([type])]:[border:0.0625rem_solid_#3b4743]',
    '[.puppet-editor_&_input:not([type])]:[border-radius:0.375rem]',
    '[.puppet-editor_&_input:not([type])]:[color:#e5eeea]',
    '[.puppet-editor_&_input:not([type])]:[background:#171e1b]',
    "[.puppet-editor_&_input[type='range']]:w-full",
    "[.puppet-editor_&_input[type='range']]:[accent-color:#64e5c4]",
  ],
  'parameter-grid': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[inset:1rem_0] [.puppet-editor_&]:[cursor:crosshair]',
    '[.puppet-editor_&]:touch-none',
  ],
  'parameter-grid-current-x': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[background:#ffbd59] [.puppet-editor_&]:pointer-events-none',
    '[.puppet-editor_&]:[top:-1rem] [.puppet-editor_&]:[bottom:-1rem] [.puppet-editor_&]:[width:0.0625rem]',
    '[.puppet-editor_&]:[transform:translateX(-50%)]',
  ],
  'parameter-grid-current-y': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[background:#ffbd59] [.puppet-editor_&]:pointer-events-none',
    '[.puppet-editor_&]:[right:0] [.puppet-editor_&]:[left:0] [.puppet-editor_&]:[height:0.0625rem]',
    '[.puppet-editor_&]:[transform:translateY(50%)]',
  ],
  'parameter-grid-keyform': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[width:0.875rem] [.puppet-editor_&]:[height:0.875rem]',
    '[.puppet-editor_&]:p-0 [.puppet-editor_&]:[border:0.125rem_solid_#b8f5e5]',
    '[.puppet-editor_&]:[border-radius:0.125rem] [.puppet-editor_&]:[background:#64e5c4]',
    '[.puppet-editor_&]:[transform:translate(-50%,_50%)_rotate(45deg)] [.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&.selected]:[border-color:#fff0cf] [.puppet-editor_&.selected]:[background:#ffbd59]',
    '[.puppet-editor_&.selected]:[box-shadow:0_0_0_0.1875rem_rgb(255_189_89_/_18%)]',
  ],
  'parameter-grid-track': [
    '[.puppet-editor_&]:[min-height:7.75rem]',
    '[.puppet-editor_&::before]:[top:50%]',
  ],
  'parameter-inspector': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:gap-editor-field',
    '[.puppet-editor_&_>_.deformer-properties]:mt-0',
  ],
  'parameter-item': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:grid [.puppet-editor_&]:w-full',
    '[.puppet-editor_&]:gap-editor-related [.puppet-editor_&]:py-editor-field [.puppet-editor_&]:pr-[1.875rem]',
    '[.puppet-editor_&]:pl-editor-field',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#313b37] [.puppet-editor_&]:[border-radius:0.4375rem]',
    '[.puppet-editor_&]:[color:#a7b3af] [.puppet-editor_&]:[background:#121916]',
    '[.puppet-editor_&]:text-left',

    '[.puppet-editor_&]:[transition:transform_160ms_ease-out] [.puppet-editor_&]:select-none',
    '[.puppet-editor_&[data-selected]]:[border-color:#4a776b]',
    '[.puppet-editor_&[data-selected]]:[color:#f3f7f5]',
    '[.puppet-editor_&[data-selected]]:[background:#17211e]',
    '[.puppet-editor_&_strong]:text-editor-body',
    '[.puppet-editor_&_small]:[color:#8f9d98]',
    '[.puppet-editor_&_small]:font-editor-mono',
    '[.puppet-editor_&_small]:text-editor-metadata',
  ],
  'parameter-item-details': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[right:1.875rem] [.puppet-editor_&]:bottom-editor-field',
    '[.puppet-editor_&]:left-editor-field [.puppet-editor_&]:[color:#a7b3af]',

    '[.puppet-editor_&]:[transition:transform_160ms_ease-out]',
  ],
  'parameter-item-main': 'relative',
  'parameter-item-surface': [
    '[&:has(.parameter-item[data-selected])]:bg-[#17211e]',
    'relative bg-[#121916] [transform:translateX(var(--parameter-swipe-offset))]',
    '[transition:transform_160ms_ease-out] [.dragging_&]:transition-none',
  ],
  'parameter-list': ['[.puppet-editor_&]:grid [.puppet-editor_&]:gap-editor-control'],
  'parameter-name-control': [
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:border-0 [.puppet-editor_&]:p-0',
    '[.puppet-editor_&]:[color:inherit] [.puppet-editor_&]:bg-transparent',
    '[.puppet-editor_&]:cursor-pointer [.puppet-editor_&]:text-left',
    '[.puppet-editor_&_strong]:block [.puppet-editor_&_strong]:overflow-hidden',
    '[.puppet-editor_&_strong]:[text-overflow:ellipsis] [.puppet-editor_&_strong]:whitespace-nowrap',
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:0.125rem]',
  ],
  'parameter-name-editor': [
    '[.puppet-editor_&]:[min-height:3rem] [.puppet-editor_&]:[align-content:center]',
    '[.puppet-editor_&_input]:w-full [.puppet-editor_&_input]:min-w-0',
    '[.puppet-editor_&_input]:py-editor-related [.puppet-editor_&_input]:px-editor-field',
    '[.puppet-editor_&_input]:[border:0.0625rem_solid_#64e5c4]',
    '[.puppet-editor_&_input]:[border-radius:0.3125rem] [.puppet-editor_&_input]:[color:#f3f7f5]',
    '[.puppet-editor_&_input]:[background:#171e1b] [.puppet-editor_&_input]:text-editor-body',
    '[.puppet-editor_&_input]:font-bold',
    '[.puppet-editor_&_input:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&_input:focus-visible]:[outline-offset:0.0625rem]',
  ],
  'parameter-properties': [
    '[.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&_button.influence-toggle]:justify-between',
    '[.puppet-editor_&_button.influence-toggle]:px-0',
  ],
  'parameter-range': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:justify-between [.puppet-editor_&]:[color:#6f7d78]',
    '[.puppet-editor_&]:font-editor-mono',
    '[.puppet-editor_&]:text-editor-metadata',
  ],
  'parameter-section-summary': [
    '[.puppet-editor_&]:m-0 [.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&]:break-words [.puppet-editor_&]:text-editor-caption',
    '[.puppet-editor_&]:leading-normal [.puppet-editor_&]:text-[#a9bdb5]',
  ],
  'parameter-settings-toggles': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[grid-template-columns:1fr_1fr]',
    '[.puppet-editor_&]:[grid-column:1] [.puppet-editor_&]:[grid-row:2]',
    '[.puppet-editor_&_>_.influence-toggle]:[grid-column:auto] [.puppet-editor_&_>_.influence-toggle]:[grid-row:auto]',
  ],
  'parameter-swipe-delete': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0] [.puppet-editor_&]:[left:0]',
    '[.puppet-editor_&]:[bottom:0] [.puppet-editor_&]:grid [.puppet-editor_&]:[width:5rem]',
    '[.puppet-editor_&]:gap-editor-tight [.puppet-editor_&]:[align-content:center]',
    '[.puppet-editor_&]:[justify-items:center] [.puppet-editor_&]:[color:#f3aaa5]',
    '[.puppet-editor_&]:[background:#471f1d] [.puppet-editor_&]:text-editor-micro [.puppet-editor_&]:font-bold',
    '[.puppet-editor_&_.puppet-icon]:[width:1rem] [.puppet-editor_&_.puppet-icon]:[height:1rem]',
  ],
  'parameter-swipe-hint': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0.625rem] [.puppet-editor_&]:left-editor-field',
    '[.puppet-editor_&]:[color:#596762] [.puppet-editor_&]:text-editor-reading',
  ],
  'parameter-swipe-row': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[border-radius:0.4375rem]',
    '[.puppet-editor_&]:overflow-hidden [.puppet-editor_&]:[background:#351918]',
    '[.puppet-editor_&]:[touch-action:pan-y]',
    '[.puppet-editor_&.armed_.parameter-swipe-delete]:[color:#fff1ef]',
    '[.puppet-editor_&.armed_.parameter-swipe-delete]:[background:#a63f3a]',
    '[.puppet-editor_&.dragging_.parameter-item]:cursor-grabbing',
    '[.puppet-editor_&.dragging_.parameter-item]:[transition:none]',
    '[.puppet-editor_&.dragging_.parameter-item-details]:[transition:none]',
  ],
  'parameter-target-actions': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:flex-wrap [.puppet-editor_&]:gap-editor-control',
    '[.puppet-editor_&_button]:py-editor-related [.puppet-editor_&_button]:px-editor-field',
    '[.puppet-editor_&_button]:[border:0.0625rem_solid_#3d5f56]',
    '[.puppet-editor_&_button]:[border-radius:0.375rem] [.puppet-editor_&_button]:[color:#bfeee1]',
    '[.puppet-editor_&_button]:[background:#17211e] [.puppet-editor_&_button]:text-editor-metadata',
    '[.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button:disabled]:[border-color:#5b6e67]',
    '[.puppet-editor_&_button:disabled]:[color:#84918c] [.puppet-editor_&_button:disabled]:[background:#121816]',
    '[.puppet-editor_&_button:disabled]:cursor-not-allowed',
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='true']]:[border-color:#64e5c4]",
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='true']]:[color:#bfeee1]",
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='true']]:[background:#1a2925]",
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='false']]:[border-color:#5b6e67]",
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='false']]:[color:#84918c]",
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='false']]:[background:#121816]",
    '[.puppet-editor_&_.parameter-visibility-toggle:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&_.parameter-visibility-toggle:focus-visible]:[outline-offset:0.125rem]',
  ],
  'parameter-target-editor': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:gap-editor-field [.puppet-editor_&]:mt-editor-control',
    '[.puppet-editor_&]:pt-editor-group [.puppet-editor_&]:[border-top:0.0625rem_solid_#27302d]',
    '[.puppet-editor_&_p]:m-0 [.puppet-editor_&_p]:[color:#788580] [.puppet-editor_&_p]:text-editor-metadata',
    '[.puppet-editor_&_p]:[line-height:1.5]',
  ],
  'parameter-target-heading': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:justify-between',
    '[.puppet-editor_&]:[color:#c6d2cd] [.puppet-editor_&]:text-editor-caption',
    '[.puppet-editor_&_span]:[color:#64e5c4]',
    '[.puppet-editor_&_span]:font-editor-mono',
  ],
  'parameter-target-list': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:flex-wrap [.puppet-editor_&]:gap-editor-related',
    '[.puppet-editor_&]:m-0 [.puppet-editor_&]:p-0 [.puppet-editor_&]:[list-style:none]',
    '[.puppet-editor_&_li]:py-editor-related [.puppet-editor_&_li]:px-editor-control',
    '[.puppet-editor_&_li]:[border:0.0625rem_solid_#35564e]',
    '[.puppet-editor_&_li]:[border-radius:62.4375rem] [.puppet-editor_&_li]:[color:#bfeee1]',
    '[.puppet-editor_&_li]:[background:#17211e] [.puppet-editor_&_li]:text-editor-metadata',
  ],
  'puppet-layer-parameter-links': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:gap-editor-related',
    '[.puppet-editor_&]:overflow-hidden',
    '[.puppet-editor_&_span]:py-editor-tight [.puppet-editor_&_span]:px-editor-related',
    '[.puppet-editor_&_span]:overflow-hidden',
    '[.puppet-editor_&_span]:[border-radius:62.4375rem] [.puppet-editor_&_span]:[color:#9fe7d4]',
    '[.puppet-editor_&_span]:[background:#1b302a] [.puppet-editor_&_span]:text-editor-micro',
    '[.puppet-editor_&_span]:[text-overflow:ellipsis] [.puppet-editor_&_span]:whitespace-nowrap',
  ],
}
