export const parametersShortcuts = {
  'keyform-actions': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:[gap:0.5rem]',
    '[.puppet-editor_&_button]:[padding:0.375rem_0.625rem]',
    '[.puppet-editor_&_button]:[border:0.0625rem_solid_#3d5f56]',
    '[.puppet-editor_&_button]:[border-radius:0.375rem] [.puppet-editor_&_button]:[color:#bfeee1]',
    '[.puppet-editor_&_button]:[background:#17211e] [.puppet-editor_&_button]:[font-size:0.625rem]',
    '[.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button.danger]:[border-color:#66403e] [.puppet-editor_&_button.danger]:[color:#ffc5c0]',
    '[.puppet-editor_&_button.danger]:[background:#241817]',
    '[.puppet-editor_&_button:disabled]:[opacity:0.42] [.puppet-editor_&_button:disabled]:cursor-not-allowed',
  ],
  'keyform-footer': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:justify-between',
    '[.puppet-editor_&]:[padding:0.5rem_1rem] [.puppet-editor_&]:[border-top:0.0625rem_solid_#27302d]',
  ],
  'keyform-help': [
    '[.puppet-editor_&]:m-0 [.puppet-editor_&]:[color:#84918c] [.puppet-editor_&]:[font-size:0.625rem]',
    '[.puppet-editor_&]:[line-height:1.5]',
  ],
  'keyform-marker': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:50%] [.puppet-editor_&]:[width:0.875rem]',
    '[.puppet-editor_&]:[height:0.875rem] [.puppet-editor_&]:p-0',
    '[.puppet-editor_&]:[border:0.125rem_solid_#b8f5e5] [.puppet-editor_&]:[border-radius:0.125rem]',
    '[.puppet-editor_&]:[background:#64e5c4] [.puppet-editor_&]:[transform:translate(-50%,_-50%)_rotate(45deg)]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&.draggable]:[cursor:ew-resize] [.puppet-editor_&.draggable]:touch-none',
    '[.puppet-editor_&.dragging]:[border-color:#fff0cf] [.puppet-editor_&.dragging]:[background:#ffbd59]',
    '[.puppet-editor_&_>_span]:absolute [.puppet-editor_&_>_span]:[top:1rem]',
    '[.puppet-editor_&_>_span]:[left:0.875rem] [.puppet-editor_&_>_span]:[color:#82908b]',
    "[.puppet-editor_&_>_span]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[.puppet-editor_&_>_span]:[font-size:0.5rem]',
    '[.puppet-editor_&_>_span]:[transform:rotate(-45deg)_translateX(-50%)]',
    "[.puppet-editor_&[aria-pressed='true']]:[border-color:#fff0cf]",
    "[.puppet-editor_&[aria-pressed='true']]:[background:#ffbd59]",
    "[.puppet-editor_&[aria-pressed='true']]:[box-shadow:0_0_0_0.1875rem_rgb(255_189_89_/_18%)]",
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#fff0cf]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:0.25rem]',
  ],
  'keyform-panel': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:min-h-0',
    '[.puppet-editor_&]:[grid-template-rows:auto_minmax(4.75rem,_1fr)_auto]',
    '[.puppet-editor_&]:[background:#111614]',
  ],
  'keyform-parameter-heading': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:[gap:0.5rem] [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:[color:#c5d0cc] [.puppet-editor_&]:[font-size:0.625rem] [.puppet-editor_&]:font-bold',
    '[.puppet-editor_&]:[letter-spacing:0.08rem] [.puppet-editor_&]:[text-transform:uppercase]',
  ],
  'keyform-row-value': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&]:[grid-template-columns:minmax(0,_1fr)_4.5rem] [.puppet-editor_&]:[gap:0.4375rem]',
    "[.puppet-editor_&]:items-center [.puppet-editor_&]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[.puppet-editor_&]:[font-size:0.5625rem] [.puppet-editor_&]:whitespace-nowrap',
    '[.puppet-editor_&_input]:box-border [.puppet-editor_&_input]:w-full [.puppet-editor_&_input]:min-w-0',
    '[.puppet-editor_&_input]:[padding:0.25rem_0.375rem]',
    '[.puppet-editor_&_input]:[border:0.0625rem_solid_#3b4743]',
    '[.puppet-editor_&_input]:[border-radius:0.3125rem] [.puppet-editor_&_input]:[color:#e5eeea]',
    '[.puppet-editor_&_input]:[background:#171e1b] [.puppet-editor_&_input]:[font:inherit]',
  ],
  'keyform-row-values': ['[.puppet-editor_&]:grid [.puppet-editor_&]:[gap:0.3125rem]'],
  'keyform-toolbar': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[min-height:3.625rem]',
    '[.puppet-editor_&]:[grid-template-columns:13.125rem_minmax(0,_1fr)] [.puppet-editor_&]:[gap:0.875rem]',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:[padding:0.5625rem_1rem]',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d]',
  ],
  'keyform-track': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:[min-width:40rem] [.puppet-editor_&]:[min-height:4.75rem]',
    '[.puppet-editor_&]:[margin:0_1.75rem] [.puppet-editor_&]:[border-bottom:0.0625rem_solid_#222b28]',
    '[.puppet-editor_&]:[background-image:linear-gradient(to_right,_#27322e_0.0625rem,_transparent_0.0625rem)]',
    '[.puppet-editor_&]:[background-size:12.5%_100%] [.puppet-editor_&]:[cursor:crosshair]',
    '[.puppet-editor_&]:touch-none',
    '[.puppet-editor_&::before]:absolute [.puppet-editor_&::before]:[top:50%]',
    '[.puppet-editor_&::before]:[right:0] [.puppet-editor_&::before]:[left:0]',
    '[.puppet-editor_&::before]:[height:0.0625rem] [.puppet-editor_&::before]:[background:#3a4642]',
    "[.puppet-editor_&::before]:[content:'']",
  ],
  'keyform-track-label': [
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[min-height:4.75rem]',
    '[.puppet-editor_&]:[border-right:0.0625rem_solid_#27302d]',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#222b28] [.puppet-editor_&]:[background:#121816]',
    '[.puppet-editor_&.parameter-grid-label]:[min-height:7.75rem]',
    '[.puppet-editor_&_.parameter-swipe-row]:[min-height:4.75rem]',
    '[.puppet-editor_&_.parameter-swipe-row]:[border-radius:0]',
    '[.puppet-editor_&_.parameter-item]:[min-height:4.75rem]',
    '[.puppet-editor_&_.parameter-item]:[border-radius:0]',
    '[.puppet-editor_&_.parameter-item]:[padding-bottom:2.375rem]',
    '[.puppet-editor_&_.parameter-item]:[border-width:0]',
    '[.puppet-editor_&.parameter-grid-label_.parameter-swipe-row]:[min-height:7.75rem]',
    '[.puppet-editor_&.parameter-grid-label_.parameter-item]:[min-height:7.75rem]',
    '[.puppet-editor_&.parameter-grid-label_.parameter-item]:[padding-bottom:4.125rem]',
  ],
  'keyform-track-labels': ['[.puppet-editor_&]:grid [.puppet-editor_&]:[align-content:start]'],
  'keyform-track-scroll': ['[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:overflow-x-auto'],
  'keyform-track-wrap': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:min-h-0',
    '[.puppet-editor_&]:[grid-template-columns:13.75rem_minmax(0,_1fr)]',
    '[.puppet-editor_&]:[align-content:start] [.puppet-editor_&]:[overflow-x:hidden]',
    '[.puppet-editor_&]:overflow-y-auto',
  ],
  'keyform-tracks': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[align-content:start]',
    '[.puppet-editor_&]:[min-width:43.5rem]',
  ],
  'keyform-value-indicator': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0] [.puppet-editor_&]:[bottom:0]',
    '[.puppet-editor_&]:[width:0.6875rem] [.puppet-editor_&]:p-0 [.puppet-editor_&]:[border:0]',
    '[.puppet-editor_&]:editor-parameter-marker',
    '[.puppet-editor_&]:[transform:translateX(-50%)] [.puppet-editor_&]:[cursor:ew-resize]',
    '[.puppet-editor_&]:touch-none',
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#fff0cf]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:-0.125rem]',
  ],
  'parameter-editor': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[gap:0.625rem] [.puppet-editor_&]:[margin-top:1.125rem]',
    '[.puppet-editor_&]:[padding-top:1rem] [.puppet-editor_&]:[border-top:0.0625rem_solid_#27302d]',
    '[.puppet-editor_&_label]:grid [.puppet-editor_&_label]:[grid-template-columns:4.625rem_minmax(0,_1fr)]',
    '[.puppet-editor_&_label]:[gap:0.5rem] [.puppet-editor_&_label]:items-center',
    '[.puppet-editor_&_label]:[color:#84918c] [.puppet-editor_&_label]:[font-size:0.625rem]',
    "[.puppet-editor_&_input[type='number']]:min-w-0",
    "[.puppet-editor_&_input[type='number']]:[padding:0.375rem_0.5rem]",
    "[.puppet-editor_&_input[type='number']]:[border:0.0625rem_solid_#3b4743]",
    "[.puppet-editor_&_input[type='number']]:[border-radius:0.375rem]",
    "[.puppet-editor_&_input[type='number']]:[color:#e5eeea]",
    "[.puppet-editor_&_input[type='number']]:[background:#171e1b]",
    '[.puppet-editor_&_input:not([type])]:min-w-0',
    '[.puppet-editor_&_input:not([type])]:[padding:0.375rem_0.5rem]',
    '[.puppet-editor_&_input:not([type])]:[border:0.0625rem_solid_#3b4743]',
    '[.puppet-editor_&_input:not([type])]:[border-radius:0.375rem]',
    '[.puppet-editor_&_input:not([type])]:[color:#e5eeea]',
    '[.puppet-editor_&_input:not([type])]:[background:#171e1b]',
    "[.puppet-editor_&_input[type='range']]:w-full",
    "[.puppet-editor_&_input[type='range']]:[accent-color:#64e5c4]",
  ],
  'parameter-grid': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[inset:1rem_0] [.puppet-editor_&]:[cursor:crosshair]',
    '[.puppet-editor_&]:touch-none',
  ],
  'parameter-grid-current-x': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[background:#ffbd59] [.puppet-editor_&]:pointer-events-none',
    '[.puppet-editor_&]:[top:-1rem] [.puppet-editor_&]:[bottom:-1rem] [.puppet-editor_&]:[width:0.0625rem]',
    '[.puppet-editor_&]:[transform:translateX(-50%)]',
  ],
  'parameter-grid-current-y': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[background:#ffbd59] [.puppet-editor_&]:pointer-events-none',
    '[.puppet-editor_&]:[right:0] [.puppet-editor_&]:[left:0] [.puppet-editor_&]:[height:0.0625rem]',
    '[.puppet-editor_&]:[transform:translateY(50%)]',
  ],
  'parameter-grid-keyform': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[width:0.875rem] [.puppet-editor_&]:[height:0.875rem]',
    '[.puppet-editor_&]:p-0 [.puppet-editor_&]:[border:0.125rem_solid_#b8f5e5]',
    '[.puppet-editor_&]:[border-radius:0.125rem] [.puppet-editor_&]:[background:#64e5c4]',
    '[.puppet-editor_&]:[transform:translate(-50%,_50%)_rotate(45deg)] [.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&.selected]:[border-color:#fff0cf] [.puppet-editor_&.selected]:[background:#ffbd59]',
    '[.puppet-editor_&.selected]:[box-shadow:0_0_0_0.1875rem_rgb(255_189_89_/_18%)]',
  ],
  'parameter-grid-track': [
    '[.puppet-editor_&]:[min-height:7.75rem]',
    '[.puppet-editor_&::before]:[top:50%]',
  ],
  'parameter-item': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:grid [.puppet-editor_&]:w-full',
    '[.puppet-editor_&]:[gap:0.25rem] [.puppet-editor_&]:[padding:0.5625rem_1.875rem_0.5625rem_0.625rem]',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#313b37] [.puppet-editor_&]:[border-radius:0.4375rem]',
    '[.puppet-editor_&]:[color:#a7b3af] [.puppet-editor_&]:[background:#121916]',
    '[.puppet-editor_&]:cursor-pointer [.puppet-editor_&]:text-left',
    '[.puppet-editor_&]:[transform:translateX(calc(var(--parameter-swipe-offset)_*_-1))]',
    '[.puppet-editor_&]:[transition:transform_160ms_ease-out] [.puppet-editor_&]:select-none',
    "[.puppet-editor_&[aria-pressed='true']]:[border-color:#4a776b]",
    "[.puppet-editor_&[aria-pressed='true']]:[color:#f3f7f5]",
    "[.puppet-editor_&[aria-pressed='true']]:[background:#17211e]",
    '[.puppet-editor_&_strong]:[font-size:0.6875rem]',
    '[.puppet-editor_&_small]:[color:#8f9d98]',
    "[.puppet-editor_&_small]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[.puppet-editor_&_small]:[font-size:0.5625rem]',
  ],
  'parameter-item-details': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[right:1.875rem] [.puppet-editor_&]:[bottom:0.5625rem]',
    '[.puppet-editor_&]:[left:0.625rem] [.puppet-editor_&]:[color:#a7b3af]',
    '[.puppet-editor_&]:[transform:translateX(calc(var(--parameter-swipe-offset)_*_-1))]',
    '[.puppet-editor_&]:[transition:transform_160ms_ease-out]',
  ],
  'parameter-list': ['[.puppet-editor_&]:grid [.puppet-editor_&]:[gap:0.375rem]'],
  'parameter-name-editor': [
    '[.puppet-editor_&]:[min-height:3rem] [.puppet-editor_&]:[align-content:center]',
    '[.puppet-editor_&_input]:w-full [.puppet-editor_&_input]:min-w-0',
    '[.puppet-editor_&_input]:[padding:0.3125rem_0.4375rem]',
    '[.puppet-editor_&_input]:[border:0.0625rem_solid_#64e5c4]',
    '[.puppet-editor_&_input]:[border-radius:0.3125rem] [.puppet-editor_&_input]:[color:#f3f7f5]',
    '[.puppet-editor_&_input]:[background:#171e1b] [.puppet-editor_&_input]:[font-size:0.6875rem]',
    '[.puppet-editor_&_input]:font-bold',
    '[.puppet-editor_&_input:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&_input:focus-visible]:[outline-offset:0.0625rem]',
  ],
  'parameter-range': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:justify-between [.puppet-editor_&]:[color:#6f7d78]',
    "[.puppet-editor_&]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[.puppet-editor_&]:[font-size:0.5625rem]',
  ],
  'parameter-swipe-delete': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0] [.puppet-editor_&]:[right:0]',
    '[.puppet-editor_&]:[bottom:0] [.puppet-editor_&]:grid [.puppet-editor_&]:[width:5rem]',
    '[.puppet-editor_&]:[gap:0.125rem] [.puppet-editor_&]:[align-content:center]',
    '[.puppet-editor_&]:[justify-items:center] [.puppet-editor_&]:[color:#f3aaa5]',
    '[.puppet-editor_&]:[background:#471f1d] [.puppet-editor_&]:[font-size:0.5rem] [.puppet-editor_&]:font-bold',
    '[.puppet-editor_&_svg]:[width:1rem] [.puppet-editor_&_svg]:[height:1rem] [.puppet-editor_&_svg]:fill-none',
    '[.puppet-editor_&_svg]:[stroke:currentcolor] [.puppet-editor_&_svg]:stroke-cap-round',
    '[.puppet-editor_&_svg]:[stroke-linejoin:round] [.puppet-editor_&_svg]:[stroke-width:0.0875rem]',
  ],
  'parameter-swipe-hint': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:50%] [.puppet-editor_&]:[right:0.625rem]',
    '[.puppet-editor_&]:[color:#596762] [.puppet-editor_&]:[font-size:0.75rem]',
    '[.puppet-editor_&]:[transform:translateY(-50%)]',
  ],
  'parameter-swipe-row': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[border-radius:0.4375rem]',
    '[.puppet-editor_&]:overflow-hidden [.puppet-editor_&]:[background:#351918]',
    '[.puppet-editor_&]:[touch-action:pan-y]',
    '[.puppet-editor_&.armed_.parameter-swipe-delete]:[color:#fff1ef]',
    '[.puppet-editor_&.armed_.parameter-swipe-delete]:[background:#a63f3a]',
    '[.puppet-editor_&.dragging_.parameter-item]:cursor-grabbing',
    '[.puppet-editor_&.dragging_.parameter-item]:[transition:none]',
    '[.puppet-editor_&.dragging_.parameter-item-details]:[transition:none]',
  ],
  'parameter-target-actions': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:flex-wrap [.puppet-editor_&]:[gap:0.375rem]',
    '[.puppet-editor_&_button]:[padding:0.3125rem_0.4375rem]',
    '[.puppet-editor_&_button]:[border:0.0625rem_solid_#3d5f56]',
    '[.puppet-editor_&_button]:[border-radius:0.375rem] [.puppet-editor_&_button]:[color:#bfeee1]',
    '[.puppet-editor_&_button]:[background:#17211e] [.puppet-editor_&_button]:[font-size:0.5625rem]',
    '[.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button:disabled]:[border-color:#5b6e67]',
    '[.puppet-editor_&_button:disabled]:[color:#84918c] [.puppet-editor_&_button:disabled]:[background:#121816]',
    '[.puppet-editor_&_button:disabled]:cursor-not-allowed',
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='true']]:[border-color:#64e5c4]",
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='true']]:[color:#bfeee1]",
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='true']]:[background:#1a2925]",
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='false']]:[border-color:#5b6e67]",
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='false']]:[color:#84918c]",
    "[.puppet-editor_&_.parameter-visibility-toggle[aria-pressed='false']]:[background:#121816]",
    '[.puppet-editor_&_.parameter-visibility-toggle:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&_.parameter-visibility-toggle:focus-visible]:[outline-offset:0.125rem]',
  ],
  'parameter-target-editor': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[gap:0.5rem] [.puppet-editor_&]:[margin-top:0.375rem]',
    '[.puppet-editor_&]:[padding-top:0.75rem] [.puppet-editor_&]:[border-top:0.0625rem_solid_#27302d]',
    '[.puppet-editor_&_p]:m-0 [.puppet-editor_&_p]:[color:#788580] [.puppet-editor_&_p]:[font-size:0.5625rem]',
    '[.puppet-editor_&_p]:[line-height:1.5]',
  ],
  'parameter-target-heading': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:justify-between',
    '[.puppet-editor_&]:[color:#c6d2cd] [.puppet-editor_&]:[font-size:0.625rem]',
    '[.puppet-editor_&_span]:[color:#64e5c4]',
    "[.puppet-editor_&_span]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
  ],
  'parameter-target-list': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:flex-wrap [.puppet-editor_&]:[gap:0.3125rem]',
    '[.puppet-editor_&]:m-0 [.puppet-editor_&]:p-0 [.puppet-editor_&]:[list-style:none]',
    '[.puppet-editor_&_li]:[padding:0.1875rem_0.375rem] [.puppet-editor_&_li]:[border:0.0625rem_solid_#35564e]',
    '[.puppet-editor_&_li]:[border-radius:62.4375rem] [.puppet-editor_&_li]:[color:#bfeee1]',
    '[.puppet-editor_&_li]:[background:#17211e] [.puppet-editor_&_li]:[font-size:0.5625rem]',
  ],
  'puppet-layer-parameter-links': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[gap:0.1875rem]',
    '[.puppet-editor_&]:overflow-hidden',
    '[.puppet-editor_&_span]:[padding:0.0625rem_0.25rem] [.puppet-editor_&_span]:overflow-hidden',
    '[.puppet-editor_&_span]:[border-radius:62.4375rem] [.puppet-editor_&_span]:[color:#9fe7d4]',
    '[.puppet-editor_&_span]:[background:#1b302a] [.puppet-editor_&_span]:[font-size:0.5rem]',
    '[.puppet-editor_&_span]:[text-overflow:ellipsis] [.puppet-editor_&_span]:whitespace-nowrap',
  ],
  timeline: [
    '[.puppet-editor_&]:[grid-area:timeline] [.puppet-editor_&]:grid [.puppet-editor_&]:min-h-0',
    '[.puppet-editor_&]:[grid-template-rows:auto_minmax(0,_1fr)]',
    '[.puppet-editor_&]:[border-top:0.0625rem_solid_#27302d] [.puppet-editor_&]:[background:#111614]',
  ],
  'timeline-actions': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[gap:0.5rem]',
    '[.puppet-editor_&]:items-center',
  ],
  'timeline-dopesheet': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:min-h-0',
    '[.puppet-editor_&]:[grid-template-columns:13.75rem_minmax(40rem,_1fr)]',
    '[.puppet-editor_&]:[align-content:start] [.puppet-editor_&]:overflow-auto',
  ],
  'timeline-easing': [
    '[.puppet-editor_&_select:disabled]:[opacity:0.42] [.puppet-editor_&_select:disabled]:cursor-not-allowed',
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[gap:0.4375rem]',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:[color:#84918c]',
    '[.puppet-editor_&]:[font-size:0.5625rem]',
    '[.puppet-editor_&_select]:[min-width:6.5rem]',
    '[.puppet-editor_&_select]:[padding:0.3125rem_1.375rem_0.3125rem_0.4375rem]',
    '[.puppet-editor_&_select]:[border:0.0625rem_solid_#3b4743]',
    '[.puppet-editor_&_select]:[border-radius:0.375rem] [.puppet-editor_&_select]:[color:#d7e1dd]',
    '[.puppet-editor_&_select]:[background:#171e1b] [.puppet-editor_&_select]:[font-size:0.625rem]',
  ],
  'timeline-empty': [
    '[.puppet-editor_&]:[grid-column:1_/_-1] [.puppet-editor_&]:m-0 [.puppet-editor_&]:[padding:1.125rem]',
    '[.puppet-editor_&]:[color:#788580] [.puppet-editor_&]:[font-size:0.625rem] [.puppet-editor_&]:text-center',
  ],
  'timeline-keyframe': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:50%] [.puppet-editor_&]:[width:0.625rem]',
    '[.puppet-editor_&]:[height:0.625rem] [.puppet-editor_&]:p-0',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#b8f5e5] [.puppet-editor_&]:[border-radius:0.0625rem]',
    '[.puppet-editor_&]:[background:#64e5c4] [.puppet-editor_&]:[transform:translate(-50%,_-50%)_rotate(45deg)]',
    '[.puppet-editor_&]:cursor-pointer',
    "[.puppet-editor_&[aria-pressed='true']]:[border-color:#fff0cf]",
    "[.puppet-editor_&[aria-pressed='true']]:[background:#ffbd59]",
    "[.puppet-editor_&[aria-pressed='true']]:[box-shadow:0_0_0_0.1875rem_rgb(255_189_89_/_18%)]",
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#fff0cf]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:0.1875rem]',
  ],
  'timeline-keyframe-add': [
    '[.puppet-editor_&]:[padding:0.3125rem_0.5625rem] [.puppet-editor_&]:[border:0.0625rem_solid_#3d5f56]',
    '[.puppet-editor_&]:[border-radius:0.375rem] [.puppet-editor_&]:[color:#bfeee1]',
    '[.puppet-editor_&]:[background:#17211e] [.puppet-editor_&]:[font-size:0.625rem]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&]:[color:#d9e3df] [.puppet-editor_&]:[border-color:#46534f]',
    '[.puppet-editor_&]:[background:#19201e]',
    '[.puppet-editor_&:disabled]:[opacity:0.42] [.puppet-editor_&:disabled]:cursor-not-allowed',
  ],
  'timeline-keyframe-delete': [
    '[.puppet-editor_&]:[padding:0.3125rem_0.5625rem] [.puppet-editor_&]:[border:0.0625rem_solid_#3d5f56]',
    '[.puppet-editor_&]:[border-radius:0.375rem] [.puppet-editor_&]:[color:#bfeee1]',
    '[.puppet-editor_&]:[background:#17211e] [.puppet-editor_&]:[font-size:0.625rem]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&]:[border-color:#66403e] [.puppet-editor_&]:[color:#ffc5c0]',
    '[.puppet-editor_&]:[background:#241817]',
    '[.puppet-editor_&:disabled]:[opacity:0.42] [.puppet-editor_&:disabled]:cursor-not-allowed',
  ],
  'timeline-label': [
    '[.puppet-editor_&_span]:[color:#74817d] [.puppet-editor_&_span]:[font-size:0.5625rem]',
    '[.puppet-editor_&_span]:font-bold [.puppet-editor_&_span]:[letter-spacing:0.12rem]',
    '[.puppet-editor_&_span]:[text-transform:uppercase]',
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[gap:0.1875rem]',
    '[.puppet-editor_&_strong]:[font-size:0.75rem]',
  ],
  'timeline-playback': [
    '[.puppet-editor_&]:[padding:0.3125rem_0.5625rem] [.puppet-editor_&]:[border:0.0625rem_solid_#3d5f56]',
    '[.puppet-editor_&]:[border-radius:0.375rem] [.puppet-editor_&]:[color:#bfeee1]',
    '[.puppet-editor_&]:[background:#17211e] [.puppet-editor_&]:[font-size:0.625rem]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&:disabled]:[opacity:0.42] [.puppet-editor_&:disabled]:cursor-not-allowed',
  ],
  'timeline-row': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:[min-width:40rem]',
    '[.puppet-editor_&]:editor-timeline-grid',
    '[.puppet-editor_&]:[background-size:calc(100%_/_var(--timeline-frame-count))_100%,_12.5%_100%]',
    '[.puppet-editor_&]:[height:2.375rem] [.puppet-editor_&]:[border-bottom:0.0625rem_solid_#222b28]',
    '[.puppet-editor_&]:[background-color:#0f1412]',
  ],
  'timeline-row-label': [
    '[.puppet-editor_&]:[border-right:0.0625rem_solid_#313a37]',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d] [.puppet-editor_&]:[background:#121816]',
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[height:2.375rem]',
    '[.puppet-editor_&]:[grid-template-columns:minmax(0,_1fr)_4rem] [.puppet-editor_&]:[gap:0.5rem]',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:[align-content:center]',
    '[.puppet-editor_&]:[padding:0_0.875rem]',
    '[.puppet-editor_&_>_span]:[color:#6f7d78] [.puppet-editor_&_>_span]:[font-size:0.5rem]',
    '[.puppet-editor_&_strong]:overflow-hidden [.puppet-editor_&_strong]:[color:#c5d0cc]',
    '[.puppet-editor_&_strong]:[font-size:0.625rem] [.puppet-editor_&_strong]:font-semibold',
    '[.puppet-editor_&_strong]:[text-overflow:ellipsis] [.puppet-editor_&_strong]:whitespace-nowrap',
    '[.puppet-editor_&_input]:min-w-0 [.puppet-editor_&_input]:w-full',
    '[.puppet-editor_&_input]:[padding:0.25rem_0.375rem]',
    '[.puppet-editor_&_input]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_input]:[border-radius:0.3125rem] [.puppet-editor_&_input]:[color:#d7e1dd]',
    '[.puppet-editor_&_input]:[background:#171e1b]',
    "[.puppet-editor_&_input]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[.puppet-editor_&_input]:[font-size:0.5625rem]',
    '[.puppet-editor_&_input:focus-visible]:[border-color:#64e5c4]',
    '[.puppet-editor_&_input:focus-visible]:[outline:none]',
  ],
  'timeline-row-playhead': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0] [.puppet-editor_&]:[bottom:0]',
    '[.puppet-editor_&]:[width:0.0625rem] [.puppet-editor_&]:[background:#ffbd59]',
    '[.puppet-editor_&]:pointer-events-none',
  ],
  'timeline-ruler': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:[min-width:40rem]',
    '[.puppet-editor_&]:editor-timeline-grid',
    '[.puppet-editor_&]:[background-size:calc(100%_/_var(--timeline-frame-count))_100%,_12.5%_100%]',
    '[.puppet-editor_&]:[height:2rem] [.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d]',
    '[.puppet-editor_&]:[background-color:#101513]',
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:absolute',
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:[top:0.5rem]',
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:[color:#788580]',
    "[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:[font-size:0.5rem]',
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:[transform:translateX(-50%)]',
    '[.puppet-editor_&_>_span:first-child]:[transform:none]',
    '[.puppet-editor_&_>_span:nth-child(9)]:[transform:translateX(-100%)]',
    '[.puppet-editor_&_input]:absolute [.puppet-editor_&_input]:[inset:0] [.puppet-editor_&_input]:w-full',
    '[.puppet-editor_&_input]:h-full [.puppet-editor_&_input]:m-0 [.puppet-editor_&_input]:[opacity:0]',
    '[.puppet-editor_&_input]:[cursor:ew-resize]',
    '[.puppet-editor_&_input:disabled]:cursor-not-allowed',
  ],
  'timeline-ruler-label': [
    '[.puppet-editor_&]:[border-right:0.0625rem_solid_#313a37]',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d] [.puppet-editor_&]:[background:#121816]',
    '[.puppet-editor_&]:flex [.puppet-editor_&]:[height:2rem] [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:[padding:0_0.875rem] [.puppet-editor_&]:[color:#788580]',
    '[.puppet-editor_&]:[font-size:0.5625rem] [.puppet-editor_&]:font-bold',
    '[.puppet-editor_&]:[letter-spacing:0.08rem] [.puppet-editor_&]:[text-transform:uppercase]',
  ],
  'timeline-ruler-playhead': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0] [.puppet-editor_&]:[bottom:0]',
    '[.puppet-editor_&]:[width:0.0625rem] [.puppet-editor_&]:[background:#ffbd59]',
    '[.puppet-editor_&]:pointer-events-none',
    '[.puppet-editor_&::before]:absolute [.puppet-editor_&::before]:[top:0]',
    '[.puppet-editor_&::before]:[left:50%] [.puppet-editor_&::before]:[width:0.4375rem]',
    '[.puppet-editor_&::before]:[height:0.4375rem] [.puppet-editor_&::before]:[border-radius:50%]',
    "[.puppet-editor_&::before]:[background:#ffbd59] [.puppet-editor_&::before]:[content:'']",
    '[.puppet-editor_&::before]:[transform:translateX(-50%)]',
  ],
  'timeline-time': [
    '[.puppet-editor_&]:[justify-self:end] [.puppet-editor_&]:[color:#7f8d88]',
    "[.puppet-editor_&]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[.puppet-editor_&]:[font-size:0.625rem]',
  ],
  'timeline-toolbar': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[grid-template-columns:11.25rem_minmax(0,_1fr)_6.875rem]',
    '[.puppet-editor_&]:[gap:0.875rem] [.puppet-editor_&]:items-center [.puppet-editor_&]:[min-height:3.625rem]',
    '[.puppet-editor_&]:[padding:0.5625rem_1rem] [.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d]',
  ],
}
