export const propertiesShortcuts = {
  'editor-number-field': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:flex [.puppet-editor_&]:box-border',
    '[.puppet-editor_&]:w-full [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:overflow-hidden [.puppet-editor_&]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&]:[border-radius:0.3125rem] [.puppet-editor_&]:[color:#dfe8e4]',
    '[.puppet-editor_&]:[background:#121816]',
    '[.puppet-editor_&[data-bounded]::before]:absolute',
    '[.puppet-editor_&[data-bounded]::before]:[inset:0_auto_0_0]',
    '[.puppet-editor_&[data-bounded]::before]:[width:var(--number-field-progress)]',
    '[.puppet-editor_&[data-bounded]::before]:[background:#24443b]',
    "[.puppet-editor_&[data-bounded]::before]:[content:'']",
    '[.puppet-editor_&[data-bounded]::before]:pointer-events-none',
    '[.puppet-editor_&:focus-within]:[border-color:#64e5c4]',
    '[.puppet-editor_&:focus-within]:[outline:0.0625rem_solid_#64e5c4]',
    '[.puppet-editor_&:focus-within]:[outline-offset:0.0625rem]',
    '[.puppet-editor_&:has(input:disabled)]:[border-color:#303936]',
    '[.puppet-editor_&:has(input:disabled)]:[color:#77837e]',
    '[.puppet-editor_&:has(input:disabled)]:[background:#111613]',
    "[.puppet-editor_&_>_input[type='number']]:relative [.puppet-editor_&_>_input[type='number']]:w-full",
    "[.puppet-editor_&_>_input[type='number']]:min-w-0 [.puppet-editor_&_>_input[type='number']]:[flex:1]",
    "[.puppet-editor_&_>_input[type='number']]:[padding:0.3125rem_0.4375rem]",
    "[.puppet-editor_&_>_input[type='number']]:[border:0]",
    "[.puppet-editor_&_>_input[type='number']]:[border-radius:0]",
    "[.puppet-editor_&_>_input[type='number']]:[outline:0]",
    "[.puppet-editor_&_>_input[type='number']]:[color:inherit]",
    "[.puppet-editor_&_>_input[type='number']]:[background:transparent]",
    "[.puppet-editor_&_>_input[type='number']]:[font:inherit]",
    "[.puppet-editor_&_>_input[type='number']]:[cursor:ew-resize]",
    "[.puppet-editor_&_>_input[type='number']]:[appearance:textfield]",
    "[.puppet-editor_&_>_input[type='number']]:touch-none",
    "[.puppet-editor_&_>_input[type='number']:focus:not(:active)]:[cursor:text]",
    "[.puppet-editor_&.scrubbing_>_input[type='number']]:[cursor:ew-resize]",
    "[.puppet-editor_&.scrubbing_>_input[type='number']]:select-none",
    "[.puppet-editor_&_>_input[type='number']::-webkit-inner-spin-button]:m-0",
    "[.puppet-editor_&_>_input[type='number']::-webkit-inner-spin-button]:[appearance:none]",
    "[.puppet-editor_&_>_input[type='number']::-webkit-outer-spin-button]:m-0",
    "[.puppet-editor_&_>_input[type='number']::-webkit-outer-spin-button]:[appearance:none]",
    '[.puppet-editor_&_>_span]:relative [.puppet-editor_&_>_span]:[padding-right:0.4375rem]',
    '[.puppet-editor_&_>_span]:[color:#81908a]',
    "[.puppet-editor_&_>_span]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[.puppet-editor_&_>_span]:[font-size:0.5625rem] [.puppet-editor_&_>_span]:pointer-events-none',
  ],
  'editor-number-step': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:grid [.puppet-editor_&]:[width:1.25rem]',
    '[.puppet-editor_&]:[align-self:stretch] [.puppet-editor_&]:[flex:0_0_1.25rem]',
    '[.puppet-editor_&]:place-items-center [.puppet-editor_&]:p-0 [.puppet-editor_&]:[border:0]',
    '[.puppet-editor_&]:[border-radius:0] [.puppet-editor_&]:[color:#91a19a]',
    '[.puppet-editor_&]:[background:#18201d] [.puppet-editor_&]:[font:inherit]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&.decrement]:[border-right:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&.increment]:[border-left:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&:hover:not(:disabled)]:[color:#dffff6]',
    '[.puppet-editor_&:hover:not(:disabled)]:[background:#29443b]',
    '[.puppet-editor_&:focus-visible]:[outline:0.0625rem_solid_#64e5c4]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:-0.125rem]',
    '[.puppet-editor_&:disabled]:[color:#4b5752] [.puppet-editor_&:disabled]:cursor-default',
    '[.puppet-editor_&_>_span]:box-border [.puppet-editor_&_>_span]:[width:0.5rem]',
    '[.puppet-editor_&_>_span]:[height:0.5rem]',
    '[.puppet-editor_&_>_span]:[border-right:0.125rem_solid_currentColor]',
    '[.puppet-editor_&_>_span]:[border-bottom:0.125rem_solid_currentColor]',
    '[.puppet-editor_&_>_span]:[font-size:0] [.puppet-editor_&_>_span]:pointer-events-none',
    '[.puppet-editor_&.decrement_>_span]:[transform:rotate(135deg)]',
    '[.puppet-editor_&.increment_>_span]:[transform:rotate(-45deg)]',
  ],
  'inspector-panel': [
    '[.puppet-editor_&]:[grid-area:inspector] [.puppet-editor_&]:overflow-y-auto',
    '[.puppet-editor_&]:[overscroll-behavior:contain] [.puppet-editor_&]:[scrollbar-gutter:stable]',
    '[.puppet-editor_&]:[border-left:0.0625rem_solid_#27302d]',
  ],
  'mask-action-button': [
    '[.puppet-editor_&]:[min-height:1.75rem] [.puppet-editor_&]:[padding:0.3125rem_0.4375rem]',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#3d5f56] [.puppet-editor_&]:[border-radius:0.375rem]',
    '[.puppet-editor_&]:[color:#bfeee1] [.puppet-editor_&]:[background:#17211e]',
    '[.puppet-editor_&]:[font:inherit] [.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&:hover:not(:disabled)]:[border-color:#64e5c4]',
    '[.puppet-editor_&:hover:not(:disabled)]:[outline:none]',
    '[.puppet-editor_&:focus-visible]:[border-color:#64e5c4] [.puppet-editor_&:focus-visible]:[outline:none]',
    '[.puppet-editor_&:disabled]:[opacity:0.42] [.puppet-editor_&:disabled]:cursor-not-allowed',
  ],
  'mask-actions': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[grid-template-columns:minmax(0,_1fr)]',
    '[.puppet-editor_&]:[gap:0.3125rem]',
  ],
  'mask-chip': [
    '[.puppet-editor_&]:[display:inline-grid] [.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&]:[grid-template-columns:1.25rem_minmax(0,_1fr)_1.25rem] [.puppet-editor_&]:[gap:0.25rem]',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:[padding:0.125rem]',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#3d5f56] [.puppet-editor_&]:[border-radius:0.375rem]',
    '[.puppet-editor_&]:[color:#d9eee8] [.puppet-editor_&]:[background:#17231f]',
    '[.puppet-editor_&]:[font-size:0.5625rem]',
    '[.puppet-editor_&_>_span]:overflow-hidden [.puppet-editor_&_>_span]:[text-overflow:ellipsis]',
    '[.puppet-editor_&_>_span]:whitespace-nowrap',
    '[.puppet-editor_&_img]:[width:1.25rem] [.puppet-editor_&_img]:[height:1.25rem]',
    '[.puppet-editor_&_img]:[border-radius:0.25rem] [.puppet-editor_&_img]:[background:#25312d]',
    '[.puppet-editor_&_img]:[object-fit:contain]',
    '[.puppet-editor_&_button]:grid [.puppet-editor_&_button]:[width:1.25rem]',
    '[.puppet-editor_&_button]:[height:1.25rem] [.puppet-editor_&_button]:p-0',
    '[.puppet-editor_&_button]:place-items-center [.puppet-editor_&_button]:[border:0]',
    '[.puppet-editor_&_button]:[border-radius:0.25rem] [.puppet-editor_&_button]:[color:#93a29d]',
    '[.puppet-editor_&_button]:[background:transparent] [.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button:hover:not(:disabled)]:[color:#f4f8f6]',
    '[.puppet-editor_&_button:hover:not(:disabled)]:[background:#293832]',
    '[.puppet-editor_&_button:hover:not(:disabled)]:[outline:none]',
    '[.puppet-editor_&_button:focus-visible]:[color:#f4f8f6]',
    '[.puppet-editor_&_button:focus-visible]:[background:#293832]',
    '[.puppet-editor_&_button:focus-visible]:[outline:none]',
    '[.puppet-editor_&_button:disabled]:[opacity:0.42] [.puppet-editor_&_button:disabled]:cursor-not-allowed',
  ],
  'mask-chip-list': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:[min-height:1.75rem] [.puppet-editor_&]:flex-wrap',
    '[.puppet-editor_&]:[gap:0.3125rem] [.puppet-editor_&]:items-center',
  ],
  'mask-empty-state': [
    '[.puppet-editor_&]:[color:#84918c] [.puppet-editor_&]:[font-size:0.5625rem]',
  ],
  'mask-pick-notice': [
    '[.puppet-editor_&]:[margin:0_0_0.5rem] [.puppet-editor_&]:[padding:0.4375rem_0.5rem]',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#3d5f56] [.puppet-editor_&]:[border-radius:0.375rem]',
    '[.puppet-editor_&]:[color:#c7f7e9] [.puppet-editor_&]:[background:#173029]',
    '[.puppet-editor_&]:[font-size:0.5625rem]',
  ],
  'mask-picker': [
    '[.puppet-editor_&]:[width:min(18.75rem,_calc(100vw_-_1.5rem))] [.puppet-editor_&]:[padding:0.625rem]',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#45544f] [.puppet-editor_&]:[border-radius:0.5625rem]',
    '[.puppet-editor_&]:[color:#dfe8e4] [.puppet-editor_&]:[background:#111816]',
    '[.puppet-editor_&]:[box-shadow:0_0.75rem_2.125rem_rgb(0_0_0_/_42%)]',
  ],
  'mask-picker-count': [
    '[.puppet-editor_&]:[color:#84918c] [.puppet-editor_&]:[font-size:0.5625rem]',
  ],
  'mask-picker-empty': [
    '[.puppet-editor_&]:[color:#84918c] [.puppet-editor_&]:[font-size:0.5625rem]',
  ],
  'mask-picker-heading': [
    '[.puppet-editor_&_button]:grid [.puppet-editor_&_button]:[width:1.25rem]',
    '[.puppet-editor_&_button]:[height:1.25rem] [.puppet-editor_&_button]:p-0',
    '[.puppet-editor_&_button]:place-items-center [.puppet-editor_&_button]:[border:0]',
    '[.puppet-editor_&_button]:[border-radius:0.25rem] [.puppet-editor_&_button]:[color:#93a29d]',
    '[.puppet-editor_&_button]:[background:transparent] [.puppet-editor_&_button]:cursor-pointer',
    '[.puppet-editor_&_button:hover]:[color:#f4f8f6] [.puppet-editor_&_button:hover]:[background:#293832]',
    '[.puppet-editor_&_button:hover]:[outline:none]',
    '[.puppet-editor_&_button:focus-visible]:[color:#f4f8f6]',
    '[.puppet-editor_&_button:focus-visible]:[background:#293832]',
    '[.puppet-editor_&_button:focus-visible]:[outline:none]',
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:justify-between',
    '[.puppet-editor_&]:[margin-bottom:0.5rem]',
    '[.puppet-editor_&_h2]:m-0 [.puppet-editor_&_h2]:[color:#dfe8e4]',
    '[.puppet-editor_&_h2]:[font-size:0.6875rem]',
  ],
  'mask-picker-label': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[gap:0.0625rem]',
    '[.puppet-editor_&_strong]:overflow-hidden [.puppet-editor_&_strong]:[text-overflow:ellipsis]',
    '[.puppet-editor_&_strong]:whitespace-nowrap',
    '[.puppet-editor_&_small]:overflow-hidden [.puppet-editor_&_small]:[text-overflow:ellipsis]',
    '[.puppet-editor_&_small]:whitespace-nowrap',
    '[.puppet-editor_&_strong]:[font-size:0.625rem]',
    '[.puppet-editor_&_small]:[color:#82908b] [.puppet-editor_&_small]:[font-size:0.5rem]',
  ],
  'mask-picker-list': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[max-height:13.75rem] [.puppet-editor_&]:[gap:0.1875rem]',
    '[.puppet-editor_&]:[margin:0.5rem_0] [.puppet-editor_&]:overflow-y-auto',
    '[.puppet-editor_&_label]:grid [.puppet-editor_&_label]:min-w-0',
    '[.puppet-editor_&_label]:[grid-template-columns:auto_1.5rem_minmax(0,_1fr)_auto]',
    '[.puppet-editor_&_label]:[gap:0.375rem] [.puppet-editor_&_label]:items-center',
    '[.puppet-editor_&_label]:[padding:0.3125rem] [.puppet-editor_&_label]:[border-radius:0.375rem]',
    '[.puppet-editor_&_label]:[color:#cbd7d3] [.puppet-editor_&_label]:cursor-pointer',
    '[.puppet-editor_&_label:hover]:[background:#1c2824]',
    '[.puppet-editor_&_label:has(input:disabled)]:[opacity:0.42]',
    '[.puppet-editor_&_label:has(input:disabled)]:cursor-not-allowed',
  ],
  'mask-picker-reason': [
    '[.puppet-editor_&]:[color:#82908b] [.puppet-editor_&]:[font-size:0.5rem]',
  ],
  'mask-picker-thumbnail': [
    '[.puppet-editor_&]:[width:1.25rem] [.puppet-editor_&]:[height:1.25rem]',
    '[.puppet-editor_&]:[border-radius:0.25rem] [.puppet-editor_&]:[background:#25312d]',
    '[.puppet-editor_&]:[object-fit:contain]',
    '[.puppet-editor_&]:grid [.puppet-editor_&]:place-items-center [.puppet-editor_&]:overflow-hidden',
    '[.puppet-editor_&_img]:block [.puppet-editor_&_img]:w-full [.puppet-editor_&_img]:h-full',
    '[.puppet-editor_&_img]:[object-fit:contain]',
  ],
  'mask-usage-count': [
    '[.puppet-editor_&]:[color:#84918c] [.puppet-editor_&]:[font-size:0.5625rem]',
  ],
  'part-mask-properties': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[gap:0.375rem] [.puppet-editor_&]:[margin:0.125rem_0_0]',
    '[.puppet-editor_&]:[padding:0.5rem] [.puppet-editor_&]:[border:0.0625rem_solid_#2a3430]',
    '[.puppet-editor_&]:[border-radius:0.375rem]',
    '[.puppet-editor_&_label]:[grid-template-columns:auto_minmax(0,_1fr)]',
  ],
  'puppet-layer-mask-usage': [
    '[.puppet-editor_&]:inline-flex [.puppet-editor_&]:[min-width:1.625rem] [.puppet-editor_&]:[gap:0.125rem]',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:justify-center [.puppet-editor_&]:[margin-left:auto]',
    '[.puppet-editor_&]:[padding:0.125rem_0.25rem] [.puppet-editor_&]:[border:0.0625rem_solid_#3d5f56]',
    '[.puppet-editor_&]:[border-radius:62.4375rem] [.puppet-editor_&]:[color:#9fe7d4]',
    '[.puppet-editor_&]:[background:#14231f] [.puppet-editor_&]:[font-size:0.5rem]',
    '[.puppet-editor_&_svg]:[width:0.625rem] [.puppet-editor_&_svg]:[height:0.625rem]',
    '[.puppet-editor_&_svg]:fill-none [.puppet-editor_&_svg]:[stroke:currentcolor]',
  ],
}
