export const storyShortcuts = {
  'puppet-context-menu-demo': [
    '[display:grid]',
    '[min-height:11.25rem]',
    '[place-items:center]',
    '[border:0.0625rem_dashed_#3d5f56]',
    '[border-radius:0.5625rem]',
    '[color:#b9c5c0]',
    '[background:#0d1210]',
    'text-editor-reading',
  ],
  'puppet-control-row': [
    '[display:flex]',
    '[flex-wrap:wrap]',
    '[align-items:center]',
    'gap-editor-group',
    'p-editor-section',
    '[border:0.0625rem_solid_#27302d]',
    '[border-radius:0.625rem]',
    '[background:#101513]',
    '[&_.panel-resizer]:[width:5rem]',
    '[&_.panel-resizer]:[height:0.375rem]',
  ],
  'puppet-design-language': [
    'editor-type-root',
    '[min-height:100vh]',
    'p-editor-reading',
    '[color:#edf4f0]',
    '[background:#0b0f0e]',
    '[&_header]:[max-width:45rem]',
    '[&_header]:mb-editor-reading',
    '[&_header_span]:[color:#64e5c4]',
    '[&_header_span]:text-editor-body',
    '[&_header_span]:[font-weight:700]',
    '[&_header_span]:[letter-spacing:0.14rem]',
    '[&_header_span]:[text-transform:uppercase]',
    '[&_h1]:mx-0 [&_h1]:mt-editor-field [&_h1]:mb-editor-field',
    '[&_h1]:editor-type-document-title',
    '[&_h1]:[letter-spacing:-0.03rem]',
    '[&_header_p]:m-0',
    '[&_header_p]:[color:#a7b3af]',
    '[&_header_p]:text-editor-reading',
    '[&_header_p]:[line-height:1.65]',
    '[&_article_p]:m-0',
    '[&_article_p]:[color:#a7b3af]',
    '[&_article_p]:text-editor-reading',
    '[&_article_p]:[line-height:1.65]',
  ],
  'puppet-design-section': [
    '[&_+_.puppet-design-section]:mt-editor-reading',
    '[&_h2]:m-0 [&_h2]:mb-editor-group',
    '[&_h2]:[color:#b9c5c0]',
    '[&_h2]:text-editor-reading',
    '[&_h2]:[letter-spacing:0.12rem]',
    '[&_h2]:[text-transform:uppercase]',
  ],
  'puppet-editor-story': [
    '[width:100%]',
    '[height:min(53.75rem,_calc(100vh_-_2rem))]',
    '[min-height:40rem]',
    '[overflow:auto]',
  ],
  'puppet-principle-grid': [
    '[display:grid]',
    '[grid-template-columns:repeat(auto-fit,_minmax(10rem,_1fr))]',
    'gap-editor-group',
    '[&_article]:[overflow:hidden]',
    '[&_article]:[border:0.0625rem_solid_#27302d]',
    '[&_article]:[border-radius:0.625rem]',
    '[&_article]:[background:#101513]',
    '[&_article]:p-editor-group',
    '[&_strong]:[display:block]',
    '[&_strong]:mb-editor-related',
    '[&_strong]:text-editor-reading',
  ],
  'puppet-spacing-sample': [
    'flex my-editor-field',
    '[&_span]:w-4 [&_span]:h-4 [&_span]:rounded-sm [&_span]:bg-[#64e5c4]',
  ],
  'puppet-story-narrow': ['[max-width:47.5rem]'],
  'puppet-story-surface': [
    '[&.puppet-editor]:[display:block]',
    '[&.puppet-editor]:[width:100%]',
    '[&.puppet-editor]:[min-width:0]',
    '[&.puppet-editor]:[height:auto]',
    '[&.puppet-editor]:[min-height:0]',
    '[&.puppet-editor]:p-editor-reading',
    '[&.puppet-editor]:[border:0.0625rem_solid_#27302d]',
    '[&.puppet-editor]:[border-radius:0.75rem]',
  ],
  'puppet-swatch': [
    '[overflow:hidden]',
    '[border:0.0625rem_solid_#27302d]',
    '[border-radius:0.625rem]',
    '[background:#101513]',
    '[&_strong]:[display:block]',
    '[&_strong]:mb-editor-related',
    '[&_strong]:text-editor-reading',
    '[&_code]:[color:#7f8d88]',
    '[&_code]:text-editor-body',
  ],
  'puppet-swatch-body': ['p-editor-group'],
  'puppet-swatch-color': ['[height:4.5rem]', '[background:var(--puppet-swatch-color)]'],
  'puppet-swatch-grid': [
    '[display:grid]',
    '[grid-template-columns:repeat(auto-fit,_minmax(10rem,_1fr))]',
    'gap-editor-group',
  ],
}
