export const storyShortcuts = {
  'puppet-context-menu-demo': [
    '[display:grid]',
    '[min-height:11.25rem]',
    '[place-items:center]',
    '[border:0.0625rem_dashed_#3d5f56]',
    '[border-radius:0.5625rem]',
    '[color:#b9c5c0]',
    '[background:#0d1210]',
    '[font-size:0.8125rem]',
  ],
  'puppet-control-row': [
    '[display:flex]',
    '[flex-wrap:wrap]',
    '[align-items:center]',
    '[gap:0.75rem]',
    '[padding:1.25rem]',
    '[border:0.0625rem_solid_#27302d]',
    '[border-radius:0.625rem]',
    '[background:#101513]',
    '[&_.panel-resizer]:[width:5rem]',
    '[&_.panel-resizer]:[height:0.375rem]',
  ],
  'puppet-design-language': [
    '[min-height:100vh]',
    '[padding:2.5rem]',
    '[color:#edf4f0]',
    '[background:#0b0f0e]',
    "[font-family:Inter,_ui-sans-serif,_system-ui,_-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_sans-serif]",
    '[&_header]:[max-width:45rem]',
    '[&_header]:[margin-bottom:2.25rem]',
    '[&_header_span]:[color:#64e5c4]',
    '[&_header_span]:[font-size:0.6875rem]',
    '[&_header_span]:[font-weight:700]',
    '[&_header_span]:[letter-spacing:0.14rem]',
    '[&_header_span]:[text-transform:uppercase]',
    '[&_h1]:[margin:0.625rem_0_0.5rem]',
    '[&_h1]:[font-size:2rem]',
    '[&_h1]:[letter-spacing:-0.03rem]',
    '[&_header_p]:[margin:0]',
    '[&_header_p]:[color:#a7b3af]',
    '[&_header_p]:[font-size:0.875rem]',
    '[&_header_p]:[line-height:1.65]',
    '[&_article_p]:[margin:0]',
    '[&_article_p]:[color:#a7b3af]',
    '[&_article_p]:[font-size:0.875rem]',
    '[&_article_p]:[line-height:1.65]',
  ],
  'puppet-design-section': [
    '[&_+_.puppet-design-section]:[margin-top:2rem]',
    '[&_h2]:[margin:0_0_0.875rem]',
    '[&_h2]:[color:#b9c5c0]',
    '[&_h2]:[font-size:0.75rem]',
    '[&_h2]:[letter-spacing:0.12rem]',
    '[&_h2]:[text-transform:uppercase]',
  ],
  'puppet-editor-story': [
    '[width:100%]',
    '[height:min(53.75rem,_calc(100vh_-_2rem))]',
    '[min-height:40rem]',
    '[overflow:auto]',
  ],
  'puppet-principle-grid': [
    '[display:grid]',
    '[grid-template-columns:repeat(auto-fit,_minmax(10rem,_1fr))]',
    '[gap:0.75rem]',
    '[&_article]:[overflow:hidden]',
    '[&_article]:[border:0.0625rem_solid_#27302d]',
    '[&_article]:[border-radius:0.625rem]',
    '[&_article]:[background:#101513]',
    '[&_article]:[padding:0.875rem]',
    '[&_strong]:[display:block]',
    '[&_strong]:[margin-bottom:0.3125rem]',
    '[&_strong]:[font-size:0.8125rem]',
  ],
  'puppet-story-narrow': ['[max-width:47.5rem]'],
  'puppet-story-surface': [
    '[&.puppet-editor]:[display:block]',
    '[&.puppet-editor]:[width:100%]',
    '[&.puppet-editor]:[min-width:0]',
    '[&.puppet-editor]:[height:auto]',
    '[&.puppet-editor]:[min-height:0]',
    '[&.puppet-editor]:[padding:1.5rem]',
    '[&.puppet-editor]:[border:0.0625rem_solid_#27302d]',
    '[&.puppet-editor]:[border-radius:0.75rem]',
  ],
  'puppet-swatch': [
    '[overflow:hidden]',
    '[border:0.0625rem_solid_#27302d]',
    '[border-radius:0.625rem]',
    '[background:#101513]',
    '[&_strong]:[display:block]',
    '[&_strong]:[margin-bottom:0.3125rem]',
    '[&_strong]:[font-size:0.8125rem]',
    '[&_code]:[color:#7f8d88]',
    '[&_code]:[font-size:0.6875rem]',
  ],
  'puppet-swatch-body': ['[padding:0.875rem]'],
  'puppet-swatch-color': ['[height:4.5rem]', '[background:var(--puppet-swatch-color)]'],
  'puppet-swatch-grid': [
    '[display:grid]',
    '[grid-template-columns:repeat(auto-fit,_minmax(10rem,_1fr))]',
    '[gap:0.75rem]',
  ],
}
