export const timelineShortcuts = {
  timeline: [
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[max-width:100cqw]',
    '[.puppet-editor_&]:[grid-area:timeline] [.puppet-editor_&]:grid [.puppet-editor_&]:min-h-0',
    '[.puppet-editor_&]:[grid-template-rows:auto_minmax(0,_1fr)]',
    '[.puppet-editor_&]:[border-top:0.0625rem_solid_#27302d] [.puppet-editor_&]:[background:#111614]',
  ],
  'timeline-actions': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:gap-editor-group',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:flex-wrap',
  ],
  'timeline-compact-action': [
    '[.puppet-editor_&]:shrink-0',
    '[@container_timeline-toolbar_(max-width:_60rem)]:[.puppet-editor_&_.timeline-action-label]:hidden',
    [
      '[@container_timeline-toolbar_(max-width:_60rem)]:',
      '[.puppet-editor_&.editor-button]:[min-width:var(--editor-control-height)]',
    ].join(''),
    '[@container_timeline-toolbar_(max-width:_60rem)]:[.puppet-editor_&.editor-button]:px-editor-related',
  ],
  'timeline-control-group': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:gap-editor-related [.puppet-editor_&]:flex-wrap',
  ],
  'timeline-document-controls': ['[.puppet-editor_&]:gap-editor-field'],
  'timeline-dopesheet': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:min-h-0',
    '[.puppet-editor_&]:[grid-template-columns:13.75rem_minmax(0,_1fr)]',
    '[.puppet-editor_&]:[align-content:start] [.puppet-editor_&]:overflow-y-auto',
    '[.puppet-editor_&]:overflow-x-hidden',
  ],
  'timeline-easing': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:gap-editor-related',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:[color:#b9c5c0]',
    '[.puppet-editor_&]:text-editor-metadata [.puppet-editor_&]:whitespace-nowrap',
    '[.puppet-editor_&]:ml-editor-related',
    '[.puppet-editor_&_.editor-select-trigger]:[width:7rem]',
  ],
  'timeline-empty': [
    '[.puppet-editor_&]:[grid-column:1_/_-1] [.puppet-editor_&]:m-0 [.puppet-editor_&]:p-editor-section',
    '[.puppet-editor_&]:[color:#788580] [.puppet-editor_&]:text-editor-caption [.puppet-editor_&]:text-center',
  ],
  'timeline-keyframe': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:50%] [.puppet-editor_&]:[width:0.625rem]',
    '[.puppet-editor_&]:[height:0.625rem] [.puppet-editor_&]:p-0',
    '[.puppet-editor_&]:[border:0.0625rem_solid_#b8f5e5] [.puppet-editor_&]:[border-radius:0.0625rem]',
    '[.puppet-editor_&]:[background:#64e5c4] [.puppet-editor_&]:[transform:translate(-50%,_-50%)_rotate(45deg)]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&[data-draggable]]:cursor-grab [.puppet-editor_&[data-draggable]]:[touch-action:none]',
    '[.puppet-editor_&[data-dragging]]:cursor-grabbing',
    "[.puppet-editor_&[aria-pressed='true']]:[border-color:#fff0cf]",
    "[.puppet-editor_&[aria-pressed='true']]:[background:#ffbd59]",
    "[.puppet-editor_&[aria-pressed='true']]:[box-shadow:0_0_0_0.1875rem_rgb(255_189_89_/_18%)]",
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#fff0cf]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:0.1875rem]',
  ],
  'timeline-label': [
    '[.puppet-editor_&]:shrink-0 [.puppet-editor_&]:[color:#b9c5c0]',
    '[.puppet-editor_&]:editor-type-section',
  ],
  'timeline-labels': ['[.puppet-editor_&]:grid [.puppet-editor_&]:[align-content:start]'],
  'timeline-motion-add': [
    '[.puppet-editor_&]:shrink-0 [.puppet-editor_&]:[width:1.75rem] [.puppet-editor_&]:[height:1.75rem]',
    '[.puppet-editor_&]:grid [.puppet-editor_&]:place-items-center [.puppet-editor_&]:p-0',
    '[.puppet-editor_&_>_.puppet-icon]:[width:0.75rem] [.puppet-editor_&_>_.puppet-icon]:[height:0.75rem]',
  ],
  'timeline-motion-controls': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[max-width:12rem]',
    '[.puppet-editor_&]:[flex:0_1_12rem] [.puppet-editor_&]:[width:12rem]',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:gap-editor-related',
    '[.puppet-editor_&_>_div]:flex-1 [.puppet-editor_&_>_div]:min-w-0',
    '[.puppet-editor_&_.editor-select-trigger]:min-w-0 [.puppet-editor_&_.editor-select-trigger]:flex-1',
    '[.puppet-editor_&_button]:text-editor-caption [.puppet-editor_&_button]:[line-height:1rem]',
  ],
  'timeline-motion-group': [
    '[.puppet-editor_&]:min-w-0',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d]',
  ],
  'timeline-motion-group-heading': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:w-full',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:gap-editor-field',
    '[.puppet-editor_&]:[letter-spacing:normal] [.puppet-editor_&]:[text-transform:none]',
    '[.puppet-editor_&_.timeline-settings]:ml-auto [.puppet-editor_&_.timeline-settings]:flex-nowrap',
    '[.puppet-editor_&_.timeline-setting_.editor-number-field]:[width:5.5rem]',
  ],
  'timeline-motion-groups': ['[.puppet-editor_&]:min-h-0 [.puppet-editor_&]:overflow-auto'],
  'timeline-motion-manage': [
    '[.puppet-editor_&]:shrink-0 [.puppet-editor_&]:[width:1.75rem] [.puppet-editor_&]:[height:1.75rem]',
    '[.puppet-editor_&]:grid [.puppet-editor_&]:place-items-center [.puppet-editor_&]:p-0',
    '[.puppet-editor_&_span]:[transform:translateY(-0.1875rem)]',
  ],
  'timeline-motion-name': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:flex [.puppet-editor_&]:h-full [.puppet-editor_&]:flex-1',
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:items-center [.puppet-editor_&]:[padding:0_1.25rem_0_0]',
    '[.puppet-editor_&]:border-0 [.puppet-editor_&]:[color:#d7e1dd] [.puppet-editor_&]:bg-transparent',
    '[.puppet-editor_&]:cursor-grab [.puppet-editor_&]:text-left [.puppet-editor_&]:select-none',
    '[.puppet-editor_&_strong]:min-w-0 [.puppet-editor_&_strong]:overflow-hidden',
    '[.puppet-editor_&_strong]:text-editor-body [.puppet-editor_&_strong]:[text-overflow:ellipsis]',
    '[.puppet-editor_&_strong]:whitespace-nowrap',
    '[.puppet-editor_&:focus-visible]:[outline:0.125rem_solid_#64e5c4]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:-0.125rem]',
  ],
  'timeline-motion-name-delete': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:inset-y-0 [.puppet-editor_&]:right-0',
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[width:5rem] [.puppet-editor_&]:gap-editor-tight',
    '[.puppet-editor_&]:[align-content:center] [.puppet-editor_&]:[justify-items:center]',
    '[.puppet-editor_&]:[color:#f3aaa5] [.puppet-editor_&]:[background:#471f1d]',
    '[.puppet-editor_&]:text-editor-micro [.puppet-editor_&]:font-bold',
    '[.puppet-editor_&_.puppet-icon]:[width:0.75rem] [.puppet-editor_&_.puppet-icon]:[height:0.75rem]',
  ],
  'timeline-motion-name-editor': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:flex-1',
    '[.puppet-editor_&_input]:box-border [.puppet-editor_&_input]:w-full [.puppet-editor_&_input]:min-w-0',
    '[.puppet-editor_&_input]:[height:1.75rem] [.puppet-editor_&_input]:py-editor-related',
    '[.puppet-editor_&_input]:px-editor-field',
    '[.puppet-editor_&_input]:[border:0.0625rem_solid_#64e5c4]',
    '[.puppet-editor_&_input]:[border-radius:0.3125rem] [.puppet-editor_&_input]:[color:#f3f7f5]',
    '[.puppet-editor_&_input]:[background:#171e1b] [.puppet-editor_&_input]:text-editor-caption',
    '[.puppet-editor_&_span]:absolute [.puppet-editor_&_span]:[top:calc(100%_+_0.25rem)]',
    '[.puppet-editor_&_span]:left-0 [.puppet-editor_&_span]:whitespace-nowrap',
    '[.puppet-editor_&_span]:[color:#f3aaa5] [.puppet-editor_&_span]:text-editor-metadata',
  ],
  'timeline-motion-name-hint': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[right:0.25rem] [.puppet-editor_&]:[color:#596762]',
    '[.puppet-editor_&]:text-editor-caption',
  ],
  'timeline-motion-name-surface': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:flex [.puppet-editor_&]:h-full [.puppet-editor_&]:w-full',
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:items-center [.puppet-editor_&]:gap-editor-field',
    '[.puppet-editor_&]:bg-[#121916]',
    '[.puppet-editor_&]:[transform:translateX(calc(var(--timeline-motion-name-offset)_*_-1))]',
    '[.puppet-editor_&]:[transition:transform_160ms_ease-out]',
    '[.dragging_&]:[transition:none]',
  ],
  'timeline-motion-name-swipe': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:flex-1',
    '[.puppet-editor_&]:self-stretch [.puppet-editor_&]:overflow-hidden [.puppet-editor_&]:bg-[#351918]',
    '[.puppet-editor_&]:[touch-action:pan-y]',
    '[.puppet-editor_&.armed_.timeline-motion-name-delete]:[color:#fff1ef]',
    '[.puppet-editor_&.armed_.timeline-motion-name-delete]:[background:#a63f3a]',
    '[.puppet-editor_&.dragging_.timeline-motion-name]:cursor-grabbing',
  ],
  'timeline-parameter-picker-list': 'max-h-64 overflow-y-auto',
  'timeline-playback': [
    '[.puppet-editor_&]:[border-color:#3d5f56] [.puppet-editor_&]:[color:#bfeee1]',
    '[.puppet-editor_&]:[background:#17211e]',
  ],
  'timeline-row': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:w-full',
    '[.puppet-editor_&]:editor-timeline-grid',
    '[.puppet-editor_&]:[background-size:calc(100%_/_var(--timeline-frame-count))_100%,_12.5%_100%]',
    '[.puppet-editor_&]:[height:2.375rem] [.puppet-editor_&]:[border-bottom:0.0625rem_solid_#222b28]',
    '[.puppet-editor_&]:[background-color:#0f1412]',
    '[.puppet-editor_&[data-selected]]:[background-color:#17211e]',
    '[.puppet-editor_&[data-selected]]:[border-bottom-color:#3d5f56]',
    '[.puppet-editor_&]:focus-visible:[outline:0.125rem_solid_#8ed5be]',
    '[.puppet-editor_&]:focus-visible:[outline-offset:-0.125rem]',
  ],
  'timeline-row-label': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:[transform:translateX(var(--parameter-swipe-offset))]',
    '[.puppet-editor_&]:[transition:transform_160ms_ease-out]',
    '[.puppet-editor_&]:[border-right:0.0625rem_solid_#313a37]',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d] [.puppet-editor_&]:[background:#121816]',
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[height:2.375rem]',
    '[.puppet-editor_&]:[grid-template-columns:minmax(0,_1fr)_5.5rem] [.puppet-editor_&]:gap-editor-control',
    '[.puppet-editor_&]:items-center [.puppet-editor_&]:[align-content:center]',
    '[.puppet-editor_&]:py-0 [.puppet-editor_&]:px-editor-field',
    '[.puppet-editor_&_>_span]:[color:#6f7d78] [.puppet-editor_&_>_span]:text-editor-micro',
    '[.puppet-editor_&_strong]:overflow-hidden [.puppet-editor_&_strong]:[color:#c5d0cc]',
    '[.puppet-editor_&_strong]:text-editor-caption [.puppet-editor_&_strong]:font-semibold',
    '[.puppet-editor_&_strong]:[text-overflow:ellipsis] [.puppet-editor_&_strong]:whitespace-nowrap',
    '[.puppet-editor_&_strong]:cursor-pointer',
    '[.puppet-editor_&[data-selected]]:[background:#1a2925]',
    '[.puppet-editor_&[data-selected]]:[box-shadow:inset_0.1875rem_0_0_#64e5c4]',
    '[.puppet-editor_&[data-selected]_strong]:[color:#e8f0ed]',
    '[.puppet-editor_&_input]:min-w-0 [.puppet-editor_&_input]:w-full',
    '[.puppet-editor_&_input]:py-editor-related [.puppet-editor_&_input]:px-editor-control',
    '[.puppet-editor_&_input]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&_input]:[border-radius:0.3125rem] [.puppet-editor_&_input]:[color:#d7e1dd]',
    '[.puppet-editor_&_input]:[background:#171e1b]',
    '[.puppet-editor_&_input]:font-editor-mono',
    '[.puppet-editor_&_.editor-number-field]:text-editor-caption',
    "[.puppet-editor_&_.editor-number-field_>_input[type='number']]:text-editor-caption",
    '[.puppet-editor_&_input:focus-visible]:[border-color:#64e5c4]',
    '[.puppet-editor_&_input:focus-visible]:[outline:none]',
  ],
  'timeline-row-label-swipe': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:overflow-hidden',
    '[.puppet-editor_&]:[height:2.375rem] [.puppet-editor_&]:[touch-action:pan-y]',
    '[.puppet-editor_&]:[background:#351918]',
    '[.puppet-editor_&.armed_.timeline-row-swipe-delete]:[color:#fff1ef]',
    '[.puppet-editor_&.armed_.timeline-row-swipe-delete]:[background:#a63f3a]',
    '[.puppet-editor_&.dragging_.timeline-row-label]:[transition:none]',
  ],
  'timeline-row-playhead': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0] [.puppet-editor_&]:[bottom:0]',
    '[.puppet-editor_&]:[width:0.0625rem] [.puppet-editor_&]:[background:#ffbd59]',
    '[.puppet-editor_&]:pointer-events-none',
  ],
  'timeline-row-swipe-delete': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:inset-y-0 [.puppet-editor_&]:left-0',
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[width:5rem] [.puppet-editor_&]:gap-editor-tight',
    '[.puppet-editor_&]:[align-content:center] [.puppet-editor_&]:[justify-items:center]',
    '[.puppet-editor_&]:[color:#f3aaa5] [.puppet-editor_&]:[background:#471f1d]',
    '[.puppet-editor_&]:text-editor-micro [.puppet-editor_&]:font-bold',
    '[.puppet-editor_&_.puppet-icon]:[width:1rem] [.puppet-editor_&_.puppet-icon]:[height:1rem]',
  ],
  'timeline-ruler': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:w-full',
    '[.puppet-editor_&]:editor-timeline-grid',
    '[.puppet-editor_&]:[background-size:calc(100%_/_var(--timeline-frame-count))_100%,_12.5%_100%]',
    '[.puppet-editor_&]:[height:2rem] [.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d]',
    '[.puppet-editor_&]:[background-color:#101513]',
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:absolute',
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:[top:0.5rem]',
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:[color:#788580]',
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:font-editor-mono',
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:text-editor-micro',
    '[.puppet-editor_&_>_span:not(.timeline-ruler-playhead)]:[transform:translateX(-50%)]',
    '[.puppet-editor_&_>_span:first-child]:[transform:none]',
    '[.puppet-editor_&_>_span:nth-child(9)]:[transform:translateX(-100%)]',
    '[.puppet-editor_&_input]:absolute [.puppet-editor_&_input]:[inset:0] [.puppet-editor_&_input]:w-full',
    '[.puppet-editor_&_input]:h-full [.puppet-editor_&_input]:m-0 [.puppet-editor_&_input]:[opacity:0]',
    '[.puppet-editor_&_input]:[cursor:ew-resize]',
    '[.puppet-editor_&_input:disabled]:cursor-not-allowed',
  ],
  'timeline-ruler-label': [
    '[.puppet-editor_&]:[border-right:0.0625rem_solid_#313a37]',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d] [.puppet-editor_&]:[background:#121816]',
    '[.puppet-editor_&]:flex [.puppet-editor_&]:[height:2rem] [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:py-0 [.puppet-editor_&]:px-editor-group [.puppet-editor_&]:[color:#788580]',
    '[.puppet-editor_&]:text-editor-metadata [.puppet-editor_&]:font-bold',
    '[.puppet-editor_&]:[letter-spacing:0.08rem] [.puppet-editor_&]:[text-transform:uppercase]',
  ],
  'timeline-ruler-playhead': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0] [.puppet-editor_&]:[bottom:0]',
    '[.puppet-editor_&]:[width:0.0625rem] [.puppet-editor_&]:[background:#ffbd59]',
    '[.puppet-editor_&]:pointer-events-none',
    '[.puppet-editor_&::before]:absolute [.puppet-editor_&::before]:[top:0]',
    '[.puppet-editor_&::before]:[left:50%] [.puppet-editor_&::before]:[width:0.4375rem]',
    '[.puppet-editor_&::before]:[height:0.4375rem] [.puppet-editor_&::before]:[border-radius:50%]',
    "[.puppet-editor_&::before]:[background:#ffbd59] [.puppet-editor_&::before]:[content:'']",
    '[.puppet-editor_&::before]:[transform:translateX(-50%)]',
  ],
  'timeline-ruler-status': [
    '[.puppet-editor_&]:absolute [.puppet-editor_&]:[top:0.375rem] [.puppet-editor_&]:[right:0.75rem]',
    '[.puppet-editor_&]:py-editor-tight [.puppet-editor_&]:px-editor-related [.puppet-editor_&]:[color:#7f8d88]',
    '[.puppet-editor_&]:[background:#101513] [.puppet-editor_&]:text-editor-micro',
    '[.puppet-editor_&]:font-editor-mono',
    '[.puppet-editor_&]:pointer-events-none',
  ],
  'timeline-seek': 'absolute inset-0 touch-none',
  'timeline-seek-thumb':
    'absolute top-0 h-full w-2 opacity-0 focus-visible:opacity-100 outline outline-[#79d7b1]',
  'timeline-seek-track': 'relative w-full h-full',
  'timeline-setting': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:gap-editor-related',
    '[.puppet-editor_&_>_span:first-child]:[color:#84918c] [.puppet-editor_&_>_span:first-child]:text-editor-metadata',
    '[.puppet-editor_&_.editor-number-field]:[width:6.25rem]',
    '[.puppet-editor_&_.editor-number-field_input]:text-editor-caption',
  ],
  'timeline-settings': [
    '[.puppet-editor_&]:flex [.puppet-editor_&]:items-center [.puppet-editor_&]:gap-editor-field',
    '[.puppet-editor_&]:flex-wrap',
  ],
  'timeline-toolbar': [
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:[container-type:inline-size]',
    '[.puppet-editor_&]:[container-name:timeline-toolbar]',
    '[.puppet-editor_&]:py-editor-field [.puppet-editor_&]:px-editor-group',
    '[.puppet-editor_&]:[border-bottom:0.0625rem_solid_#27302d]',
  ],
  'timeline-tracks': [
    '[.puppet-editor_&]:grid [.puppet-editor_&]:[align-content:start]',
    '[.puppet-editor_&]:[width:calc(var(--timeline-frame-count)_*_0.75rem)]',
  ],
  'timeline-tracks-scroll': [
    '[.puppet-editor_&]:min-w-0 [.puppet-editor_&]:overflow-x-auto',
    '[.puppet-editor_&]:overflow-y-hidden',
  ],
}
