mutation authenticateUserWithCryptoSignature($input: AuthenticateUserWithCryptoSignatureInput!) {
  authenticateUserWithCryptoSignature(input: $input) {
    item {
      name
      id
      email
      postsCount
      postLikesCount
      followingCount
      followerCount
    },
    sessionToken
  }
}
