import {Show} from 'solid-js'
import {cx} from 'class-variance-authority'

import {SERVICE_POLICY_PATHS} from 'src/features/service-terms'

import {
  PServicePolicyDocument,
  type ServicePolicyContentsItem,
} from '../p-service-policy-document/PServicePolicyDocument'
import {
  CONTENT_LINK_CLASSES,
  HEADING_CLASSES,
  LIST_CLASSES,
  PARAGRAPH_CLASSES,
  type PServiceTermsProps,
  SECTION_CLASSES,
} from '../service-terms/shared'

const BUSINESS_INFORMATION_CLASSES = cx(
  'mb-0 mt-6 grid max-w-3xl gap-x-6 gap-y-2 rounded-4 border border-white/10',
  'bg-white/4 p-4 text-sm leading-6 text-#d8cbd9 sm:grid-cols-[auto_1fr]',
)
const EMPHASIS_CLASSES = 'font-750 text-#ffd4de'

const ENGLISH_OPERATOR = {
  address: '301-818, 11 Jagok-ro 11-gil, Gangnam-gu, Seoul, Republic of Korea',
  businessName: 'Kuwoong',
  representative: 'Bichi Kim',
} as const

const CONTENT_ITEMS = [
  {id: 'purpose', label: '1. Purpose and scope'},
  {id: 'definitions', label: '2. Definitions'},
  {id: 'agreement', label: '3. Effect and changes'},
  {id: 'service', label: '4. Service'},
  {id: 'platform', label: '5. Platform environment'},
  {id: 'account', label: '6. Accounts and user obligations'},
  {id: 'ai-voice', label: '7. AI voice features'},
  {id: 'restricted-uses', label: '8. Prohibited conduct'},
  {id: 'rights', label: '9. Content and rights'},
  {id: 'payment', label: '10. Paid services, payment, and refunds'},
  {id: 'availability', label: '11. Changes and suspension'},
  {id: 'termination', label: '12. Termination and restrictions'},
  {id: 'responsibility', label: '13. Liability'},
  {id: 'disputes', label: '14. Inquiries and disputes'},
] as const satisfies ReadonlyArray<ServicePolicyContentsItem>

// oxlint-disable-next-line eslint/max-lines-per-function -- Keep the legal document in reading order.
export const EnglishServiceTermsContent = (props: PServiceTermsProps) => {
  const isAppsInToss = () => props.platform === 'apps-in-toss'

  return (
    <PServicePolicyDocument
      backHref={props.backHref}
      backLabel={props.backLabel}
      businessInformation={
        <dl class={BUSINESS_INFORMATION_CLASSES}>
          <dt class="font-750 text-#f8edf1">Business name</dt>
          <dd class="m-0">{ENGLISH_OPERATOR.businessName}</dd>
          <dt class="font-750 text-#f8edf1">Representative</dt>
          <dd class="m-0">{ENGLISH_OPERATOR.representative}</dd>
          <dt class="font-750 text-#f8edf1">Business registration number</dt>
          <dd class="m-0">720-42-01404</dd>
          <dt class="font-750 text-#f8edf1">Mail-order business registration</dt>
          <dd class="m-0">
            Exempt because the previous year&apos;s mail-order transactions were fewer than 50
          </dd>
          <dt class="font-750 text-#f8edf1">Business address</dt>
          <dd class="m-0">{ENGLISH_OPERATOR.address}</dd>
          <dt class="font-750 text-#f8edf1">Customer support phone</dt>
          <dd class="m-0">070-5236-4741</dd>
          <dt class="font-750 text-#f8edf1">Customer support</dt>
          <dd class="m-0">
            <a class={CONTENT_LINK_CLASSES} href="mailto:info@pomofi.io">
              info@pomofi.io
            </a>
          </dd>
        </dl>
      }
      contents={CONTENT_ITEMS}
      contentsLabel="Terms of service contents"
      contentsTitle="Contents"
      currentPolicy="terms"
      description={
        <>
          These terms describe the rights and obligations that apply when using Pomofi&apos;s focus
          tools, content, and AI voice features.
        </>
      }
      eyebrow={isAppsInToss() ? 'Apps in Toss terms of service' : 'Web terms of service'}
      footer={
        <>
          <span>
            Terms inquiries:{' '}
            <a class={CONTENT_LINK_CLASSES} href="mailto:info@pomofi.io">
              info@pomofi.io
            </a>
          </span>
          <span>© Pomofi</span>
        </>
      }
      metadata={
        <p class="mb-0 mt-3 text-xs text-#a99cab">
          Effective date: August 22, 2026 · Document version 1.0
        </p>
      }
      notice={{
        description: (
          <>
            Do not use the voice features to infringe another person&apos;s rights or to conceal
            that audio was generated by AI. Check the cancellation and refund conditions for paid
            services before purchasing.
          </>
        ),
        title: 'Important usage conditions',
      }}
      platform={props.platform ?? 'web'}
      title="Pomofi terms of service"
    >
      <>
        <section class={SECTION_CLASSES} id="purpose">
          <h2 class={HEADING_CLASSES}>Article 1. Purpose and scope</h2>
          <p class={PARAGRAPH_CLASSES}>
            These terms set the conditions of use and the rights, obligations, and responsibilities
            between the individual business Kuwoong, represented by Bichi Kim, and people who use
            Pomofi. Operating policies and conditions for individual features shown in the service
            also apply together with these terms.
          </p>
        </section>

        <section class={SECTION_CLASSES} id="definitions">
          <h2 class={HEADING_CLASSES}>Article 2. Definitions</h2>
          <ul class={LIST_CLASSES}>
            <li>
              “Service” means Pomofi&apos;s focus tools, content, AI voice, and related features.
            </li>
            <li>“User” means a person who uses the service under these terms.</li>
            <li>
              “User content” means scripts, settings, audio, and other material that a user enters,
              stores, uploads, or creates through the service.
            </li>
            <li>
              “Platform” means the Apps in Toss or web environment where the service is provided.
            </li>
          </ul>
        </section>

        <section class={SECTION_CLASSES} id="agreement">
          <h2 class={HEADING_CLASSES}>Article 3. Effect and changes</h2>
          <p class={PARAGRAPH_CLASSES}>
            These terms are posted in the service so that users can review them easily. They apply
            when a user starts using the service or agrees to the terms.
          </p>
          <p class={PARAGRAPH_CLASSES}>
            We may revise the terms when applicable law, service features, or operating policies
            change. We announce the changes and effective date through the service before they take
            effect. Important or unfavorable changes are announced visibly with a reasonable notice
            period. A user may stop using the service if they do not agree to the changes.
          </p>
        </section>

        <section class={SECTION_CLASSES} id="service">
          <h2 class={HEADING_CLASSES}>Article 4. Service</h2>
          <p class={PARAGRAPH_CLASSES}>Pomofi may provide all or part of the following features.</p>
          <ul class={LIST_CLASSES}>
            <li>Pomodoro timer, focus scenes, music, and dialogue features</li>
            <li>On-device storage of focus history and user settings</li>
            <li>AI voice generation and playback based on text</li>
            <li>Other features announced in the service</li>
          </ul>
          <p class={PARAGRAPH_CLASSES}>
            How a feature works and its quality may vary depending on device performance, the
            operating system, browser, network conditions, or external service support.
          </p>
        </section>

        <section class={SECTION_CLASSES} id="platform">
          <h2 class={HEADING_CLASSES}>Article 5. Platform environment</h2>
          <Show
            fallback={
              <>
                <p class={PARAGRAPH_CLASSES}>
                  The web service is available at the web address and in the supported browsers
                  announced by Pomofi. The terms and policies of browser, operating-system, and
                  sign-in providers apply separately to their services.
                </p>
                <p class={PARAGRAPH_CLASSES}>
                  Some features or settings may not work correctly if browser storage, cookies, or
                  network access are blocked.
                </p>
              </>
            }
            when={isAppsInToss()}
          >
            <p class={PARAGRAPH_CLASSES}>
              The Apps in Toss service is provided in the mini-app environment inside the Toss app.
              The terms and policies set by Toss or the platform operator apply separately to the
              Toss account, Toss app, and Apps in Toss platform.
            </p>
            <p class={PARAGRAPH_CLASSES}>
              These terms apply to features and content provided directly by Pomofi. Maintenance,
              policy changes, or outages in the Toss app or Apps in Toss platform may restrict
              access to the service.
            </p>
          </Show>
        </section>

        <section class={SECTION_CLASSES} id="account">
          <h2 class={HEADING_CLASSES}>Article 6. Accounts and user obligations</h2>
          <p class={PARAGRAPH_CLASSES}>
            Users must keep their account and device secure and keep registered or provided
            information up to date. Users must not transfer, lend, or fraudulently use an account or
            authentication method belonging to another person.
          </p>
          <Show
            fallback={
              <p class={PARAGRAPH_CLASSES}>
                The web service is available only to people aged 14 or older. A minor may need a
                legal representative&apos;s consent to purchase a paid service, and a contract made
                without that consent may be cancelled under applicable law.
              </p>
            }
            when={isAppsInToss()}
          >
            <p class={PARAGRAPH_CLASSES}>
              The Apps in Toss service is available only to people aged 19 or older.
            </p>
          </Show>
          <p class={PARAGRAPH_CLASSES}>
            Users must comply with applicable law, these terms, service notices, and third-party
            rights, and must not interfere with stable service operation.
          </p>
        </section>

        <section class={SECTION_CLASSES} id="ai-voice">
          <h2 class={HEADING_CLASSES}>Article 7. AI voice features</h2>
          <p class={PARAGRAPH_CLASSES}>
            Pomofi&apos;s speech synthesis may be processed on the user&apos;s device using models
            such as Supertonic 3. Required model files may be downloaded from external storage, and
            quality and processing time may vary by device.
          </p>
          <p class={PARAGRAPH_CLASSES}>
            When publishing, distributing, or using generated audio in other content, users must
            clearly disclose that it was generated by AI, such as by stating{' '}
            <strong class={EMPHASIS_CLASSES}>“AI-generated voice”</strong>, so that it is not
            mistaken for a recording made by a person.
          </p>
          <p class={PARAGRAPH_CLASSES}>
            The Supertonic 3 model is subject to the BigScience OpenRAIL-M License. Users must
            comply with these terms and the{' '}
            <a
              class={CONTENT_LINK_CLASSES}
              href="https://huggingface.co/Supertone/supertonic-3/blob/3cadd1e/LICENSE"
              rel="noreferrer"
              target="_blank"
            >
              original model license
            </a>
            .
          </p>
        </section>

        <section class={SECTION_CLASSES} id="restricted-uses">
          <h2 class={HEADING_CLASSES}>Article 8. Prohibited conduct</h2>
          <p class={PARAGRAPH_CLASSES}>Users must not:</p>
          <ul class={LIST_CLASSES}>
            <li>Violate law, these terms, or a third party&apos;s rights</li>
            <li>
              Steal another person&apos;s account or information, or impersonate someone without
              consent
            </li>
            <li>Hide that generated audio was made by AI and publish it as a human recording</li>
            <li>
              Defame or harass others, or create or distribute false, illegal, or harmful content
            </li>
            <li>Exploit or harm minors or vulnerable people</li>
            <li>Interfere with service security, the network, or normal operation</li>
            <li>Access the service or data through unauthorized automation</li>
            <li>Violate prohibited uses in model licenses posted in the service</li>
          </ul>
        </section>

        <section class={SECTION_CLASSES} id="rights">
          <h2 class={HEADING_CLASSES}>Article 9. Content and rights</h2>
          <p class={PARAGRAPH_CLASSES}>
            Rights to the service, software, brand, and content provided by Pomofi belong to Pomofi
            or the relevant rights holder. Users may use them only to the extent allowed for using
            the service.
          </p>
          <p class={PARAGRAPH_CLASSES}>
            Pomofi does not provide music-file downloads. Purchasing a music pass does not transfer
            ownership or intellectual-property rights in the audio file; it grants only the right to
            use the music in the service with the purchasing account.
          </p>
          <p class={PARAGRAPH_CLASSES}>
            Users must have the lawful authority to have their content processed by the service.
            Users are responsible for publishing, distributing, and making further use of user
            content and generated results. Pomofi does not guarantee that a generated result creates
            rights or is suitable for a particular purpose.
          </p>
        </section>

        <section class={SECTION_CLASSES} id="payment">
          <h2 class={HEADING_CLASSES}>Article 10. Paid services, payment, and refunds</h2>
          <Show
            fallback={
              <p class={PARAGRAPH_CLASSES}>
                The web service currently does not sell paid products. If paid products are offered
                in the future, their price, contents, conditions, and refund standards will be
                explained separately before purchase.
              </p>
            }
            when={isAppsInToss()}
          >
            <p class={PARAGRAPH_CLASSES}>
              Apps in Toss may sell song- or album-based music passes as one-time purchases. Passes
              do not renew automatically or require a recurring payment, and the purchasing account
              may continue using the music while the Pomofi service remains available.
            </p>
            <p class={PARAGRAPH_CLASSES}>
              Price, music, contents, and payment conditions are shown before purchase. Payment and
              refunds are subject to Apps in Toss and operating-system app-market procedures and the{' '}
              <a class={CONTENT_LINK_CLASSES} href={SERVICE_POLICY_PATHS.refund}>
                refund and withdrawal policy
              </a>
              . These terms and policies do not limit rights guaranteed by applicable law.
            </p>
          </Show>
        </section>

        <section class={SECTION_CLASSES} id="availability">
          <h2 class={HEADING_CLASSES}>Article 11. Changes and suspension</h2>
          <p class={PARAGRAPH_CLASSES}>
            Pomofi may change or temporarily suspend all or part of the service for feature
            improvements, security, maintenance, legal compliance, or operational needs. Predictable
            important changes or suspensions are announced in advance; urgent security problems or
            circumstances beyond control may be announced afterward.
          </p>
          <p class={PARAGRAPH_CLASSES}>
            If the service ends, Pomofi will announce the schedule and available ways to organize
            stored materials with reasonable advance notice.
          </p>
        </section>

        <section class={SECTION_CLASSES} id="termination">
          <h2 class={HEADING_CLASSES}>Article 12. Termination and restrictions</h2>
          <p class={PARAGRAPH_CLASSES}>
            Users may separately withdraw from or request deletion of their web and Apps in Toss
            accounts. Withdrawing from one platform does not automatically delete the account on
            another platform. If payment, refund, or disputes are in progress, processing may
            continue to the extent required by law and policy.
          </p>
          <p class={PARAGRAPH_CLASSES}>
            Pomofi may restrict use to the necessary extent if a user violates law or these terms or
            seriously threatens service safety. Except when urgent action is required, Pomofi will
            explain the reason and how to object.
          </p>
        </section>

        <section class={SECTION_CLASSES} id="responsibility">
          <h2 class={HEADING_CLASSES}>Article 13. Liability</h2>
          <p class={PARAGRAPH_CLASSES}>
            Pomofi is liable under applicable law for damage caused intentionally or through
            negligence. Pomofi is not liable for damage caused by the user, device or network
            problems, or circumstances that Pomofi could not reasonably control.
          </p>
          <p class={PARAGRAPH_CLASSES}>
            AI features may produce inaccurate or unexpected results. Users must not use generated
            results as the sole basis for important decisions or professional advice. This article
            does not exclude liability that cannot be limited under applicable law.
          </p>
        </section>

        <section class={SECTION_CLASSES} id="disputes">
          <h2 class={HEADING_CLASSES}>Article 14. Inquiries and disputes</h2>
          <p class={PARAGRAPH_CLASSES}>
            Users may contact customer support at{' '}
            <a class={CONTENT_LINK_CLASSES} href="mailto:info@pomofi.io">
              info@pomofi.io
            </a>{' '}
            about these terms, restrictions, payment, or refunds and may raise objections. Kuwoong
            will review the inquiry within a reasonable period and explain the result.
          </p>
          <p class={PARAGRAPH_CLASSES}>
            These terms are governed by the laws of the Republic of Korea. If a dispute cannot be
            resolved, the parties may use mediation or litigation under applicable law, and the
            competent court is determined under the Civil Procedure Act and other applicable laws.
          </p>
        </section>
      </>
    </PServicePolicyDocument>
  )
}
