nodeLinker: node-modules

packageExtensions:
  "@vue/test-utils@*":
    dependencies:
      vue: "*"
  babel-loader@*:
    dependencies:
      webpack: "*"
  tsc-watch@*:
    dependencies:
      ttypescript: "*"
  vue-i18n@*:
    dependencies:
      vue: "*"
  vue-jest@*:
    dependencies:
      vue: "*"
  vue-loader@*:
    dependencies:
      webpack: "*"
  vue-router@*:
    dependencies:
      vue: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.0.0.cjs
