services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Pa22w0rd
      MONGO_INITDB_DATABASE: front
    ports:
      - "27017:27017"
