import {defineConfig} from 'oxlint'

const MAX_LINES_PER_FILE = 600

export default defineConfig({
  env: {
    builtin: true,
    node: true,
  },
  ignorePatterns: ['apps/*/dist/*', 'packages/*/dist/*'],
  jsPlugins: [
    'oxlint-plugin-eslint',
    {
      name: 'sort-export-all',
      specifier: 'eslint-plugin-sort-export-all',
    },
    {
      name: 'sort-keys-fix',
      specifier: '@winter-love/oxlint-plugins',
    },
    {
      name: 'solid',
      specifier: 'eslint-plugin-solid',
    },
  ],
  overrides: [
    // eslint-plugin-solid configs/typescript (JSX/TSX only)
    {
      files: ['**/*.{tsx,jsx}'],
      rules: {
        'solid/components-return-once': 'warn',
        'solid/event-handlers': 'warn',
        'solid/imports': 'warn',
        'solid/jsx-no-duplicate-props': 'error',
        'solid/jsx-no-script-url': 'error',
        'solid/jsx-no-undef': ['error', {typescriptEnabled: true}],
        'solid/jsx-uses-vars': 'error',
        'solid/no-array-handlers': 'off',
        'solid/no-destructure': 'error',
        'solid/no-innerhtml': 'error',
        'solid/no-proxy-apis': 'off',
        'solid/no-react-deps': 'warn',
        'solid/no-react-specific-props': 'warn',
        'solid/no-unknown-namespaces': 'off',
        'solid/prefer-classlist': 'off',
        'solid/prefer-for': 'error',
        'solid/prefer-show': 'off',
        'solid/reactivity': 'warn',
        'solid/self-closing-comp': 'warn',
        'solid/style-prop': 'warn',
      },
    },
    // test mock files
    {
      files: ['**/__mocks__/**/*.{ts,mts,js,mjs}'],
      rules: {
        'max-classes-per-file': 'off',
        'unicorn/consistent-function-scoping': 'off',
        'unicorn/no-static-only-class': 'off',
      },
    },
    // storybook files
    {
      files: ['**/*.story.{ts,mts,tsx,js,mjs,jsx}'],
      rules: {
        'no-magic-numbers': 'off',
        'unicorn/consistent-function-scoping': 'off',
      },
    },
    // test files
    {
      files: ['**/*.spec.{ts,mts,tsx,js,mjs,jsx}', '**/*.e2e.{ts,mts,tsx,js,mjs,jsx}'],
      rules: {
        '@typescript-eslint/no-unused-vars': 'off',
        '@typescript-eslint/no-var-requires': 'off',
        'eslint-js/camelcase': 'off',
        'eslint-js/no-magic-numbers': 'off',
        // 'eslint-js/no-invalid-this': 'off',
        'eslint-js/no-mixed-operators': 'off',
        'eslint-js/prefer-named-capture-group': 'off',
        'eslint-js/require-unicode-regexp': 'off',
        'id-length': 'off',
        'max-classes-per-file': 'off',
        'max-lines': 'off',
        'max-lines-per-function': 'off',
        'max-nested-callbacks': 'off',
        'max-params': 'off',
        'max-statements': 'off',
        'no-control-regex': 'off',
        // 'no-mixed-operators': 'off',
        'no-empty-function': 'off',
        'no-magic-numbers': 'off',
        'no-unassigned-vars': 'off',
        'no-unsafe-optional-chaining': 'off',
        'no-void': 'off',
        'prefer-destructuring': 'off',
        'solid/reactivity': 'off',
        'unicorn/consistent-function-scoping': 'off',
        'unicorn/no-invalid-remove-event-listener': 'off',
        'unicorn/no-new-array': 'off',
        'unicorn/no-thenable': 'off',
        'unicorn/no-useless-undefined': 'off',
      },
    },
    // js files
    {
      files: ['**/*.js'],
      rules: {
        '@typescript-eslint/no-var-requires': 'off',
        'unicorn/prefer-module': 'off',
      },
    },
    {
      files: ['.eslintrc.js'],
      rules: {
        'no-magic-numbers': 'off',
      },
    },
    // @winter-love/oxlint-plugins — ESLint rule implementation; relax rules that conflict with AST idioms or rule metadata.
    {
      files: ['packages/oxlint-plugins/**/*.{js,mjs}'],
      rules: {
        'id-length': 'off',
        'max-params': 'off',
        'prefer-destructuring': 'off',
        'sort-keys-fix/sort-keys-fix': 'off',
      },
    },
  ],
  plugins: ['typescript', 'unicorn', 'oxc', 'import', 'promise', 'node'],
  rules: {
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-inferrable-types': 'off',
    '@typescript-eslint/no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTernary: true,
      },
    ],
    '@typescript-eslint/no-unused-vars': [
      'warn',
      {
        args: 'after-used',
        argsIgnorePattern: '^_+$',
        ignoreRestSiblings: true,
      },
    ],
    'accessor-pairs': 'error',
    'array-callback-return': 'error',
    'arrow-body-style': 'off',
    'block-scoped-var': 'error',
    complexity: 'error',
    'consistent-return': 'off',
    curly: 'error',
    'default-case': 'off',
    'default-case-last': 'error',
    'default-param-last': 'error',
    'dot-notation': 'error',
    eqeqeq: ['error', 'smart'],
    'eslint-js/array-bracket-newline': ['error', 'consistent'],
    'eslint-js/array-bracket-spacing': ['error', 'never'],
    'eslint-js/arrow-parens': ['error', 'always'],
    'eslint-js/arrow-spacing': ['error', {after: true, before: true}],
    'eslint-js/block-spacing': ['error', 'never'],
    'eslint-js/brace-style': ['error', '1tbs', {allowSingleLine: true}],
    'eslint-js/camelcase': [
      'error',
      {ignoreGlobals: true, ignoreImports: true, properties: 'always'},
    ],
    'eslint-js/comma-dangle': ['error', 'always-multiline'],
    'eslint-js/comma-spacing': ['error', {after: true, before: false}],
    'eslint-js/computed-property-spacing': ['error', 'never'],
    'eslint-js/consistent-this': 'error',
    'eslint-js/dot-location': ['error', 'property'],
    'eslint-js/eol-last': 'error',
    'eslint-js/func-call-spacing': ['error', 'never'],
    'eslint-js/function-call-argument-newline': ['error', 'consistent'],
    'eslint-js/function-paren-newline': 'off',
    'eslint-js/generator-star-spacing': ['error', {after: true, before: false}],
    'eslint-js/indent': 'off',
    'eslint-js/jsx-quotes': ['error', 'prefer-double'],
    'eslint-js/key-spacing': ['error', {afterColon: true, beforeColon: false, mode: 'strict'}],
    'eslint-js/keyword-spacing': [
      'error',
      {
        after: true,
        before: true,
        overrides: {
          catch: {after: true},
          for: {after: true},
          if: {after: true},
          switch: {after: true},
          while: {after: true},
        },
      },
    ],
    'eslint-js/line-comment-position': ['warn', {position: 'above'}],
    'eslint-js/max-len': [
      'error',
      {code: 120, ignoreComments: true, ignoreTrailingComments: true, ignoreUrls: true},
    ],
    'eslint-js/max-statements-per-line': ['error', {max: 2}],
    'eslint-js/no-buffer-constructor': 'error',
    'eslint-js/no-catch-shadow': 'error',
    // AI_NOTE - Oxfmt removes parentheses around conditional arrow bodies, so this rule cannot be satisfied after formatting.
    'eslint-js/no-confusing-arrow': 'off',
    'eslint-js/no-extra-parens': ['error', 'functions'],
    'eslint-js/no-floating-decimal': 'error',
    'eslint-js/no-implicit-globals': 'off',
    // 'eslint-js/no-invalid-this': 'error',
    'eslint-js/no-magic-numbers': 'off',
    // 'eslint-js/no-mixed-operators': 'error',
    'eslint-js/no-mixed-spaces-and-tabs': 'error',
    'eslint-js/no-multi-spaces': 'error',
    'eslint-js/no-multiple-empty-lines': ['error', {max: 1, maxEOF: 1}],
    'eslint-js/no-new-object': 'error',
    'eslint-js/no-octal-escape': 'error',
    'eslint-js/no-restricted-properties': 'error',
    'eslint-js/no-return-await': 'error',
    'eslint-js/no-tabs': 'error',
    'eslint-js/no-trailing-spaces': 'error',
    'eslint-js/no-undef-init': 'error',
    'eslint-js/no-unreachable-loop': 'error',
    'eslint-js/no-whitespace-before-property': 'error',
    'eslint-js/nonblock-statement-body-position': 'error',
    'eslint-js/object-curly-newline': ['warn', {consistent: true, multiline: true}],
    'eslint-js/object-curly-spacing': ['error', 'never'],
    'eslint-js/one-var': ['error', 'never'],
    'eslint-js/prefer-arrow-callback': 'off',
    'eslint-js/prefer-named-capture-group': 'error',
    'eslint-js/prefer-regex-literals': 'error',
    'eslint-js/quote-props': ['error', 'as-needed'],
    'eslint-js/require-unicode-regexp': 'error',
    'eslint-js/rest-spread-spacing': 'error',
    'eslint-js/semi': ['error', 'never'],
    'eslint-js/space-before-blocks': [
      'error',
      {classes: 'always', functions: 'always', keywords: 'always'},
    ],
    'eslint-js/space-before-function-paren': [
      'error',
      {anonymous: 'always', asyncArrow: 'always', named: 'never'},
    ],
    'eslint-js/space-in-parens': ['error', 'never'],
    'eslint-js/space-infix-ops': 'error',
    'eslint-js/space-unary-ops': 'error',
    'eslint-js/switch-colon-spacing': ['error', {after: true}],
    'eslint-js/template-curly-spacing': ['error', 'never'],
    'eslint-js/template-tag-spacing': ['error', 'never'],
    'eslint-js/wrap-iife': 'error',
    'eslint-js/yield-star-spacing': ['error', 'before'],
    'func-names': ['error', 'as-needed'],
    'func-style': ['error', 'declaration', {allowArrowFunctions: true}],
    'grouped-accessor-pairs': 'error',
    'id-length': [
      'error',
      {
        exceptionPatterns: ['^[A-Z]$'],
        exceptions: ['_', 'x', 'y', 'z', 'p', 'm', 'h', 'w', 'b', 't', 'l', 'r'],
      },
    ],
    'import/named': 'off',
    'import/no-absolute-path': 'off',
    'max-classes-per-file': 'error',
    'max-depth': ['error', {max: 4}],
    'max-lines': ['error', MAX_LINES_PER_FILE],
    'max-lines-per-function': ['error', {max: 150, skipBlankLines: true, skipComments: true}],
    'max-nested-callbacks': ['error', {max: 3}],
    'max-params': ['error', {max: 4}],
    'max-statements': ['error', {max: 40}],
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-await-in-loop': 'error',
    'no-bitwise': 'error',
    'no-caller': 'error',
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-constructor-return': 'error',
    'no-continue': 'error',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-div-regex': 'error',
    'no-duplicate-imports': 'warn',
    'no-else-return': 'error',
    'no-empty-function': 'error',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-implicit-coercion': 'error',
    'no-implied-eval': 'error',
    'no-iterator': 'warn',
    'no-label-var': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    'no-loss-of-precision': 'error',
    'no-magic-numbers': ['error', {ignore: [1, -1, 0, 2], ignoreArrayIndexes: true}],
    'no-multi-assign': 'error',
    'no-multi-str': 'error',
    'no-negated-condition': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-require': 'error',
    'no-new-wrappers': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-param-reassign': 'error',
    'no-plusplus': 'error',
    'no-promise-executor-return': 'error',
    'no-proto': 'error',
    'no-redeclare': 'off',
    'no-restricted-globals': 'error',
    'no-return-assign': 'error',
    'no-script-url': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-shadow': 'off',
    'no-shadow-restricted-names': 'error',
    'no-template-curly-in-string': 'error',
    'no-throw-literal': 'error',
    'no-undef': 'off',
    'no-undefined': 'off',
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-expressions': 'off',
    'no-unused-vars': 'off',
    'no-use-before-define': 'off',
    'no-useless-backreference': 'error',
    'no-useless-call': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'off',
    'no-useless-rename': 'warn',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'no-with': 'error',
    'operator-assignment': ['warn', 'always'],
    'prefer-const': 'error',
    'prefer-destructuring': 'warn',
    'prefer-exponentiation-operator': 'warn',
    'prefer-numeric-literals': 'error',
    'prefer-object-spread': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'warn',
    radix: 'error',
    'sort-export-all/sort-export-all': 'warn',
    'sort-imports': ['warn', {ignoreCase: true, ignoreDeclarationSort: true}],
    'sort-keys-fix/sort-keys-fix': ['warn', 'asc', {natural: true}],
    'unicorn/consistent-function-scoping': 'warn',
    'unicorn/filename-case': ['warn', {cases: {kebabCase: true, pascalCase: true}}],
    'unicorn/new-for-builtins': 'off',
    'unicorn/no-abusive-eslint-disable': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/no-nested-ternary': 'off',
    'unicorn/no-null': 'off',
    'unicorn/prefer-module': 'off',
    'unicorn/prefer-node-protocol': 'off',
    'unicorn/prefer-ternary': 'off',
    yoda: 'error',
  },
  settings: {},
})
