packages:
  - packages/*
  - apps/*
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  nx: true
  sharp: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - aws-sdk
  - core-js
  - core-js-pure
  - esbuild
  - nx
  - sharp
