// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const createEffect: typeof import('react-solid-state')['createEffect']
  const createSignal: typeof import('react-solid-state')['createSignal']
  const onCleanup: typeof import('react-solid-state')['onCleanup']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useObserver: typeof import('react-solid-state')['useObserver']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const withSolid: typeof import('react-solid-state')['withSolid']
}
export {}
