import {describe, expect, it} from 'vitest'
import {
  assignStyle,
  cleanObject,
  createClientStorage,
  createInverseOrderParameters,
  createMonotonicId,
  createPrevArgs,
  createStateUpdater,
  createStateUpdaterWithArgs,
  createUuid,
  eventOptions,
  formatBytes,
  formatNumber,
  getByPath,
  getElement,
  getItem,
  invertParams,
  isScrollable,
  isScrollAble,
  isSupportPassive,
  match,
  matchRun,
  mergeStyles,
  noNaN,
  normalizeEventOptions,
  numberTo,
  omitUndefinedProperties,
  resolveElement,
  safeNumber,
  setByPath,
  setItem,
  setStyle,
  stateful,
  statefulWithArgs,
  storage,
  supportsPassiveEvents,
  toBytesSize,
  toFormatNumber,
  trackPreviousArgs,
} from '../'

describe('renamed exports', () => {
  it.each([
    [createUuid, createMonotonicId],
    [getItem, getByPath],
    [setItem, setByPath],
    [isScrollAble, isScrollable],
    [isSupportPassive, supportsPassiveEvents],
    [eventOptions, normalizeEventOptions],
    [getElement, resolveElement],
    [createPrevArgs, trackPreviousArgs],
    [matchRun, match],
    [createInverseOrderParameters, invertParams],
    [noNaN, safeNumber],
    [numberTo, safeNumber],
    [toBytesSize, formatBytes],
    [toFormatNumber, formatNumber],
    [setStyle, mergeStyles],
    [assignStyle, mergeStyles],
    [cleanObject, omitUndefinedProperties],
    [stateful, createStateUpdater],
    [statefulWithArgs, createStateUpdaterWithArgs],
    [storage, createClientStorage],
  ])('should retain deprecated aliases', (deprecatedExport, canonicalExport) => {
    expect(deprecatedExport).toBe(canonicalExport)
  })
})
