export * from './is-camel-case'
export * from './is-element'
export * from './is-nil'
export * from './is-null'
export * from './is-pascal-case'
export * from './is-promise'
export * from './is-undefined'
export * from './is-window'
