# compose
version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: foo-bar
    volumes:
      - ./data/postgres/:/data/postgresql/
