// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    QFooter: typeof import('quasar')['QFooter']
    QLayout: typeof import('quasar')['QLayout']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QToolbar: typeof import('quasar')['QToolbar']
  }
}

export { }
