/* eslint-disable @typescript-eslint/no-explicit-any */
/// <reference types="@solidjs/start/env" />
/// <reference types="vite/client" />
/// <reference types="vitest" />
/// <reference types="@testing-library/jest-dom/vitest" />

import type {RouteDefinition as _RouteDefinition} from '@solidjs/router'

declare module '~icons/*' {
  const icon: any
  export default icon
}

declare module '*.json' {
  const value: object
  export default value
}

declare module '*.lottie' {
  const src: string
  export default src
}

declare module '@supabase/supabase-js' {
  /**
   * Extend the Database type to include the supabase tables (generated by Drizzle)
   */
  export type Database = import('../.supabase/supabase').Database
}

declare module '@solidjs/start/server' {
  /**
   * Extend the RequestEventLocals interface to include the user and supabase properties
   */
  interface RequestEventLocals {
    user?: import('@supabase/supabase-js').User | null
    supabase?: import('@supabase/supabase-js').SupabaseClient
  }
}

interface PageOpenGraphMetadata {
  title: string
  description: string
  image?: string
}

declare global {
  /**
   * Extend the RouteDefinition type to include the public property
   */
  interface RouteDefinition extends _RouteDefinition {
    info: {
      /**
       * Controls route access based on user authentication status.
       * @see src/components/auth-guard/allow.ts
       *
       * - `true`: Accessible to everyone (public route)
       * - `false`: Requires authentication (private route, redirects to sign-in if not logged in)
       * - `'only-unauthorized'`: Only accessible when NOT logged in (e.g., sign-in, sign-up pages)
       *   - Logged-in users are redirected to home
       */
      public?: 'only-unauthorized' | boolean
      /**
       * page open graph metadata
       * @see src/components/page-meta/RouteMeta.tsx
       */
      meta?: PageOpenGraphMetadata
    }
  }
}
