// css var name for uno css "height-var"
export const HEIGHT_VAR = '--var-height'
export const WIDTH_VAR = '--var-width'
export const LEFT_VAR = '--var-left'
export const RIGHT_VAR = '--var-right'
export const TOP_VAR = '--var-top'
export const BOTTOM_VAR = '--var-bottom'
export const SCROLL_X_PERCENT = '--ver-scroll-x-percent'
export const SCROLL_Y_PERCENT = '--ver-scroll-y-percent'
export const BAR_PERCENT = '--ver-bar-percent'
