export const numberFieldDescendants = [
  '[&_.editor-number-field]:[height:var(--editor-control-height,_1.40625rem)]',
  '[&_.editor-number-field]:relative [&_.editor-number-field]:flex [&_.editor-number-field]:box-border',
  '[&_.editor-number-field]:w-full [&_.editor-number-field]:min-w-0 [&_.editor-number-field]:items-center',
  '[&_.editor-number-field]:overflow-hidden [&_.editor-number-field]:[border:0.0625rem_solid_#35413d]',
  '[&_.editor-number-field]:[border-radius:0.3125rem] [&_.editor-number-field]:[color:#dfe8e4]',
  '[&_.editor-number-field]:[background:#121816]',
  '[&_.editor-number-field[data-bounded]::before]:absolute',
  '[&_.editor-number-field[data-bounded]::before]:[inset:0_auto_0_0]',
  '[&_.editor-number-field[data-bounded]::before]:[width:var(--number-field-progress)]',
  '[&_.editor-number-field[data-bounded]::before]:[background:#24443b]',
  "[&_.editor-number-field[data-bounded]::before]:[content:'']",
  '[&_.editor-number-field[data-bounded]::before]:pointer-events-none',
  '[&_.editor-number-field:focus-within]:[border-color:#64e5c4]',
  '[&_.editor-number-field:focus-within]:[outline:0.0625rem_solid_#64e5c4]',
  '[&_.editor-number-field:focus-within]:[outline-offset:0.0625rem]',
  '[&_.editor-number-field:has(input:disabled)]:[border-color:#303936]',
  '[&_.editor-number-field:has(input:disabled)]:[color:#77837e]',
  '[&_.editor-number-field:has(input:disabled)]:[background:#111613]',
  "[&_.editor-number-field_>_input[type='number']]:relative",
  "[&_.editor-number-field_>_input[type='number']]:w-full",
  "[&_.editor-number-field_>_input[type='number']]:min-w-0",
  "[&_.editor-number-field_>_input[type='number']]:[flex:1]",
  "[&_.editor-number-field_>_input[type='number']]:[padding:0.3125rem_0.4375rem]",
  "[&_.editor-number-field_>_input[type='number']]:[border:0]",
  "[&_.editor-number-field_>_input[type='number']]:[border-radius:0]",
  "[&_.editor-number-field_>_input[type='number']]:[outline:0]",
  "[&_.editor-number-field_>_input[type='number']]:[color:inherit]",
  "[&_.editor-number-field_>_input[type='number']]:[background:transparent]",
  "[&_.editor-number-field_>_input[type='number']]:[font:inherit]",
  "[&_.editor-number-field_>_input[type='number']]:[cursor:ew-resize]",
  "[&_.editor-number-field_>_input[type='number']]:[appearance:textfield]",
  "[&_.editor-number-field_>_input[type='number']]:touch-none",
  "[&_.editor-number-field_>_input[type='number']:not(:focus)]:select-none",
  "[&_.editor-number-field_>_input[type='number']:focus]:[cursor:text]",
  "[&_.editor-number-field.scrubbing_>_input[type='number']]:[cursor:ew-resize]",
  "[&_.editor-number-field.scrubbing_>_input[type='number']]:select-none",
  "[&_.editor-number-field_>_input[type='number']::-webkit-inner-spin-button]:m-0",
  "[&_.editor-number-field_>_input[type='number']::-webkit-inner-spin-button]:[appearance:none]",
  "[&_.editor-number-field_>_input[type='number']::-webkit-outer-spin-button]:m-0",
  "[&_.editor-number-field_>_input[type='number']::-webkit-outer-spin-button]:[appearance:none]",
  '[&_.editor-number-field_>_span]:relative [&_.editor-number-field_>_span]:[padding-right:0.4375rem]',
  '[&_.editor-number-field_>_span]:[color:#81908a]',
  "[&_.editor-number-field_>_span]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
  '[&_.editor-number-field_>_span]:[font-size:0.5625rem] [&_.editor-number-field_>_span]:pointer-events-none',
  '[&_.editor-number-step]:relative [&_.editor-number-step]:grid [&_.editor-number-step]:[width:1.25rem]',
  '[&_.editor-number-step]:[align-self:stretch] [&_.editor-number-step]:[flex:0_0_1.25rem]',
  '[&_.editor-number-step]:place-items-center [&_.editor-number-step]:p-0 [&_.editor-number-step]:[border:0]',
  '[&_.editor-number-step]:[border-radius:0] [&_.editor-number-step]:[color:#91a19a]',
  '[&_.editor-number-step]:[background:#18201d] [&_.editor-number-step]:[font:inherit]',
  '[&_.editor-number-step]:cursor-pointer',
  '[&_.editor-number-step.decrement]:[border-right:0.0625rem_solid_#35413d]',
  '[&_.editor-number-step.increment]:[border-left:0.0625rem_solid_#35413d]',
  '[&_.editor-number-step:hover:not(:disabled)]:[color:#dffff6]',
  '[&_.editor-number-step:hover:not(:disabled)]:[background:#29443b]',
  '[&_.editor-number-step:focus-visible]:[outline:0.0625rem_solid_#64e5c4]',
  '[&_.editor-number-step:focus-visible]:[outline-offset:-0.125rem]',
  '[&_.editor-number-step:disabled]:[color:#4b5752] [&_.editor-number-step:disabled]:cursor-default',
  '[&_.editor-number-step_>_.puppet-icon]:[width:0.75rem] [&_.editor-number-step_>_.puppet-icon]:[height:0.75rem]',
]

export const controlShortcuts = {
  'editor-tooltip': [
    'fixed inset-auto m-2 w-max max-w-[min(20rem,calc(100vw_-_1rem))] box-border overflow-visible',
    'rounded-md border border-solid border-[#35413d] bg-[#121816] px-2 py-1 text-xs leading-5 text-[#edf4f0]',
    'shadow-[0_2px_4px_#0007,0_8px_18px_#0006] [overflow-wrap:anywhere] [&[hidden]]:hidden',
    '[position-anchor:var(--editor-tooltip-anchor)] [position-area:top]',
    '[position-try-fallbacks:flip-block,top_span-right,top_span-left,bottom_span-right,bottom_span-left]',
    '[position-visibility:anchors-visible]',
  ],
  'editor-tooltip-arrow': [
    'pointer-events-none absolute w-2.5 h-1.5 bg-[#35413d] [translate:-50%_0]',
    '[left:clamp(0.5rem,var(--editor-tooltip-arrow-x),calc(100%_-_0.5rem))]',
    "after:[content:''] after:absolute after:bg-[#121816] after:[clip-path:inherit]",
    'data-[side=top]:bottom-[-6px] data-[side=top]:[clip-path:polygon(0_0,100%_0,50%_100%)]',
    'data-[side=top]:after:[inset:0_1px_1px]',
    'data-[side=bottom]:top-[-6px] data-[side=bottom]:[clip-path:polygon(50%_0,100%_100%,0_100%)]',
    'data-[side=bottom]:after:[inset:1px_1px_0]',
  ],
  'editor-control': [
    '[--editor-control-height:1.40625rem]',
    "[&[data-control-size='md']]:[--editor-control-height:1.75rem]",
  ],
  'editor-range-input': '[height:var(--editor-control-height,_1.40625rem)] box-border',
  'editor-segmented-field': [
    'box-border inline-flex w-fit max-w-full items-stretch gap-0.5 p-0.5',
    'rounded-md border border-solid border-[#313b37]',
    '[height:var(--editor-control-height,_1.40625rem)] bg-[#0d1210]',
    "[&[data-size='md']_button]:text-[0.6875rem] [&[data-size='md']_button]:px-3",
    '[&_button]:border-0 [&_button]:rounded [&_button]:px-2 [&_button]:py-0',
    '[&_button]:text-[0.5625rem] [&_button]:leading-none [&_button]:bg-transparent [&_button]:text-[#7f8d88]',
    '[&_button]:cursor-pointer [&_button:disabled]:opacity-40',
    "[&_button[aria-pressed='true']]:bg-[#26332f] [&_button[aria-pressed='true']]:text-[#e9f3ef]",
    '[&_button:focus-visible]:outline [&_button:focus-visible]:outline-[#64e5c4]',
  ],
  'editor-text-input': [
    'box-border [height:var(--editor-control-height,_1.40625rem)]',
    '[min-height:var(--editor-control-height,_1.40625rem)]',
  ],
  'editor-checkbox':
    'relative inline-flex shrink-0 align-middle items-center [height:var(--editor-control-height,_1.40625rem)]',
  'editor-checkbox-control': [
    'inline-grid w-3.5 h-3.5 place-items-center rounded border border-solid border-[#60776a] text-[#11231a]',
    '[&[data-checked]]:bg-[#79d7b1] [&[data-checked]]:border-[#79d7b1]',
    '[&[data-disabled]]:opacity-40 [&[data-focus-visible]]:outline [&[data-focus-visible]]:outline-[#a4f3d9]',
  ],

  'editor-button': [
    '[.puppet-editor_&.editor-button]:[height:var(--editor-control-height,_1.40625rem)]',
    '[.puppet-editor_&.editor-button]:[min-height:var(--editor-control-height,_1.40625rem)]',
    '[.puppet-editor_&.editor-button]:[padding-block:0]',
    '[height:var(--editor-control-height,_1.40625rem)] [min-height:var(--editor-control-height,_1.40625rem)]',
    'box-border inline-flex items-center justify-center gap-1.5 px-2 py-0',
    'border border-solid border-[#35413d] rounded-md bg-[#171e1b] text-[#b9c5c0] text-xs leading-4',
    '[font-family:inherit] cursor-pointer whitespace-nowrap',
    'hover:bg-[#293832] hover:text-[#f4f8f6]',
    'focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-[#64e5c4]',
    'disabled:opacity-40 disabled:cursor-not-allowed',
    "[&[aria-pressed='true']]:bg-[#24443b] [&[aria-pressed='true']]:border-[#64e5c4]",
    '[&[data-selected]]:bg-[#24443b] [&[data-selected]]:border-[#64e5c4] [&[data-selected]]:text-[#e8f0ed]',
  ],
  'editor-select-list': 'm-0 p-0 list-none',
  'editor-color-area': [
    '[.puppet-editor_&]:relative',
    '[.puppet-editor_&]:[height:8.5rem]',
    '[.puppet-editor_&]:[border-radius:0.25rem]',
    '[.puppet-editor_&]:touch-none',
  ],

  'editor-color-field': [
    '[.puppet-editor_&_input]:box-border [.puppet-editor_&_input]:[height:var(--editor-control-height)]',
    '[.puppet-editor_&]:grid',
    '[.puppet-editor_&]:[grid-template-columns:1.75rem_minmax(0,_1fr)]',
    '[.puppet-editor_&]:[gap:0.25rem]',
    '[.puppet-editor_&_input]:w-full',
    '[.puppet-editor_&_input]:min-w-0',
    '[.puppet-editor_&_input]:[font-family:monospace]',
    '[.puppet-editor_&_input]:[font-size:0.6875rem]',
  ],
  'editor-select-trigger': 'editor-button w-full justify-between min-w-0 [&_span]:truncate',
  'editor-color-picker': [
    '[.puppet-editor_&]:[width:14rem]',
    '[.puppet-editor_&]:grid',
    '[.puppet-editor_&]:[gap:0.625rem]',
    '[.puppet-editor_&_label]:block',
    '[.puppet-editor_&_label]:[font-size:0.625rem]',
    '[.puppet-editor_&_label]:[margin-bottom:0.375rem]',
  ],
  'editor-color-row': [
    '[.puppet-editor_&]:grid',
    '[.puppet-editor_&]:[grid-template-columns:3.375rem_minmax(0,_1fr)]',
    '[.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:[gap:0.5rem]',
    '[.puppet-editor_&]:[font-size:0.5625rem]',
    '[.puppet-editor_&]:[color:#84918c]',
  ],
  'editor-color-swatch': [
    '[.puppet-editor_&]:block',
    '[.puppet-editor_&]:[width:1rem]',
    '[.puppet-editor_&]:[height:1rem]',
    '[.puppet-editor_&]:[border-radius:0.1875rem]',
    '[.puppet-editor_&]:[box-shadow:inset_0_0_0_1px_rgb(255_255_255_/_20%)]',
  ],
  'editor-color-thumb': [
    '[.puppet-editor_&]:block',
    '[.puppet-editor_&]:[width:0.875rem]',
    '[.puppet-editor_&]:[height:0.875rem]',
    '[.puppet-editor_&]:[border:2px_solid_white]',
    '[.puppet-editor_&]:[border-radius:50%]',
    '[.puppet-editor_&]:[box-shadow:0_0_0_1px_#17211e]',
    '[.puppet-editor_&:focus-visible]:[outline:2px_solid_#64e5c4]',
  ],
  'editor-color-track': [
    '[.puppet-editor_&]:relative',
    '[.puppet-editor_&]:[height:0.75rem]',
    '[.puppet-editor_&]:[border-radius:0.375rem]',
    '[.puppet-editor_&]:[margin:0.5rem_0]',
    '[.puppet-editor_&]:touch-none',
  ],
  'editor-color-trigger': [
    '[.puppet-editor_&]:box-border [.puppet-editor_&]:[height:var(--editor-control-height)]',
    '[.puppet-editor_&]:grid',
    '[.puppet-editor_&]:place-items-center',
    '[.puppet-editor_&]:p-0',
    '[.puppet-editor_&]:[border:1px_solid_#45544f]',
    '[.puppet-editor_&]:[border-radius:0.375rem]',
    '[.puppet-editor_&]:[background:#17211e]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&:focus-visible]:[outline:2px_solid_#64e5c4]',
    '[.puppet-editor_&:disabled]:[opacity:0.42]',
  ],
  'editor-number-field': [
    '[.puppet-editor_&]:[height:var(--editor-control-height)]',
    '[.puppet-editor_&]:relative [.puppet-editor_&]:flex [.puppet-editor_&]:box-border',
    '[.puppet-editor_&]:w-full [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:items-center',
    '[.puppet-editor_&]:overflow-hidden [.puppet-editor_&]:[border:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&]:[border-radius:0.3125rem] [.puppet-editor_&]:[color:#dfe8e4]',
    '[.puppet-editor_&]:[background:#121816]',
    '[.puppet-editor_&[data-bounded]::before]:absolute',
    '[.puppet-editor_&[data-bounded]::before]:[inset:0_auto_0_0]',
    '[.puppet-editor_&[data-bounded]::before]:[width:var(--number-field-progress)]',
    '[.puppet-editor_&[data-bounded]::before]:[background:#24443b]',
    "[.puppet-editor_&[data-bounded]::before]:[content:'']",
    '[.puppet-editor_&[data-bounded]::before]:pointer-events-none',
    '[.puppet-editor_&:focus-within]:[border-color:#64e5c4]',
    '[.puppet-editor_&:focus-within]:[outline:0.0625rem_solid_#64e5c4]',
    '[.puppet-editor_&:focus-within]:[outline-offset:0.0625rem]',
    '[.puppet-editor_&:has(input:disabled)]:[border-color:#303936]',
    '[.puppet-editor_&:has(input:disabled)]:[color:#77837e]',
    '[.puppet-editor_&:has(input:disabled)]:[background:#111613]',
    "[.puppet-editor_&_>_input[type='number']]:relative [.puppet-editor_&_>_input[type='number']]:w-full",
    "[.puppet-editor_&_>_input[type='number']]:min-w-0 [.puppet-editor_&_>_input[type='number']]:[flex:1]",
    "[.puppet-editor_&_>_input[type='number']]:[padding:0.3125rem_0.4375rem]",
    "[.puppet-editor_&_>_input[type='number']]:[border:0]",
    "[.puppet-editor_&_>_input[type='number']]:[border-radius:0]",
    "[.puppet-editor_&_>_input[type='number']]:[outline:0]",
    "[.puppet-editor_&_>_input[type='number']]:[color:inherit]",
    "[.puppet-editor_&_>_input[type='number']]:[background:transparent]",
    "[.puppet-editor_&_>_input[type='number']]:[font:inherit]",
    "[.puppet-editor_&_>_input[type='number']]:[cursor:ew-resize]",
    "[.puppet-editor_&_>_input[type='number']]:[appearance:textfield]",
    "[.puppet-editor_&_>_input[type='number']]:touch-none",
    "[.puppet-editor_&_>_input[type='number']:not(:focus)]:select-none",
    "[.puppet-editor_&_>_input[type='number']:focus]:[cursor:text]",
    "[.puppet-editor_&.scrubbing_>_input[type='number']]:[cursor:ew-resize]",
    "[.puppet-editor_&.scrubbing_>_input[type='number']]:select-none",
    "[.puppet-editor_&_>_input[type='number']::-webkit-inner-spin-button]:m-0",
    "[.puppet-editor_&_>_input[type='number']::-webkit-inner-spin-button]:[appearance:none]",
    "[.puppet-editor_&_>_input[type='number']::-webkit-outer-spin-button]:m-0",
    "[.puppet-editor_&_>_input[type='number']::-webkit-outer-spin-button]:[appearance:none]",
    '[.puppet-editor_&_>_span]:relative [.puppet-editor_&_>_span]:[padding-right:0.4375rem]',
    '[.puppet-editor_&_>_span]:[color:#81908a]',
    "[.puppet-editor_&_>_span]:[font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[.puppet-editor_&_>_span]:[font-size:0.5625rem] [.puppet-editor_&_>_span]:pointer-events-none',
  ],
  'editor-diamond-button':
    '[.puppet-editor_&]:box-border [.puppet-editor_&]:min-h-0 [.puppet-editor_&]:min-w-0 [.puppet-editor_&]:p-0',
  'editor-number-step': [
    '[.puppet-editor_&]:relative [.puppet-editor_&]:grid [.puppet-editor_&]:[width:1.25rem]',
    '[.puppet-editor_&]:[align-self:stretch] [.puppet-editor_&]:[flex:0_0_1.25rem]',
    '[.puppet-editor_&]:place-items-center [.puppet-editor_&]:p-0 [.puppet-editor_&]:[border:0]',
    '[.puppet-editor_&]:[border-radius:0] [.puppet-editor_&]:[color:#91a19a]',
    '[.puppet-editor_&]:[background:#18201d] [.puppet-editor_&]:[font:inherit]',
    '[.puppet-editor_&]:cursor-pointer',
    '[.puppet-editor_&.decrement]:[border-right:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&.increment]:[border-left:0.0625rem_solid_#35413d]',
    '[.puppet-editor_&:hover:not(:disabled)]:[color:#dffff6]',
    '[.puppet-editor_&:hover:not(:disabled)]:[background:#29443b]',
    '[.puppet-editor_&:focus-visible]:[outline:0.0625rem_solid_#64e5c4]',
    '[.puppet-editor_&:focus-visible]:[outline-offset:-0.125rem]',
    '[.puppet-editor_&:disabled]:[color:#4b5752] [.puppet-editor_&:disabled]:cursor-default',
    '[.puppet-editor_&_>_.puppet-icon]:[width:0.75rem] [.puppet-editor_&_>_.puppet-icon]:[height:0.75rem]',
  ],
  'editor-context-menu-content': [
    '[min-width:11.25rem] [padding:0.3125rem] [border:0.0625rem_solid_#35413d] [border-radius:0.4375rem]',
    '[outline:none] [color:#dbe5e1] [background:#121816] [box-shadow:0_0.625rem_1.75rem_rgb(0_0_0_/_36%)]',
    '[&[data-closed]]:hidden',
  ],
  'editor-context-menu-item': [
    'flex [min-height:1.875rem] [gap:1.125rem] items-center [padding:0.3125rem_0.5rem]',
    '[border-radius:0.3125rem] [outline:none] [font-size:0.625rem] cursor-default select-none',
    '[&[data-highlighted]]:[color:#effffb] [&[data-highlighted]]:[background:#28594c]',
    '[&.danger]:[color:#f3aaa5]',
    '[&.danger[data-highlighted]]:[color:#fff1ef] [&.danger[data-highlighted]]:[background:#873b37]',
    '[&[data-disabled]]:[opacity:0.42] [&[data-disabled]]:pointer-events-none',
    '[&[data-highlighted]_.editor-context-menu-shortcut]:[color:currentcolor]',
  ],
  'editor-context-menu-separator': [
    '[height:0.0625rem] [margin:0.25rem_0.375rem] [border:0] [background:#2d3834]',
  ],
  'editor-context-menu-shortcut': [
    "[margin-left:auto] [color:#788681] [font-family:'SFMono-Regular',_Consolas,_monospace]",
    '[font-size:0.5625rem]',
  ],
}
