export const SIGN_IN_PATH = '/auth/sign-in'
export const SIGN_UP_PATH = '/auth/sign-up'
export const RESET_PASSWORD_PATH = '/auth/reset-password'
export const CHANGE_PASSWORD_PATH = '/auth/change-password'
export const VERIFY_EMAIL_PATH = '/auth/verify-email'
export const HOME_PATH = '/'
