const MINUTES_PER_SUBMISSION_RECOVERY_DELAY = 30
const SECONDS_PER_MINUTE = 60
const MILLISECONDS_PER_SECOND = 1000

export const SUBMITTED_RESPONSE_RECOVERY_DELAY_MILLISECONDS =
  MINUTES_PER_SUBMISSION_RECOVERY_DELAY * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND

export const UNKNOWN_SUBMISSION_EXPIRATION_MILLISECONDS =
  MINUTES_PER_SUBMISSION_RECOVERY_DELAY * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND

/** Returns the deadline after which an ambiguous submission can be terminated. */
export const getSubmissionRecoveryDeadline = (submittedAt: Date): Date =>
  new Date(submittedAt.getTime() + UNKNOWN_SUBMISSION_EXPIRATION_MILLISECONDS)
