import {describe, expect, test, vi} from 'vitest'
import {createSelectedPlayback} from '../create-selected-playback'

const motions = [
  {duration: 2, id: 'idle', tracks: []},
  {duration: 1, id: 'mouth', tracks: []},
]
const setup = () => createSelectedPlayback({motions})

describe('createSelectedPlayback', () => {
  test('should loop the selected motion and freeze its time while paused', () => {
    const playback = setup()
    playback.advance(2.5)
    expect(playback.getFrame()).toEqual({duration: 2, motionId: 'idle', time: 0.5})
    playback.pause()
    playback.advance(1)
    expect(playback.isPlaying()).toBe(false)
    expect(playback.getFrame().time).toBe(0.5)
    playback.resume()
    playback.advance(0.5)
    expect(playback.getFrame().time).toBe(1)
  })
  test('should stop contributions without reviving them through resume and restore on play', () => {
    const playback = setup()
    playback.stop()
    playback.resume()
    playback.seek(1)
    expect(playback.frames()).toEqual([])
    expect(playback.isPlaying()).toBe(false)
    expect(playback.getFrame()).toEqual({duration: 0, motionId: null, time: 1})
    expect(playback.play({speed: 0})).toBe(true)
    expect(playback.frames()[0]?.time).toBe(1)
    expect(playback.isPlaying()).toBe(false)
    expect(playback.play()).toBe(false)
  })
  test('should select motions without starting a stopped or paused timeline', () => {
    const playback = setup()
    expect(playback.select('idle')).toBe('unchanged')
    expect(playback.select('missing')).toBe('missing')
    playback.stop()
    expect(playback.select('mouth')).toBe('changed')
    expect(playback.getFrame()).toEqual({duration: 1, motionId: 'mouth', time: 0})
    expect(playback.isPlaying()).toBe(false)
    expect(playback.frames()).toHaveLength(1)
  })
  test('should hold the final frame and notify one-shot completion once', () => {
    const playback = setup()
    const onComplete = vi.fn()
    expect(playback.playMotion('mouth', {loop: false, onComplete, speed: 2})).toBe(true)
    const complete = playback.advance(0.5)
    expect(playback.isPlaying()).toBe(false)
    expect(playback.getFrame().time).toBe(1)
    complete?.()
    expect(onComplete).toHaveBeenCalledOnce()
    expect(playback.advance(1)).toBeUndefined()
    expect(playback.frames()).toHaveLength(1)
  })
  test('should cancel stale completion when the final-frame listener replaces the motion', () => {
    const playback = setup()
    const onComplete = vi.fn()
    playback.playMotion('idle', {loop: false, onComplete})
    const complete = playback.advance(2)
    playback.playMotion('mouth')
    complete?.()
    expect(onComplete).not.toHaveBeenCalled()
    playback.advance(0.25)
    expect(playback.getFrame()).toEqual({duration: 1, motionId: 'mouth', time: 0.25})
  })
  test('should reconcile document edits and cancel completion without changing pause state', () => {
    const playback = setup()
    const onComplete = vi.fn()
    playback.playMotion('idle', {loop: false, onComplete})
    playback.seek(1.5)
    playback.pause()
    playback.update([{...motions[0]!, duration: 1}])
    expect(playback.getFrame()).toEqual({duration: 1, motionId: 'idle', time: 1})
    expect(playback.isPlaying()).toBe(false)
    playback.resume()
    playback.advance(0.25)?.()
    expect(onComplete).not.toHaveBeenCalled()
    expect(playback.getFrame().time).toBe(0.25)
  })
  test('should reject invalid numbers before changing the selection and preserve missing-motion state', () => {
    const playback = setup()
    playback.seek(0.5)
    expect(() => playback.playMotion('mouth', {speed: -1})).toThrow(RangeError)
    expect(() => playback.play({speed: Infinity})).toThrow(RangeError)
    expect(() => playback.setSpeed(NaN)).toThrow(RangeError)
    expect(() => playback.seek(NaN)).toThrow(RangeError)
    expect(playback.playMotion('missing')).toBe(false)
    expect(playback.getFrame()).toEqual({duration: 2, motionId: 'idle', time: 0.5})
    playback.seek(-1)
    expect(playback.getFrame().time).toBe(0)
    playback.seek(9)
    expect(playback.getFrame().time).toBe(2)
  })
})
