/** @vitest-environment jsdom */
import {cleanup, renderHook} from '@solidjs/testing-library'
import {afterEach, beforeEach, expect, it, vi} from 'vitest'
import {useUiAutoHide} from '../use-ui-auto-hide'

beforeEach(() => {
  vi.useFakeTimers()
  localStorage.clear()
})
afterEach(() => {
  cleanup()
  vi.useRealTimers()
})
it('should remain visible by default and hide only after the selected inactivity delay', () => {
  const {result} = renderHook(useUiAutoHide)
  vi.advanceTimersByTime(300_000)
  expect(result.hidden()).toBe(false)
  result.onEnabledChange(true)
  result.onSecondsChange(15)
  vi.advanceTimersByTime(14_999)
  expect(result.hidden()).toBe(false)
  vi.advanceTimersByTime(1)
  expect(result.hidden()).toBe(true)
  window.dispatchEvent(new Event('pointermove'))
  expect(result.hidden()).toBe(false)
  vi.advanceTimersByTime(15_000)
  expect(result.hidden()).toBe(true)
  result.onEnabledChange(false)
  expect(result.hidden()).toBe(false)
})
it('should restore both preferences without losing the duration when disabled', () => {
  const first = renderHook(useUiAutoHide)
  first.result.onSecondsChange(60)
  first.result.onEnabledChange(true)
  first.result.onEnabledChange(false)
  first.cleanup()
  const {result} = renderHook(useUiAutoHide)
  expect(result.enabled()).toBe(false)
  expect(result.seconds()).toBe(60)
})
it('should keep dialogs visible and cancel timers on disposal', () => {
  const dialog = document.createElement('div')
  dialog.setAttribute('role', 'dialog')
  vi.spyOn(dialog, 'getClientRects').mockReturnValue({length: 1} as DOMRectList)
  document.body.append(dialog)
  const view = renderHook(useUiAutoHide)
  view.result.onEnabledChange(true)
  vi.advanceTimersByTime(30_000)
  expect(view.result.hidden()).toBe(false)
  dialog.remove()
  window.dispatchEvent(new Event('keydown'))
  vi.advanceTimersByTime(30_000)
  expect(view.result.hidden()).toBe(true)
  view.cleanup()
  expect(vi.getTimerCount()).toBe(0)
})
it('should restart the countdown when the duration changes and ignore invalid durations', () => {
  const {result} = renderHook(useUiAutoHide)
  result.onEnabledChange(true)
  vi.advanceTimersByTime(20_000)
  result.onSecondsChange(5)
  vi.advanceTimersByTime(4_999)
  expect(result.hidden()).toBe(false)
  vi.advanceTimersByTime(1)
  expect(result.hidden()).toBe(true)
  result.onSecondsChange(Number.NaN)
  expect(result.seconds()).toBe(5)
})
it('should restore visibility and restart the delay when returning to the document', () => {
  const {result} = renderHook(useUiAutoHide)
  result.onEnabledChange(true)
  vi.advanceTimersByTime(30_000)
  expect(result.hidden()).toBe(true)
  document.dispatchEvent(new Event('visibilitychange'))
  expect(result.hidden()).toBe(false)
})

it('should ignore closed dialog elements when hiding UI', () => {
  const dialog = document.createElement('div')
  dialog.setAttribute('role', 'dialog')
  document.body.append(dialog)
  const {result} = renderHook(useUiAutoHide)
  result.onEnabledChange(true)
  vi.advanceTimersByTime(30_000)
  expect(result.hidden()).toBe(true)
  dialog.remove()
})
