name: Build and Deploy
on:
  push:
    branches:
      - dev
env:
  PNPM_VERSION: 7.1.0
  NODE_VERSION: 16
jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Prepare Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          # key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build:coong-client
